import type { TopicInfographicItem } from './topicInfographicsData';

export const commonTopicInfographicsMap: Record<string, TopicInfographicItem> = {
  // ==========================================
  // 5. CHINESE (6 Topics)
  // ==========================================
  'chinese/phonetics-characters': {
    topicSlug: 'phonetics-characters',
    title: '形音義辨析與六書構字法理',
    subtitle: '象形、指事、會意、形聲、轉注、假借與常考易混淆同音字',
    conceptType: 'comparative-matrix',
    icon: '✍️',
    diagramTitle: '六書構字架構（獨體文 vs 合體字）與高頻統測形音義辨析樹狀圖',
    diagramDescription: '展示象形與指事為「獨體為文」，會意與形聲（佔90%）為「合體為字」，及常考一字多音多義辨析。',
    formulaBanner: '六書原則: 獨體 (象形/指事) ； 合體 (會意/形聲) ； 用字之法 (轉注/假借)',
    visualHighlights: [
      { label: '象形 (Pictograph)', desc: '畫成其物，隨體詰詘（如：日、月、木、水、人）', badge: '純圖像' },
      { label: '指事 (Ideograph)', desc: '視而可識，察而見意，在象形基礎上加抽象符號（如：上、下、本、末、刃）', badge: '抽象指示' },
      { label: '形聲 (Picto-phonetic)', desc: '一邊表意（形符）、一邊表音（聲符），漢字中最龐大族群（如：河、江、材、築）', badge: '佔漢字 90%' },
    ],
    keyTakeaways: [
      '「本」與「末」是指事字（在木之下部或上部加一橫指示部位）；「休」與「武」是會意字。',
      '形聲字辨析：注意「形旁」代表事物類別，「聲旁」代表發音，遇罕見字可先從部首推測詞義。',
      '統測注音考點聚焦於一字多音（如「折」騰 zhē、「折」斷 zhé、「折」本 shé）。',
    ],
  },
  'chinese/idioms-vocabulary': {
    topicSlug: 'idioms-vocabulary',
    title: '成語典故、褒貶色彩與建築空間成語',
    subtitle: '出處典故、前後呼應、褒貶色彩辨析與空間意象成語',
    conceptType: 'comparative-matrix',
    icon: '📚',
    diagramTitle: '常考成語語義感情色彩（褒義/中性/貶義）與典故情境對比光譜',
    diagramDescription: '展示「美輪美奐」（專指建築宏偉）、「棟樑之材」、「鉤心鬥角」（原指阿房宮建築結構精巧）之詞性與古今演變。',
    formulaBanner: '成語應用: 褒義詞 (如: 碩德名望) ； 貶義詞 (如: 始作俑者) ； 建築專用 (如: 美輪美奐)',
    visualHighlights: [
      { label: '美輪美奐', desc: '《禮記》「輪焉奐焉」，專門形容「房屋建築高大華美」，不可用於形容衣服或文章', badge: '建築專用' },
      { label: '鉤心鬥角', desc: '杜牧《阿房宮賦》形容「宮室建築結構交錯精巧」，後演變為貶義指各用心機', badge: '古今詞義' },
      { label: '移樽就教', desc: '「樽」為酒杯，端著酒杯向人請教，比喻「親自登門謙虛向人請教」', badge: '社交敬語' },
    ],
    keyTakeaways: [
      '「美輪美奐」嚴格限定只能用於形容「建築物、居室之高大華麗」，切忌誤用於形容服裝珠寶。',
      '「文不加點」之「點」為塗改之意，形容「文思敏捷，寫作一氣呵成不須修改」，非指不加標點符號。',
      '成語辨析首重感情色彩（褒義詞、貶義詞、中性詞），填空題需結合上下文語境感情基調判定。',
    ],
  },
  'chinese/grammar-rhetoric': {
    topicSlug: 'grammar-rhetoric',
    title: '修辭技巧、文法句型與倒裝語序',
    subtitle: '借代、互文、轉品、映襯、排比與文言文倒裝句結構',
    conceptType: 'flowchart-logic',
    icon: '🔍',
    diagramTitle: '修辭手法空間意象映射（借代象徵/互文足義/轉品詞性變更）與句型倒裝圖解',
    diagramDescription: '展示借代（如布衣代百姓、杜康代酒）、互文（如「主人下馬客上船」互相補充）、及賓語前置倒裝句。',
    formulaBanner: '常見修辭: 借代 (以特徵代全體) ； 互文 (上文見下文，互相呼應) ； 轉品 (詞性轉換)',
    visualHighlights: [
      { label: '借代 (Metonymy)', desc: '不直接說出本名，借用其特徵或相關物代替（如「帆」代船、「白丁」代無功名者）', badge: '特徵代稱' },
      { label: '互文 (Intersynonym)', desc: '前後兩句在意義上互相補充融合，如「煙籠寒水月籠沙」（煙月籠罩著寒水沙灘）', badge: '互為補充' },
      { label: '賓語前置倒裝', desc: '文言文中否定句或疑問句代詞作賓語時前置，如「何陋之有」（有何陋之倒裝）', badge: '語序倒裝' },
    ],
    keyTakeaways: [
      '「互文」讀法：不可將上下句割裂解釋，必須合在一起讀（如「將軍百戰死，壯士十年歸」）。',
      '轉品修辭：「火」紅的太陽（名詞作副詞）、「春風又『綠』江南岸」（形容詞作動詞，具強烈生機感）。',
      '文言文倒裝句常以「之」、「是」作為賓語提前之標誌，如「唯命是從」（從命）、「唯利是圖」。',
    ],
  },
  'chinese/classical-literature': {
    topicSlug: 'classical-literature',
    title: '古典文學流變、唐宋八大家與散文發展',
    subtitle: '先秦諸子、漢賦、六朝駢文、唐宋古文運動、明清小說與韻文體制',
    conceptType: 'comparative-matrix',
    icon: '📜',
    diagramTitle: '中國歷代散文與韻文演進時間軸（楚辭→漢賦→唐詩→宋詞→元曲）矩陣圖',
    diagramDescription: '展示唐宋八大家（韓柳歐三蘇曾王）古文運動反對六朝華靡駢文，主張「文以載道」與明清四大奇書。',
    formulaBanner: '古文運動宗師: 韓愈 (文起八代之衰) 、 柳宗元 ； 唐宋八大家: 韓、柳、歐、蘇洵、蘇軾、蘇轍、曾、王',
    visualHighlights: [
      { label: '駢體文 (Parallel Prose)', desc: '講求駢四儷六、對仗工整、音律諧協、辭藻華麗、多用典故（如《滕王閣序》）', badge: '六朝華麗' },
      { label: '古文運動 (Guwen Movement)', desc: '韓愈、柳宗元提倡回復先秦兩漢質樸自由之散文，強調「文道合一」', badge: '文以載道' },
      { label: '韻文體制演變', desc: '詩（字數固定押韻平仄嚴格） → 詞（長短句依詞牌填詞） → 曲（可加襯字更趨通俗）', badge: '格律解放' },
    ],
    keyTakeaways: [
      '韓愈與柳宗元並稱「韓柳」，蘇軾稱韓愈「文起八代之衰，道濟天下之溺」。',
      '唐宋八大家包含唐代 2 位（韓愈、柳宗元）與宋代 6 位（歐陽脩、蘇洵、蘇軾、蘇轍、曾鞏、王安石）。',
      '賦的流變：古賦（漢大賦鋪陳宏麗） → 俳賦（六朝駢化） → 文賦（宋代散文化如蘇軾《赤壁賦》）。',
    ],
  },
  'chinese/modern-prose-literacy': {
    topicSlug: 'modern-prose-literacy',
    title: '現代散文、台灣文學與非連續性文本閱讀',
    subtitle: '五四新文學、台灣鄉土文學論戰、現代詩派與圖表/資訊跨界文本素養',
    conceptType: 'flowchart-logic',
    icon: '📰',
    diagramTitle: '非連續性文本（資訊圖表/契約規章/論述評論）三步快速閱讀破題流',
    diagramDescription: '展示「1. 抓取標題與圖表核心軸線 → 2. 鎖定極值/拐點與對比數據 → 3. 比對選項文意邏輯」之現代閱讀策略。',
    formulaBanner: '閱讀理解三層次: 提取訊息 (What) → 統整解釋 (Why) → 反思評鑑 (How)',
    visualHighlights: [
      { label: '台灣鄉土文學', desc: '賴和（台灣新文學之父）、楊逵（壓不扁的玫瑰）、黃春明、洪醒夫（關懷底層社會與土地情感）', badge: '土地關懷' },
      { label: '現代詩三要素', desc: '意象 (Image, 以具體寫抽象)、音樂性 (節奏韻律)、精煉語言 (跨行與跳躍思考)', badge: '空間留白' },
      { label: '圖表多文本對讀', desc: '將文字論述與柱狀圖/折線圖交叉比對，排除「過度推論」與「無中生有」干擾項', badge: '跨域素養' },
    ],
    keyTakeaways: [
      '非連續性文本題型：先看題幹問什麼，再回圖表與文章中定位關鍵數據，切忌未看題目通篇盲讀。',
      '現代詩解題核心：抓住詩中的「核心意象 (Central Image)」即可掌握整首詩的情感核心。',
      '作者觀點題：注意文中轉折詞（然而、但是、其實），真正的作者核心論點往往落在轉折詞之後。',
    ],
  },
  'chinese/practical-writing': {
    topicSlug: 'practical-writing',
    title: '公文程式、應用文稱謂與柬帖題辭規範',
    subtitle: '公文三段式（主旨/說明/辦法）、書信提稱語/啟封詞與婚喪喜慶題辭',
    conceptType: 'comparative-matrix',
    icon: '✉️',
    diagramTitle: '書信稱謂信封格式（發信人自稱、對方尊稱、信封收信人啟封詞）對照表',
    diagramDescription: '展示信封啟封詞（給長輩用「安啟/福啟」、給平輩用「大啟/台啟」、絕對「不可用敬啟」因敬啟是請對方恭敬開啟）。',
    formulaBanner: '公文三段架構: 主旨 (一句話說明目的) ； 說明 (背景依據) ； 辦法 (具體執行作為)',
    visualHighlights: [
      { label: '信封啟封詞', desc: '長輩：安啟、福啟 ； 平輩：大啟、台啟 ； 晚輩：啟、收 ； 嚴禁對任何人使用「敬啟」', badge: '高頻易錯' },
      { label: '提稱語 (信內)', desc: '父母：膝下、膝前 ； 師長：函丈、壇席 ； 平輩：足下、左右 ； 晚輩：如晤、知悉', badge: '信件內文' },
      { label: '常見題辭', desc: '新居落成：美輪美奐、喬遷之喜 ； 祝壽：齒德俱尊、松柏長青 ； 哀輓：駕鶴西歸、福壽全歸', badge: '應對進退' },
    ],
    keyTakeaways: [
      '信封上的「啟封詞」是發信人請收信人拆信的客氣話，若寫「敬啟」等於傲慢命令長輩「恭敬地拆開」，大不敬。',
      '公文「函」的行文方向：上行文（向長官用「陳」、「請 鑒核」）、平行文（同級機關用「洽」、「請 查照」）、下行文（對屬下用「督導」、「請 照辦」）。',
      '對他人稱自己父親用「家父/家嚴」，稱自己母親用「家母/家慈」；稱對方父母用「令尊/令堂」。',
    ],
  },

  // ==========================================
  // 6. ENGLISH (12 Topics)
  // ==========================================
  'english/vocabulary-phrases': {
    topicSlug: 'vocabulary-phrases',
    title: '核心高頻單字、字根字首與動詞片語搭疊',
    subtitle: 'Prefix (字首)、Root (字根)、Suffix (字尾) 與統測高頻片語',
    conceptType: 'flowchart-logic',
    icon: '🔤',
    diagramTitle: '字根字首構詞網絡（struct/construct/destruct/instruct）與片語語意衍生圖',
    diagramDescription: '展示 struct (建造) 衍生 construct (建造), destruct (破壞), instruct (指導), structure (結構) 記憶網絡。',
    formulaBanner: '字根構詞: Prefix (方向/否定) + Root (核心意義) + Suffix (詞性轉換)',
    visualHighlights: [
      { label: 'struct- (建造)', desc: 'structure (結構), construction (施工), infrastructure (基礎設施)', badge: '建築核心根' },
      { label: 'form- (形狀)', desc: 'transform (轉型), conform (符合規範), deformation (變形)', badge: '形狀字根' },
      { label: '高頻動詞片語', desc: 'take place (發生), carry out (執行), put up with (容忍), account for (佔比例/解釋)', badge: '片語必背' },
    ],
    keyTakeaways: [
      '掌握一個字根（如 spect 看、tract 拉、port 搬運），可一次串記 10~20 個高階單字。',
      '動詞片語需注意介系詞搭配：be responsible for (對...負責)、be composed of (由...組成)。',
      '字尾決定詞性：-tion/-ment (名詞)、-ate/-ize (動詞)、-able/-ive (形容詞)、-ly (副詞)。',
    ],
  },
  'english/grammar-patterns': {
    topicSlug: 'grammar-patterns',
    title: '時態語態、主被動關係與假設語氣',
    subtitle: '現在完成式、過去完成式、被動語態 (be + p.p.) 與與現在/過去事實相反假設',
    conceptType: 'flowchart-logic',
    icon: '⏳',
    diagramTitle: '12 大時態時間軸座標圖與與過去事實相反 (Had + p.p., Would have + p.p.) 條件句結構',
    diagramDescription: '展示過去、現在、未來時間點，完成式「在此時間之前已完成」，及假設語氣動詞退一步時態法則。',
    formulaBanner: '與現在事實相反: If S + 過去式, S + would/could + VR ； 與過去事實相反: If S + had p.p., S + would have p.p.',
    visualHighlights: [
      { label: '現在完成式 (Have/Has + p.p.)', desc: '從過去持續到現在，或過去發生的動作對現在仍有影響（常搭配 since, for）', badge: '連結古今' },
      { label: '被動語態 (be + p.p.)', desc: '受詞移為句首主詞，強調動作接受者（如 The bridge was constructed in 1999.）', badge: '客觀工程' },
      { label: '假設語氣退時態', desc: '表示非真實條件，動詞時態一律向過去退一格（is/am/are → were；do/does → did；did → had done）', badge: '虛擬情境' },
    ],
    keyTakeaways: [
      '工程與科學文獻極大量使用「被動語態」，以呈現客觀事實（避免過多主觀第一人稱 I/We）。',
      'since 後面接「過去時間點」，主要子句一律使用「現在完成式 (has/have + p.p.)」。',
      '與過去事實相反假設：If he had studied hard, he would have passed the exam. (代表他過去沒用功，也沒考過)。',
    ],
  },
  'english/conversation-daily-use': {
    topicSlug: 'conversation-daily-use',
    title: '生活情境對話、校園溝通與商務應答',
    subtitle: '問路、就醫、購物、機場、電話溝通與禮貌詢問拒絕句型',
    conceptType: 'flowchart-logic',
    icon: '💬',
    diagramTitle: '日常情境對話決策樹（問句功能判定 → 語氣語調 → 正向/反向禮貌回應）',
    diagramDescription: '展示 Would you mind...?（介意嗎？不介意回答 Not at all）、How come...?（為何）、I couldn\'t agree more（完全贊同）。',
    formulaBanner: '問句辨析: Would you mind...? (回答 No/Not at all 表示同意) ； I couldn\'t agree more = 完全贊成',
    visualHighlights: [
      { label: 'Would you mind...?', desc: '回答「No, not at all.」代表「我不介意，你可以做」；回答「Yes.」代表「我介意，請不要做」', badge: '反向作答' },
      { label: 'I couldn\'t agree more.', desc: '雙重否定表強烈肯定，意思是「我完全同意你的觀點」，絕非不同意', badge: '強烈贊同' },
      { label: 'How come...?', desc: '等於 Why，後面直接接「肯定句語序」（How come you are late?）', badge: '口語疑問' },
    ],
    keyTakeaways: [
      '對話解題首重「上下文語境 (Context)」與「禮貌原則 (Politeness)」，避免挑選過於粗魯生硬的選項。',
      '祈使句附加問句：Let\'s go, shall we? ； Clean your room, will you?',
      '表達同感：肯定句用 So + be/助動詞 + S (So do I)；否定句用 Neither/Nor + be/助動詞 + S (Neither do I)。',
    ],
  },
  'english/reading-comprehension': {
    topicSlug: 'reading-comprehension',
    title: '長篇閱讀理解、主旨判斷與細節推論',
    subtitle: 'Skimming (略讀抓主旨)、Scanning (掃讀找細節) 與 Contextual Inference',
    conceptType: 'flowchart-logic',
    icon: '📖',
    diagramTitle: '英文長篇閱讀快速破題五步法（首尾段首尾句 → 關鍵字定位 → 邏輯因果反推）',
    diagramDescription: '展示主題句 (Topic Sentence) 位於段落開頭或結尾，轉折詞 (However, Nevertheless) 指引文章核心觀點。',
    formulaBanner: '閱讀核心策略: Skimming (首尾段看大意) → Scanning (專有名詞數字定位) → Inference (排除過度推論)',
    visualHighlights: [
      { label: '主旨題 (Main Idea)', desc: '重點鎖定第一段第一句（背景引出）與最後一段最後一句（結論重申）', badge: '首尾呼應' },
      { label: '細節定位 (Scanning)', desc: '在文章中快速尋找人名、年份數字、大寫專有名詞，精確鎖定答案句', badge: '關鍵字雷達' },
      { label: '推論題 (Inference)', desc: '答案必須在文中有間接依據，選項包含「always, never, only」等極端詞通常為錯誤選項', badge: '避免絕對' },
    ],
    keyTakeaways: [
      '閱讀測驗先快速讀過題幹題目（抓住問什麼），再帶著問題回到文章中尋找對應段落，效率最高。',
      '文章中出現 However, In contrast, On the other hand 時，其後方句子必定為全段最重要核心論點。',
      '代名詞指涉題（What does "it" refer to?）：往該代名詞「前一句」尋找單複數與性別一致之名詞。',
    ],
  },
  'english/vocabulary-professional': {
    topicSlug: 'vocabulary-professional',
    title: '建築與土木工程專業英文詞彙庫',
    subtitle: 'Architecture, Construction, Structural, Materials & Sustainable Terms',
    conceptType: 'comparative-matrix',
    icon: '🏛️',
    diagramTitle: '建築工程全生命週期（Design → Material → Construction → Operation）專業詞彙網絡',
    diagramDescription: '展示 beam (梁), column (柱), foundation (基礎), reinforcement (鋼筋), sustainable (永續), blueprint (藍圖) 跨領域術語。',
    formulaBanner: '工程術語: Foundation (基礎) / Load-bearing (承重) / Reinforced Concrete (鋼筋混凝土) / Ventilation (通風)',
    visualHighlights: [
      { label: '結構構件', desc: 'beam (橫梁), column (柱), slab (樓板), truss (桁架), cantilever (懸臂)', badge: '結構英文' },
      { label: '材料性質', desc: 'durability (耐久性), tensile strength (抗拉強度), insulation (隔熱/隔音)', badge: '材料力學' },
      { label: '永續綠建築', desc: 'renewable (可再生), energy efficiency (能源效率), carbon neutral (碳中和)', badge: '綠建築' },
    ],
    keyTakeaways: [
      '統測非考科群常在克漏字與閱讀題中結合跨領域工程常識文章，掌握專業字彙能快速理解文章脈絡。',
      '注意一字多義：beam（橫梁 / 光束）、concrete（混凝土 / 具體的）、crane（起重吊車 / 白鶴）。',
      '國際營建常見縮寫：RC (Reinforced Concrete), BIM (Building Information Modeling), LEED (綠建築認證)。',
    ],
  },
  'english/grammar-clauses': {
    topicSlug: 'grammar-clauses',
    title: '複合句型、關係代名詞與三大子句結構',
    subtitle: '名詞子句 (that/wh-)、副詞子句 (although/because/if) 與形容詞子句 (who/which/that)',
    conceptType: 'flowchart-logic',
    icon: '🔗',
    diagramTitle: '三大子句語法樹狀圖與關係代名詞 (who/which/that/whose/where) 先行詞指引圖解',
    diagramDescription: '展示主句與從屬子句關係，形容詞子句修飾先行詞，關係副詞 where/when = 介系詞 + which。',
    formulaBanner: '關係詞代換: where = in/at which ； when = on/in which ； whose + N (所有格先行詞)',
    visualHighlights: [
      { label: '限定 vs 非限定用法', desc: '非限定用法（有逗號）提供補充說明，逗號後面「絕對不能使用 that」', badge: '逗號後無 that' },
      { label: '關係代名詞當主詞', desc: 'The architect who designed this building is famous. (who 在子句中作主詞，不可省略)', badge: '作主詞' },
      { label: '關係代名詞當受詞', desc: 'The blueprint (which) he drew was approved. (which 作受詞時可以省略)', badge: '作受詞可省' },
    ],
    keyTakeaways: [
      'that 萬能但有兩大禁忌：1. 逗號後面不能用 that；2. 介系詞後面不能用 that（如 in which 可，in that 不行）。',
      '名詞子句由 that, whether/if, wh- 疑問詞引導，在句中可充當主詞、受詞或同位語。',
      '分詞構句簡化：當兩子句主詞相同時，可省略連接詞與主詞，主動動詞改 V-ing，被動動詞改 p.p.。',
    ],
  },
  'english/reading-infographics': {
    topicSlug: 'reading-infographics',
    title: '圖表資訊解讀、長條圖/圓餅圖與數據比對',
    subtitle: 'Reading Charts, Graphs, Tables, Floor Plans & Environmental Data',
    conceptType: 'comparative-matrix',
    icon: '📊',
    diagramTitle: '英文長條圖、折線圖與平面圖快速數據比對解題指南',
    diagramDescription: '展示 rise, drop, double, account for, peak at 等趨勢描述動詞與圖表最高/最低極值對照。',
    formulaBanner: '趨勢動詞: increase / decrease / peak at (達到頂峰) / remain steady (保持穩定) / account for (佔比)',
    visualHighlights: [
      { label: '佔比描述', desc: 'account for 40% of the total, make up the majority of...', badge: '比例表達' },
      { label: '趨勢變化', desc: 'dramatic increase (急劇上升), sharp decline (驟降), fluctuate (波動)', badge: '趨勢副詞' },
      { label: '圖表極值判定', desc: 'highest / lowest / second largest / exceeded (超越) 關鍵詞比對', badge: '數據極值' },
    ],
    keyTakeaways: [
      '圖表題務必先看圖表「標題 (Title)」與「橫縱軸單位 (X/Y axis labels)」，避免看錯數據級距。',
      '比對選項時注意時間區間（如 from 2020 to 2025），切勿將某一年的數值誤當成全期趨勢。',
      '建築空間平面圖題：注意方向標示（North）、房間編號與無障礙坡道（Ramp）等圖例文字說明。',
    ],
  },
  'english/cloze-passage-structure': {
    topicSlug: 'cloze-passage-structure',
    title: '綜合填空 (克漏字) 語意轉折與上下文邏輯',
    subtitle: '轉折連接詞 (However, Therefore, In addition)、代名詞指涉與文意推敲',
    conceptType: 'flowchart-logic',
    icon: '🧩',
    diagramTitle: '克漏字空格前後詞性判定（名/動/形/副）與上下文邏輯轉折關聯樹',
    diagramDescription: '展示空格前看搭配、空格後看受詞，透過轉折詞 (However)、因果詞 (As a result) 判定填空語義正負向。',
    formulaBanner: '轉折詞庫: 因果 (Therefore, Thus) ； 轉折 (However, Yet) ； 遞進 (Furthermore, In addition)',
    visualHighlights: [
      { label: '詞性預判法', desc: '空格在冠詞 (the/a) 與名詞之間 → 必填形容詞；空格在主詞與受詞之間 → 必填動詞', badge: '結構語法' },
      { label: '語意正負符號', desc: '若前句為正面評價 (+) 且有 However，空格後句必然接負面評價 (-) 或問題', badge: '正負邏輯' },
      { label: '固定搭配片語', desc: 'pay attention to (注意), in terms of (就...而言), in contrast to (與...相反)', badge: '片語慣用' },
    ],
    keyTakeaways: [
      '克漏字切忌「看一個空做一個空」，必須至少讀完空格所在的「整句話（前後句）」，掌握完整邏輯。',
      '四大轉折邏輯分類：1. 因果 (Because, As a result)；2. 轉折 (Although, However)；3. 補充 (Moreover)；4. 舉例 (For instance)。',
      '介系詞提示：空格後若有 to, of, for, with 等介系詞，通常是前面動詞或形容詞的固定搭配。',
    ],
  },
  'english/grammar-mastery': {
    topicSlug: 'grammar-mastery',
    title: '分詞構句、倒裝句型與高級文法精粹',
    subtitle: 'V-ing (主動) vs p.p. (被動) 分詞簡化、否定副詞置句首倒裝與強調句',
    conceptType: 'flowchart-logic',
    icon: '⚡',
    diagramTitle: '分詞構句簡化流程圖與否定副詞 (Not only, Seldom, Never) 置句首倒裝結構',
    diagramDescription: '展示 Seeing the danger, he ran away (主動 Seeing)；Built in 1930, the house is old (被動 Built)；Not only did he pass...',
    formulaBanner: '分詞構句: 主動用 V-ing, 被動用 p.p. ； 否定倒裝: 否定副詞 + 助動詞/be + 主詞 + 原形動詞',
    visualHighlights: [
      { label: '主動分詞 (V-ing)', desc: '主詞發出動作：Walking along the street, I met an old friend.', badge: '主動進行' },
      { label: '被動分詞 (p.p.)', desc: '主詞接受動作：Designed by a master, the museum attracts thousands.', badge: '被動狀態' },
      { label: '否定置首倒裝', desc: 'Seldom have I seen such a masterpiece. (否定副詞置首，助動詞 have 提前到主詞前)', badge: '高級句型' },
    ],
    keyTakeaways: [
      '分詞構句解題黃金法則：看主句的「主詞」是這件事的「主動執行者」還是「被動承受者」。',
      '常見否定副詞倒裝詞：Never, Seldom, Rarely, Hardly, Scarcely, Little, Not only, Under no circumstances。',
      '強調句型架構：It is/was + [被強調的部分] + that/who + [句子其餘部分]。',
    ],
  },
  'english/workplace-communication': {
    topicSlug: 'workplace-communication',
    title: '職場商務通訊、電子郵件格式與會議備忘錄',
    subtitle: 'Formal Email structure, Memo, Meeting Minutes & Professional Inquiries',
    conceptType: 'flowchart-logic',
    icon: '📧',
    diagramTitle: '標準職場商務電子郵件結構（Subject Line → Salutation → Opening → Body → CTA → Sign-off）',
    diagramDescription: '展示主旨明確、開場問候 (I am writing to inquire about...)、核心事項、下一步行動 (CTA) 與結尾 (Sincerely)。',
    formulaBanner: '商務電郵句型: I am writing to confirm... / Please find attached the report / Look forward to hearing from you',
    visualHighlights: [
      { label: '開場問候 (Salutation)', desc: '已知姓名：Dear Mr. Smith / Dear Ms. Davis ； 未知收信人：To Whom It May Concern', badge: '正式尊稱' },
      { label: '附件告知', desc: 'Please find attached the structural analysis report for your review.', badge: '附件附檔' },
      { label: '行動召喚 (Call to Action)', desc: 'Please let me know your availability by Friday for the site inspection.', badge: '明確回覆期限' },
    ],
    keyTakeaways: [
      '商務電郵主旨 (Subject) 必須清晰具體（如 Meeting Request: Structural Inspection on Oct 12），避免模糊只寫 Hello。',
      '正式書信結尾：Sincerely yours (最正式)、Best regards (商務常用)；口語 Casual 信件可用 Cheers, Best。',
      '職場備忘錄 (Memo) 格式固定包含四要素：To (收件人), From (發件人), Date (日期), Subject (事由)。',
    ],
  },
  'english/reading-advanced': {
    topicSlug: 'reading-advanced',
    title: '跨學科長篇文獻、論證結構與作者語氣判定',
    subtitle: 'Academic discourse, Rhetorical stance, Tone analysis (Objective/Critical/Optimistic)',
    conceptType: 'flowchart-logic',
    icon: '🧠',
    diagramTitle: '學術論述三層論證結構（Thesis Statement → Evidence & Counter-argument → Synthesis）',
    diagramDescription: '展示主張 (Claim)、論據 (Evidence)、反方論點 (Counter-argument) 與結論，及作者語調判定（客觀/批判/樂觀）。',
    formulaBanner: '語氣詞彙: Objective (客觀) / Skeptical (懷疑) / Optimistic (樂觀) / Critical (批判) / Neutral (中立)',
    visualHighlights: [
      { label: '論證主張 (Claim)', desc: '通常位於導論段末尾，宣告全篇核心立場（如 Green building saves 30% energy）', badge: '核心論點' },
      { label: '反駁讓步 (Concession)', desc: 'Although initial costs are higher, the long-term benefits outweigh the expenses.', badge: '讓步反駁' },
      { label: '作者態度 (Tone)', desc: '從形容詞與副詞用字推斷作者情感（客觀客觀 objective、批判 critical、支持 supportive）', badge: '語調分析' },
    ],
    keyTakeaways: [
      '進階學術閱讀：注意作者在提出反方意見後，如何用 However 或 But 進行有力反駁，那才是真正的結論。',
      '語氣題判斷：科普文章通常為「客觀中立 (Objective/Informative)」；社論批評文章通常為「批判性 (Critical)」。',
      '遇到生僻專有名詞不必慌張，作者通常會在破折號 (—)、括號或 comma 後方給予同位語定義解釋。',
    ],
  },
  'english/translation-writing': {
    topicSlug: 'translation-writing',
    title: '中翻英結構轉換、句型整合與段落寫作',
    subtitle: 'Chinese to English Translation, Sentence Combining & Coherence',
    conceptType: 'flowchart-logic',
    icon: '✍️',
    diagramTitle: '中翻英五步轉換流程（抓主詞動詞 → 確定時態 → 調配修飾子句 → 檢視連接詞 → 校對主謂一致）',
    diagramDescription: '展示中文意合（無明顯主詞）轉為英文形合（必須有主詞動詞與連接詞），避免流水句 (Run-on sentences)。',
    formulaBanner: '翻譯五步法: 1. 抓主幹 (S+V) → 2. 定時態 (Past/Present) → 3. 補修飾 (Clauses) → 4. 順語序 → 5. 檢核一致',
    visualHighlights: [
      { label: '抓出核心主謂', desc: '中文「這棟建築物是由著名建築師設計的」→ 主詞 The building, 動詞 was designed by...', badge: '核心主幹' },
      { label: '避免流水句 (Run-on)', desc: '兩個完整子句不可直接用逗號連接，必須加上對等連接詞 (and/but) 或改為從屬子句', badge: '語法結構' },
      { label: '主謂一致 (Agreement)', desc: '單數主詞配單數動詞（The number of students IS increasing）；小心介系詞片語干擾', badge: '單複數檢查' },
    ],
    keyTakeaways: [
      '中文習慣無主詞（如「下雨了」），翻成英文必須補出虛主詞「It is raining.」。',
      '「A number of + 複數名詞」意思是許多，動詞用「複數」；「The number of + 複數名詞」意思是數目，動詞用「單數」。',
      '翻譯完成後三秒速查清單：1. 主謂單複數；2. 動詞時態；3. 名詞可數單數是否少加 a/the；4. 拼字正確。',
    ],
  },

  // ==========================================
  // 7. MATH C (6 Topics)
  // ==========================================
  'math-c/trigonometry': {
    topicSlug: 'trigonometry',
    title: '三角函數定義、廣義角化簡與正餘弦定理',
    subtitle: '銳角/廣義角三角函數、同角關係、正弦定理、餘弦定理與三角形面積',
    conceptType: 'survey-geometry',
    icon: '📐',
    diagramTitle: '單位圓廣義角坐標定義 (x=cosθ, y=sinθ) 與正餘弦定理斜三角形幾何圖',
    diagramDescription: '展示四象限正負號 (All-Sin-Tan-Cos)，正弦定理 a/sinA = b/sinB = c/sinC = 2R，餘弦定理 c² = a² + b² - 2ab·cosC。',
    formulaBanner: '正弦定理: a/sinA = b/sinB = c/sinC = 2R ； 餘弦定理: c² = a² + b² - 2ab·cosC ； 面積 Δ = 1/2·ab·sinC',
    visualHighlights: [
      { label: '四象限正負 (ASTC)', desc: '第一象限全正 (All)、第二象限 sin正、第三象限 tan正、第四象限 cos正', badge: '象限正負' },
      { label: '餘弦定理 (Cosine Rule)', desc: '已知兩邊及其夾角 (SAS) 或已知三邊 (SSS)，求第三邊或求角度之萬能定理', badge: '解斜三角形' },
      { label: '海龍公式 (Heron)', desc: '已知三角形三邊長 a, b, c，設 s = (a+b+c)/2，面積 Δ = √[s(s-a)(s-b)(s-c)]', badge: '三邊求面積' },
    ],
    keyTakeaways: [
      '測量與力學計算基石：正弦定理用於「已知一邊與兩角 (AAS/ASA)」；餘弦定理用於「已知兩邊及夾角 (SAS) 或三邊 (SSS)」。',
      '特殊角數值牢記：sin30° = 1/2, cos30° = √3/2, tan30° = 1/√3；sin45° = √2/2, cos45° = √2/2, tan45° = 1。',
      '平方關係恆等式：sin²θ + cos²θ = 1 ； 1 + tan²θ = sec²θ ； 1 + cot²θ = csc²θ。',
    ],
  },
  'math-c/vectors': {
    topicSlug: 'vectors',
    title: '平面向量內積、正射影與空間幾何向量',
    subtitle: '向量加減、內積 u·v = |u||v|cosθ、正射影向量與柯西不等式',
    conceptType: 'equilibrium-vector',
    icon: '🧭',
    diagramTitle: '向量內積幾何意義（投影長度乘積）與向量 a 在向量 b 上之正射影向量圖解',
    diagramDescription: '展示內積 u·v = u1·v1 + u2·v2，正射影向量公式 proj_b(a) = [(a·b) / |b|²] · b，垂直則內積為 0。',
    formulaBanner: '內積: u·v = |u||v|cosθ = u₁v₁ + u₂v₂ ； 正射影: proj_b(a) = [(a·b) / |b|²] · b ； 垂直條件: a·b = 0',
    visualHighlights: [
      { label: '正射影長度', desc: '純量長度 |proj| = |a·b| / |b|，代表向量 a 投影在 b 方向上的影子長度', badge: '純量投影' },
      { label: '正射影向量', desc: '具備方向之向量，公式為 [(a·b) / |b|²] · b（方向沿著向量 b）', badge: '向量投影' },
      { label: '柯西不等式 (Cauchy)', desc: '(a₁² + a₂²)(b₁² + b₂²) ≥ (a₁b₁ + a₂b₂)²，等號成立於 a₁/b₁ = a₂/b₂', badge: '極值利器' },
    ],
    keyTakeaways: [
      '兩向量垂直之充分必要條件：內積等於零 (a · b = 0)；兩向量平行之條件：分量成比例 (a1/b1 = a2/b2)。',
      '力學中力作功 W = F · d（力向量與位移向量之內積），若力垂直於位移方向則作功為 0。',
      '二階行列式計算二維向量所張開之平行四邊形面積：面積 A = |det([a, b])| = |a1·b2 - a2·b1|。',
    ],
  },
  'math-c/algebra': {
    topicSlug: 'algebra',
    title: '多項式運算、餘式定理與指數對數方程式',
    subtitle: '除法原理 f(x)=g(x)q(x)+r(x)、餘式定理 f(k)、指數律與對數換底公式',
    conceptType: 'flowchart-logic',
    icon: '➗',
    diagramTitle: '指數函數 y = a^x vs 對數函數 y = log_a(x) 對稱於 y = x 鏡射圖譜',
    diagramDescription: '展示除法原理餘式次數小於除式，餘式定理代入求餘數，對數律 log(xy) = logx + logy 與換底公式 log_a(b) = logb/loga。',
    formulaBanner: '餘式定理: 多項式 f(x) 除以 (x - c) 之餘式為 f(c) ； 對數換底公式: log_a(b) = log_c(b) / log_c(a)',
    visualHighlights: [
      { label: '餘式定理 (Remainder)', desc: '欲求 f(x) 除以 (x - a) 的餘式，直接計算 f(a) 數值即可，免做長除法', badge: '秒殺餘式' },
      { label: '因式定理 (Factor)', desc: '若 f(a) = 0，則 (x - a) 必為多項式 f(x) 的因式（可整除）', badge: '因式分解' },
      { label: '對數運算律', desc: 'log(A·B) = logA + logB ； log(A/B) = logA - logB ； log(A^k) = k·logA', badge: '對數拆解' },
    ],
    keyTakeaways: [
      '對數真數必須大於零 (x > 0)，底數必須大於零且不等於 1 (a > 0 且 a ≠ 1)，解題後務必代回檢驗真數條件。',
      '二項式定理：(a + b)ⁿ = Σ C(n, k) · aⁿ⁻ᵏ · bᵏ，用於快速求特定項係數。',
      '算幾不等式：若 a, b > 0，則 (a + b) / 2 ≥ √(ab)，當且僅當 a = b 時等號成立（常用於求極值）。',
    ],
  },
  'math-c/geometry': {
    topicSlug: 'geometry',
    title: '平面解析幾何：直線方程式、圓與二次圓錐曲線',
    subtitle: '點到直線距離 d = |ax₀+by₀+c|/√(a²+b²)、圓與直線相交判別與拋物/橢圓/雙曲線',
    conceptType: 'survey-geometry',
    icon: '⭕',
    diagramTitle: '點到直線垂直距離幾何圖與圓方程式 (x-h)² + (y-k)² = r² 相切相割相離判別圖解',
    diagramDescription: '展示直線斜率 m = -a/b，點到直線距離公式，圓心至直線距離 d 與半徑 r 之關係（d < r 相交兩點、d = r 相切、d > r 相離）。',
    formulaBanner: '點到直線距離: d = |a·x₀ + b·y₀ + c| / √(a² + b²) ； 圓心到直線距 d = r (相切條件)',
    visualHighlights: [
      { label: '點線距離公式', desc: '坐標 (x₀, y₀) 代入直線一般式取絕對值，除以係數平方和開根號 √(a²+b²)', badge: '幾何距離' },
      { label: '直線與圓相切 (Tangent)', desc: '圓心到切線之垂直距離等於半徑 (d = r)，判別式 Δ = 0', badge: '相切判別' },
      { label: '橢圓標準式', desc: 'x²/a² + y²/b² = 1 (a>b)，焦點坐標 c² = a² - b²，兩焦點距離和為定值 2a', badge: '圓錐曲線' },
    ],
    keyTakeaways: [
      '兩平行直線 L1: ax+by+c1=0 與 L2: ax+by+c2=0 之間距離：d = |c1 - c2| / √(a² + b²)。',
      '兩互相垂直直線斜率相乘必為 -1 (m1 · m2 = -1)；若直線為 ax+by+c=0，其垂直線可設為 bx-ay+k=0。',
      '拋物線標準式 y² = 4cx，焦點在 (c, 0)，準線方程式為 x = -c，任一點至焦點距離等於至準線距離。',
    ],
  },
  'math-c/probability': {
    topicSlug: 'probability',
    title: '排列組合、古典機率與二項式機率分佈',
    subtitle: '直線排列 P(n, r)、組合 C(n, r)、條件機率 P(A|B) 與數學期望值 E(X)',
    conceptType: 'flowchart-logic',
    icon: '🎲',
    diagramTitle: '排列 (順序有關 P) vs 組合 (順序無關 C) 分流決策樹與貝氏定理樹狀圖',
    diagramDescription: '展示排列 P(n,r) = n!/(n-r)!，組合 C(n,r) = n!/[r!(n-r)!]，條件機率 P(A|B) = P(A∩B)/P(B) 與期望值 E = Σ x_i·p_i。',
    formulaBanner: '排列 P(n, r) = n! / (n - r)! ； 組合 C(n, r) = n! / [r!(n - r)!] ； 期望值 E(X) = Σ (x_i · P_i)',
    visualHighlights: [
      { label: '排列 P (Permutation)', desc: '「取出來且要排順序」（如排成一列、選出幹部社長/副社長）', badge: '順序有關' },
      { label: '組合 C (Combination)', desc: '「只取出來不排順序」（如從 10 人選 3 人出差、挑選樣本）', badge: '順序無關' },
      { label: '期望值 (Expected Value)', desc: '各事件可能數值與其發生機率乘積之總和，代表長期平均報酬', badge: '長期平均' },
    ],
    keyTakeaways: [
      '重複組合 H(n, r) = C(n + r - 1, r)：將 r 個相同物品分給 n 個不同人的方法數。',
      '互斥事件 (Mutually Exclusive)：A 與 B 不能同時發生 (A∩B = ∅)，則 P(A∪B) = P(A) + P(B)。',
      '獨立事件 (Independent)：A 發生不影響 B 發生，則 P(A∩B) = P(A) · P(B)。',
    ],
  },
  'math-c/calculus': {
    topicSlug: 'calculus',
    title: '極限導數、多項式微積分與定積分面積',
    subtitle: '導數斜率 f\'(x) = lim Δy/Δx、極值判定 (f\'=0)、不定積分與微積分基本定理',
    conceptType: 'flowchart-logic',
    icon: '📈',
    diagramTitle: '函數曲線切線斜率（微分）與曲線下方黎曼和曲邊梯形面積（定積分）幾何圖解',
    diagramDescription: '展示多項式微分公式 (xⁿ)\' = n·xⁿ⁻¹，積分公式 ∫ xⁿ dx = xⁿ⁺¹/(n+1) + C，微積分基本定理 ∫_a^b f(x)dx = F(b) - F(a)。',
    formulaBanner: '微分: d/dx (xⁿ) = n·xⁿ⁻¹ ； 積分: ∫ xⁿ dx = xⁿ⁺¹/(n+1) + C ； 基本定理: ∫_a^b f(x)dx = F(b) - F(a)',
    visualHighlights: [
      { label: '導數幾何意義', desc: 'f\'(x₀) 代表曲線 y = f(x) 在 x = x₀ 處之「切線斜率 (Tangent Slope)」', badge: '切線斜率' },
      { label: '極值一階二階檢驗', desc: '若 f\'(c) = 0 且 f\'\'(c) < 0 為局部極大值；若 f\'\'(c) > 0 為局部極小值', badge: '極值判定' },
      { label: '定積分求面積', desc: '兩曲線 y = f(x) 與 y = g(x) 夾面積 A = ∫_a^b |f(x) - g(x)| dx', badge: '曲線面積' },
    ],
    keyTakeaways: [
      '力學中剪力與彎矩之微分連動：dM/dx = V(x)，故剪力為零處 (V=0) 正是彎矩取極值之處。',
      '微積分基本定理連結了微分與積分互為逆運算：導數求變化率，定積分求累積量（面積、功、體積）。',
      '多項式連續函數在封閉區間 [a, b] 上必定存在絕對最大值與絕對最小值，出現在臨界點 (f\'=0) 或區間端點。',
    ],
  },

  // ==========================================
  // 8. PHYSICS, CHEMISTRY, HISTORY, GEOGRAPHY, CIVICS, EXTENSIONS (37 Topics)
  // ==========================================
  'physics/mechanics-motion': {
    topicSlug: 'mechanics-motion',
    title: '牛頓運動定律、等加速度運動與動量守恆',
    subtitle: '運動學三大公式、牛頓三大運動定律與衝量動量定理',
    conceptType: 'equilibrium-vector',
    icon: '🚀',
    diagramTitle: 'v-t 速度時間圖（斜率為加速度 a，圖形面積為位移 S）與 F = ma 力學圖解',
    diagramDescription: '展示 v = v₀ + at, S = v₀t + 1/2·at², v² = v₀² + 2aS，及動量守恆在碰撞結構中之衝擊力吸收。',
    formulaBanner: '牛頓第二定律: F = m·a ； 運動學三大式: S = v₀·t + 1/2·a·t² ； 動量 p = m·v',
    visualHighlights: [
      { label: 'v-t 圖斜率與面積', desc: 'v-t 圖之切線斜率代表加速度 a，曲線與時間軸所包圍之面積代表總位移 S', badge: 'v-t 圖' },
      { label: '慣性與反作用力', desc: '第一定律（動者恆動）、第三定律（作用力與反作用力大小相等方向相反）', badge: '運動定律' },
      { label: '動量守恆定律', desc: '不受外力系統中，碰撞前後總動量維持守恆 (m₁v₁ + m₂v₂ = m₁v₁\' + m₂v₂\')', badge: '衝擊碰撞' },
    ],
    keyTakeaways: [
      '自由落體運動為初速 v₀ = 0、加速度 a = g (9.8 m/s²) 之等加速度運動。',
      '衝量 J = F · Δt = Δp（動量變化量），延長受力時間 Δt（如汽車安全氣囊、耐震阻尼器）可大幅降低衝擊力 F。',
      '向心加速度 a_c = v² / r = ω²·r，方向永遠指向圓心，由向心力提供。',
    ],
  },
  'physics/work-energy': {
    topicSlug: 'work-energy',
    title: '功、動能、重力位能與力學能守恆',
    subtitle: '作功 W = F·d·cosθ、動能 Ek = 1/2·mv²、位能 Ug = mgh 與能量守恆',
    conceptType: 'equilibrium-vector',
    icon: '⚡',
    diagramTitle: '單擺與自由落體力學能守恆（動能與重力位能互相轉換）能量轉換圖',
    diagramDescription: '展示無摩擦阻力下，總力學能 E = Ek + Ep = 定值，及外力作功等於系統動能變化量（功能定理）。',
    formulaBanner: '功: W = F·d·cosθ ； 力學能守恆: 1/2·m·v₁² + m·g·h₁ = 1/2·m·v₂² + m·g·h₂',
    visualHighlights: [
      { label: '正功 vs 負功', desc: '力與位移同向 (θ < 90°) 作正功；反向 (θ > 90°) 作負功；垂直 (θ = 90°) 作功為 0', badge: '作功條件' },
      { label: '功能定理 (Work-Energy)', desc: '合力對物體所作的總功，等於該物體「動能的變化量 (ΔEk)」', badge: '動能增減' },
      { label: '彈性位能', desc: '彈簧受力變形 x 所儲存之位能 Ep = 1/2 · k · x²', badge: '彈簧儲能' },
    ],
    keyTakeaways: [
      '向心力、正向力（垂直位移時）對物體「永遠不作功」。',
      '摩擦力通常對系統作負功，將力學能轉化為熱能散失於環境中。',
      '功率 P = W / t = F · v，代表單位時間內所作的功（單位為瓦特 W = J/s 或馬力 HP）。',
    ],
  },
  'physics/thermodynamics': {
    topicSlug: 'thermodynamics',
    title: '熱傳導、熱對流、熱輻射與建築熱工學',
    subtitle: '傅立葉熱傳導定律 Q/t = kAΔT/L、熱阻 R = L/k 與建築外殼耗能 U 值',
    conceptType: 'environmental-physics',
    icon: '🔥',
    diagramTitle: '建築外牆多層複合構造（飾面+RC+保溫層+石膏板）溫度梯度與熱流圖解',
    diagramDescription: '展示熱傳三途徑（固體傳導、流體對流、電磁波輻射），及熱總阻 R_total = Σ(L_i / k_i) 與外殼熱傳透率 U = 1/R_total。',
    formulaBanner: '傅立葉熱傳導: Q/t = k · A · (T_hot - T_cold) / L ； 總熱傳透率 U = 1 / ΣR_i',
    visualHighlights: [
      { label: '熱傳導 (Conduction)', desc: '固體內部微觀分子振動傳遞熱量，保溫材料（如岩棉、發泡板）導熱係數 k 極低', badge: '固體傳熱' },
      { label: '熱對流 (Convection)', desc: '流體（空氣/水）流動傳熱，建築天井利用「煙囪效應」驅動自然通風降溫', badge: '流體循環' },
      { label: '熱輻射 (Radiation)', desc: '不需要介質，以電磁波形式直接傳播（太陽輻射），Low-E 玻璃能反射熱輻射', badge: '電磁波傳熱' },
    ],
    keyTakeaways: [
      '建築外殼保溫的核心公式：總熱阻 R = 各層厚度 L 除以導熱係數 k 之和；U 值越小代表隔熱性能越好。',
      '熱橋效應 (Thermal Bridge)：建築梁柱金屬節點若未包覆保溫層，熱量會集中自此處快速流失或結露發霉。',
      '熱力學第一定律為能量守恆；第二定律指出熱量不會自發地從低溫物體傳遞到高溫物體（熵增原理）。',
    ],
  },
  'physics/waves-acoustics': {
    topicSlug: 'waves-acoustics',
    title: '聲波物理、分貝 (dB)、建築吸音與殘響時間',
    subtitle: '聲速 v = f·λ、聲壓級 Lp = 20log(P/P₀) dB 與塞賓殘響公式 (Sabine RT60)',
    conceptType: 'environmental-physics',
    icon: '🔊',
    diagramTitle: '音樂廳空間聲線反射殘響衰減曲線與塞賓殘響時間 RT60 = 0.161V / A 計算圖',
    diagramDescription: '展示直達聲、早期反射聲與擴散聲，多孔吸音材料（吸收中高頻）vs 板狀共振吸音（吸收低頻）機制。',
    formulaBanner: '塞賓殘響公式: RT₆₀ = 0.161 · V / A ； 分貝公式: dB = 10 · log₁₀(I / I₀)',
    visualHighlights: [
      { label: '殘響時間 (RT60)', desc: '聲源停止發聲後，室內聲能密度衰減 60 dB（百萬分之一）所需的時間', badge: '音質關鍵' },
      { label: '吸音 vs 隔音', desc: '吸音（多孔隙材料減少室內迴音）；隔音（高密度實心厚重牆體阻擋聲音穿透）', badge: '聲學區分' },
      { label: '分貝對數疊加', desc: '兩個 60 dB 的相同噪音源同時發聲，合成總音量為 63 dB（非 120 dB）', badge: '+3 dB 翻倍' },
    ],
    keyTakeaways: [
      '音樂廳最佳殘響時間約為 1.8~2.2 秒（飽滿共鳴）；演講廳與教室最佳殘響時間約為 0.6~0.8 秒（高語音清晰度）。',
      '聲波強度每增加一倍，分貝值增加 3 dB (10·log2 ≈ 3.01 dB)。',
      '質量定律 (Mass Law)：隔音單層牆之面密度每增加一倍，其空氣音隔音量 (TL) 理論上提高約 6 dB。',
    ],
  },
  'physics/optics': {
    topicSlug: 'optics',
    title: '幾何光學、折射定律與建築自然採光設計',
    subtitle: '司乃耳折射定律 n₁sinθ₁ = n₂sinθ₂、全反射、採光係數 (DF) 與眩光控制',
    conceptType: 'environmental-physics',
    icon: '💡',
    diagramTitle: '光線穿透窗玻璃折射路徑、全反射臨界角與室內採光係數 (Daylight Factor) 分佈圖',
    diagramDescription: '展示光線自空氣 (n=1) 進入玻璃 (n=1.5) 向法線偏折，及建築深開口利用導光板 (Light Shelf) 將日光引進建築深處。',
    formulaBanner: '折射定律 (Snell\'s Law): n₁ · sinθ₁ = n₂ · sinθ₂ ； 採光係數 DF = (室內照度 / 室外全陰天照度) × 100%',
    visualHighlights: [
      { label: '司乃耳定律', desc: '光從光疏介質進入光密介質（如空氣至水/玻璃），折射角小於入射角（偏向法線）', badge: '折射偏向' },
      { label: '全反射 (Total Reflection)', desc: '光由光密介質射向光疏介質且入射角大於臨界角 (θ > θc) 時，光線 100% 反射（光纖原理）', badge: '全反射' },
      { label: '導光遮陽板 (Light Shelf)', desc: '窗戶上方水平延伸板，阻擋直射眩光，並將反射陽光投射至天花板漫射至深處', badge: '自然採光' },
    ],
    keyTakeaways: [
      '建築採光標準：一般辦公室與教室桌面工作面照度應維持在 300 至 500 Lux 以上。',
      '全反射臨界角公式：sinθc = n2 / n1（條件為 n1 > n2）。',
      '眩光 (Glare) 控制：避免直射陽光照射工作面，開窗應配合深遮陽板或磨砂玻璃形成均勻漫射光。',
    ],
  },
  'physics/electricity': {
    topicSlug: 'electricity',
    title: '電路學、歐姆定律、交流電與用電安全防護',
    subtitle: '歐姆定律 V = I·R、電功率 P = V·I、串並聯電路與漏電斷路器 (ELCB)',
    conceptType: 'flowchart-logic',
    icon: '⚡',
    diagramTitle: '家庭單相三線制 (110V/220V) 配電迴路與接地系統安全防護圖解',
    diagramDescription: '展示火線 (L1/L2, 110V)、中性線 (N, 0V)、接地線 (G)，電功率計算，及漏電斷路器 (ELCB) 偵測平衡電流毫秒跳脫。',
    formulaBanner: '歐姆定律: V = I · R ； 電功率: P = V · I = I²·R = V²/R ； 耗電度數 (kWh) = (P × 小時) / 1000',
    visualHighlights: [
      { label: '單相三線系統', desc: '兩條 110V 火線與一條中性線，可同時供應 110V（插座/照明）與 220V（冷氣/熱水器）', badge: '居家配電' },
      { label: '串聯 vs 並聯', desc: '家庭電器一律採用「並聯」，各電器獨立工作且承受相同額定電壓 (110V)', badge: '並聯供電' },
      { label: '漏電斷路器 (ELCB)', desc: '裝設於廚房、衛浴、陽台潮濕區域，當漏電電流達 15~30 mA 在 0.1 秒內跳脫斷電', badge: '人身安全' },
    ],
    keyTakeaways: [
      '家庭電路中，電器越多並聯使用，總電阻越小，總電流越大，可能導致電線過載發熱起火。',
      '1 度電 = 1 瓩·小時 (1 kWh) = 1000 瓦電器連續使用 1 小時消耗的電能 (3.6×10⁶ 焦耳)。',
      '綠色地線 (G) 與設備外殼接地：當內部電線破損碰殼時，電流經地線導入大地，觸發斷路器跳脫防止人員感電。',
    ],
  },

  // ==========================================
  // CHEMISTRY (7 Topics)
  // ==========================================
  'chemistry/matter-structure': {
    topicSlug: 'matter-structure',
    title: '原子構造、週期表規律與化學鍵結',
    subtitle: '質子中子電子、八隅體法則、共價鍵/離子鍵/金屬鍵與結晶點陣',
    conceptType: 'material-reaction',
    icon: '⚛️',
    diagramTitle: '金屬鍵自由電子海模型 vs 離子鍵晶格 vs 共價鍵電子雲幾何圖解',
    diagramDescription: '展示金屬鍵（自由電子賦予鋼鐵優良導電延展性）、離子鍵（NaCl 脆性解理面）與共價鍵（金剛石高硬度）。',
    formulaBanner: '化學鍵能: 共價鍵 (分子共用電子) ； 離子鍵 (正負離子庫倫引力) ； 金屬鍵 (陽離子+自由電子海)',
    visualHighlights: [
      { label: '金屬鍵 (Metallic Bond)', desc: '金屬陽離子浸潤在自由電子海中，外力敲擊時原子層滑移而不斷裂，具高延展性', badge: '延展導電' },
      { label: '離子鍵 (Ionic Bond)', desc: '陰陽離子緊密排列晶格，受外力剪切時同號電荷相斥立即脆性碎裂（陶瓷/礦物）', badge: '高硬脆性' },
      { label: '共價鍵 (Covalent Bond)', desc: '非金屬原子間共用電子對，鍵能極強（如高分子塑料骨架 C-C 鍵）', badge: '定向分子' },
    ],
    keyTakeaways: [
      '金屬良好導電導熱性與塑性加工能力，根本原因來自微觀結構中可自由移動的「自由電子海」。',
      '週期表同族元素具有相同價電子數，表現出相似之化學反應活性（如鹼金屬、鹵素）。',
      '凡得瓦爾力 (Van der Waals) 與氫鍵屬於分子間作用力，強度遠小於化學鍵，決定材料沸點與表面吸附。',
    ],
  },
  'chemistry/chemical-reactions': {
    topicSlug: 'chemical-reactions',
    title: '化學計量、莫耳數與反應速率催化機制',
    subtitle: '莫耳質量換算、理想氣體方程式 PV = nRT、活化能與勒沙特列平衡',
    conceptType: 'material-reaction',
    icon: '🧪',
    diagramTitle: '化學反應能量活化能 (Ea) 勢壘曲線（催化劑降低活化能加快反應）圖解',
    diagramDescription: '展示反應物 → 活化錯合物 → 生成物之放熱/吸熱過程，及溫度、濃度、接觸面積與催化劑對反應速率之影響。',
    formulaBanner: '莫耳數 n = 質量 m / 分子量 M ； 理想氣體: P·V = n·R·T (R = 0.082 atm·L/(mol·K))',
    visualHighlights: [
      { label: '亞佛加厥數', desc: '1 莫耳 (mol) 物質包含 6.02 × 10²³ 個微觀粒子（原子或分子）', badge: '6.02×10²³' },
      { label: '催化劑 (Catalyst)', desc: '改變反應路徑降低活化能 Ea，加速反應速率，但「不改變化學平衡常數 K」與總產量', badge: '降低活化能' },
      { label: '勒沙特列原理', desc: '平衡系統受到外界條件改變時，系統朝向「減弱該改變」之方向移動', badge: '平衡移動' },
    ],
    keyTakeaways: [
      '水泥水化反應屬於強烈放熱反應，高溫環境會加速水化反應速率，故大體積混凝土需控制溫升。',
      '標準狀態 (STP: 0°C, 1 atm) 下，1 莫耳任何理想氣體體積約為 22.4 公升。',
      '固體反應物之接觸表面積越大（如水泥研磨越細），反應碰撞機率越高，水化反應越迅速。',
    ],
  },
  'chemistry/acids-bases-salts': {
    topicSlug: 'acids-bases-salts',
    title: '酸鹼中和、pH 值、緩衝溶液與混凝土鹼性保護',
    subtitle: 'pH = -log[H⁺]、水解平衡、混凝土強鹼性 (pH 12~13) 與中性化 (碳化)',
    conceptType: 'material-reaction',
    icon: '🧪',
    diagramTitle: 'pH 0~14 尺度與混凝土內部鹼性保護膜 (鈍化膜 pH > 11.5) 碳化酸雨中性化破壞圖',
    diagramDescription: '展示混凝土中 Ca(OH)2 賦予 pH 12~13 形成鈍化膜保護鋼筋不生鏽，當空氣中 CO2 滲入反應成 CaCO3 使 pH < 9 時鋼筋爆裂生鏽。',
    formulaBanner: '混凝土碳化反應: Ca(OH)₂ (強鹼 pH>12) + CO₂ (空氣) → CaCO₃ (中性) + H₂O (鈍化膜消失)',
    visualHighlights: [
      { label: '鋼筋鈍化膜 (Passivation Film)', desc: '強鹼環境 (pH > 11.5) 下鋼筋表面生成極薄且緻密之 γ-Fe2O3 氧化膜，阻絕氧氣與水鏽蝕', badge: '強鹼防鏽' },
      { label: '中性化碳化深度', desc: '碳化深度隨時間平方根增加 (d = k·√t)，當碳化前線抵達鋼筋表面即引發全面生鏽', badge: '耐久壽命' },
      { label: '保護層厚度', desc: '梁柱主筋保護層厚度依法規至少需 4 公分，提供足夠距離延緩中性化到達鋼筋的時間', badge: '耐火防蝕' },
    ],
    keyTakeaways: [
      '新鮮混凝土為強鹼性 (pH ≈ 12.5~13.5)，是鋼筋結構百年不鏽的最根本天然化學防護盾。',
      '酸雨（pH < 5.0）與大氣二氧化碳會中和混凝土鹼性，導致「混凝土中性化」，破壞鋼筋防鏽保護。',
      '現場檢驗混凝土碳化深度：以 1% 酚酞 (Phenolphthalein) 酒精溶液噴灑於新鮮斷面，未碳化強鹼區呈「紫紅色」，碳化區「無色」。',
    ],
  },
  'chemistry/redox': {
    topicSlug: 'redox',
    title: '氧化還原、電化學腐蝕與鋼結構陰極防蝕',
    subtitle: '氧化數判定、金屬活動性順序、海砂氯離子腐蝕與外加電流/犧牲陽極防蝕',
    conceptType: 'material-reaction',
    icon: '🔋',
    diagramTitle: '鋼筋混凝土氯離子 (Cl⁻) 催化電化學腐蝕電池模型與犧牲陽極 (鋅塊) 防蝕圖解',
    diagramDescription: '展示陽極區 Fe → Fe²⁺ + 2e⁻，陰極區 O2 + 2H2O + 4e⁻ → 4OH⁻，生成膨脹性鐵鏽體積膨脹 3~6 倍擠裂混凝土。',
    formulaBanner: '鋼筋腐蝕反應: 陽極 Fe → Fe²⁺ + 2e⁻ ； 陰極 O₂ + 2H₂O + 4e⁻ → 4OH⁻ ； 體積膨脹 3~6 倍',
    visualHighlights: [
      { label: '氯離子穿透 (海砂屋)', desc: 'Cl⁻ 穿透破壞鈍化膜，形成點蝕 (Pitting)，並作為催化劑反覆加速鐵氧化', badge: '海砂殺手' },
      { label: '犧牲陽極法 (Galvanic)', desc: '連接活性比鐵大之金屬（如鋅 Zn 或鎂 Mg），鋅優先氧化失去電子，保護主結構鋼材', badge: '犧牲陽極' },
      { label: '外加電流陰極防蝕 (ICCP)', desc: '以直流電源負極接結構鋼筋、正極接輔助陽極，強制電子流入鋼筋阻止氧化', badge: '大型工程' },
    ],
    keyTakeaways: [
      '金屬活動性順序：K > Na > Ca > Mg > Al > Zn > Fe > Sn > Pb > (H) > Cu > Hg > Ag > Pt > Au。',
      '鋼筋生鏽生成的水合氧化鐵體積比原鋼材大 3 至 6 倍，產生巨大內部膨脹拉應力導致混凝土保護層開裂剝落。',
      'CNS 3090 規範規定預拌混凝土中最大水溶性氯離子含量不得超過 0.15 kg/m³（防範海砂屋標準）。',
    ],
  },
  'chemistry/organic-chemistry': {
    topicSlug: 'organic-chemistry',
    title: '有機化合物、官能基與建築高分子合成',
    subtitle: '烷/烯/炔/醇/醛/酸/酯、聚合反應（加成 vs 縮合）與防火耐燃材料',
    conceptType: 'material-reaction',
    icon: '🧪',
    diagramTitle: '單體聚合反應機制（加成聚合 PE/PVC vs 縮合聚合 PET/尼龍）分子鏈結構圖',
    diagramDescription: '展示乙烯雙鍵打開聚合為聚乙烯，環氧樹脂與硬化劑立體交聯固化，及難燃劑阻斷燃燒自由基機制。',
    formulaBanner: '加成聚合: n CH₂=CH₂ → [-CH₂-CH₂-]ₙ (PE) ； 縮合聚合: 脫水或小分子縮合 (Polyester)',
    visualHighlights: [
      { label: '聚氯乙烯 (PVC)', desc: '單體氯乙烯加成聚合，抗酸鹼耐腐蝕，廣泛用於建築給排水管與電線絕緣皮', badge: '管材主力' },
      { label: '聚碳酸酯 (PC)', desc: '工程塑膠，高透光率且耐衝擊強度為玻璃 250 倍，用於採光罩與防爆隔音牆', badge: '耐力板' },
      { label: '阻燃劑機制', desc: '添加鹵素或磷系化合物，在高溫下釋放自由基捕獲劑或形成表面碳化隔熱層阻燃', badge: '耐火建材' },
    ],
    keyTakeaways: [
      '同分異構物 (Isomers)：具有相同分子式但不同結構排列與物理化學性質的化合物。',
      '聚苯乙烯 (PS) 發泡即為保麗龍 (EPS/XPS)，導熱係數極低，但耐火性差遇火燃燒釋放濃煙，需添加難燃劑。',
      '甲醛 (HCHO) 為揮發性致癌物，常存於劣質合板膠水與塗料中，室內應嚴格選用 E1/E0 級低甲醛綠建材。',
    ],
  },
  'chemistry/environmental-chemistry': {
    topicSlug: 'environmental-chemistry',
    title: '環境化學、溫室效應、酸雨與室內空氣品質',
    subtitle: '溫室氣體 (CO₂/CH₄)、光化學煙霧、酸雨成因 (SOx/NOx) 與 TVOC/甲醛檢測',
    conceptType: 'environmental-physics',
    icon: '🌍',
    diagramTitle: '大氣溫室效應輻射平衡與石化燃燒 SOx/NOx 生成硫酸/硝酸酸雨反應路徑圖',
    diagramDescription: '展示地表長波輻射被 CO2 吸收造成全球暖化，及二氧化硫與氮氧化物轉化為酸雨腐蝕建築金屬與石材。',
    formulaBanner: '酸雨形成: SO₂ + H₂O → H₂SO₃ ； 2SO₂ + O₂ + 2H₂O → 2H₂SO₄ (硫酸酸雨 pH < 5.0)',
    visualHighlights: [
      { label: '溫室效應 (Greenhouse Effect)', desc: '大氣中 CO₂、CH₄、N₂O 吸收地表發射之長波紅外線輻射，造成全球氣候暖化', badge: '碳中和目標' },
      { label: '酸雨侵蝕建築', desc: '酸雨與石材碳酸鈣反應 CaCO₃ + H₂SO₄ → CaSO₄ + CO₂ + H₂O，造成雕像溶解剝落', badge: '建築侵蝕' },
      { label: '室內 TVOC 逸散', desc: '總揮發性有機物包含苯、甲苯、二甲苯，綠建築標準限制室內濃度 ≤ 0.56 ppm', badge: '空氣品質' },
    ],
    keyTakeaways: [
      '自然雨水因溶解大氣中二氧化碳呈弱酸性 (pH ≈ 5.6)；當雨水 pH < 5.0 時即定義為「酸雨」。',
      '水泥生產佔全球人為碳排放約 8%，主要來自石灰石高溫煅燒 CaCO3 → CaO + CO2。',
      '室內二氧化碳 (CO2) 濃度若超過 1000 ppm 會導致嗜睡與專注力下降，建築通風換氣率至關重要。',
    ],
  },
  'chemistry/materials-chemistry': {
    topicSlug: 'materials-chemistry',
    title: '材料化學、奈米材料與自潔塗層光觸媒',
    subtitle: '二氧化鈦 (TiO₂) 光觸媒超親水性、奈米碳管、氣凝膠與自癒合混凝土',
    conceptType: 'material-reaction',
    icon: '✨',
    diagramTitle: 'TiO₂ 光觸媒在紫外線照射下激發電子-電洞對分解有機污垢與超親水自潔圖解',
    diagramDescription: '展示 TiO2 吸收 UV 產生氫氧自由基 ·OH 分解污垢，表面形成水膜使雨水直接沖刷帶走灰塵（蓮花效應）。',
    formulaBanner: '光觸媒自潔: TiO₂ + hν (UV) → e⁻ + h⁺ ； h⁺ + H₂O → ·OH (超強氧化自由基分解污垢)',
    visualHighlights: [
      { label: '光觸媒自潔外牆 (TiO₂)', desc: '利用太陽紫外線分解表面附著油脂，下雨時水均勻鋪展形成水膜將污垢帶走', badge: '長效潔淨' },
      { label: '二氧化矽氣凝膠 (Aerogel)', desc: '固態奈米多孔材料，孔隙率高達 99%，導熱係數極低 (k < 0.015 W/mK)，終極隔熱材料', badge: '超級隔熱' },
      { label: '自癒合混凝土 (Self-healing)', desc: '包覆枯草芽孢桿菌微膠囊，當混凝土開裂水滲入時細菌甦醒分泌 CaCO3 結晶自動修補裂縫', badge: '仿生修復' },
    ],
    keyTakeaways: [
      '光觸媒塗層的兩大特性：1. 強氧化性分解有機物；2. 超親水性（接觸角接近 0°）使水流沖刷自潔。',
      '奈米材料（尺度 1~100 nm）由於比表面積巨大與量子效應，展現出遠超宏觀材料之強度與光電特性。',
      '碳封存混凝土技術：在混凝土攪拌過程中注入回收 CO2 形成永久納米碳酸鈣晶體，既提高早期強度又封存碳。',
    ],
  },

  // ==========================================
  // HISTORY, GEOGRAPHY, CIVICS (18 Topics)
  // ==========================================
  'history/taiwan-history': {
    topicSlug: 'taiwan-history',
    title: '台灣歷史演進與多元聚落建築空間形塑',
    subtitle: '南島原民、荷西明鄭、清代漢人移墾、日治現代化與戰後都會發展',
    conceptType: 'comparative-matrix',
    icon: '🇹🇼',
    diagramTitle: '台灣歷史發展階段與代表性建築聚落空間型態演進圖譜',
    diagramDescription: '展示原民石板屋/高腳屋 → 漢人傳統三合院/街屋市街 → 日治西洋歷史主義/折衷官廳 → 戰後現代主義都市空間。',
    formulaBanner: '台灣建築歷史流變: 原民風土 → 傳統閩南 → 日治官廳/街屋 → 當代多元地域',
    visualHighlights: [
      { label: '清代漢人聚落', desc: '三合院合院配置（正身、護龍、禾埕），依宗族血緣與防禦聚居，如板橋林本源園邸', badge: '宗族合院' },
      { label: '日治市區改正', desc: '棋盤格道路、下水道衛生改善，紅磚與洗石子洋風官廳（如總統府、台南州廳）', badge: '近代化轉型' },
      { label: '戰後十大建設', desc: '鋼鐵石化、南北高速公路與台中港，帶動台灣都市化與集合住宅公寓普及', badge: '工商業騰飛' },
    ],
    keyTakeaways: [
      '台灣建築空間反映多重文化疊合：南島風土、閩粵漢人傳統、近代日治引進之西方古典與當代多元地域主義。',
      '日治大正時期市區改正奠定了台北、台中、台南等主要城市現代都市骨幹與騎樓人行道制度。',
      '眷村建築與步登公寓（四、五層無電梯住宅）是戰後台灣特定歷史背景下形成的獨特集體居住記憶。',
    ],
  },
  'history/chinese-history': {
    topicSlug: 'chinese-history',
    title: '中國傳統建築體系與歷代王朝制度變遷',
    subtitle: '木構架系統（抬梁式 vs 穿斗式）、斗栱演變、封建禮制與都城軸線',
    conceptType: 'comparative-matrix',
    icon: '🏯',
    diagramTitle: '中國古建築木構架大木作體系（柱、梁、枋、斗栱、鋪作層）剖面分解圖',
    diagramDescription: '展示抬梁式（北方宮殿大跨度空間）、穿斗式（南方民居用料省）、斗栱演變（唐宋結構承重至明清裝飾化）。',
    formulaBanner: '木構兩大體系: 抬梁式 (柱上架梁，梁上架短柱，空間開闊) ； 穿斗式 (柱直接穿通檁條，用料省)',
    visualHighlights: [
      { label: '斗栱 (Dou-gong)', desc: '斗（方形墊木）與栱（弓形橫木）層層疊出，將巨大屋頂荷載分散傳遞至柱頂，具極佳耐震抗扭彈性', badge: '減震關節' },
      { label: '都城中軸對稱', desc: '《考工記》「匠人營國，方九里，旁三門，九經九緯」，前朝後市、左祖右社嚴格禮制', badge: '禮制空間' },
      { label: '屋頂等級次序', desc: '重簷廡殿頂（最高等級） > 重簷歇山頂 > 單簷廡殿 > 單簷歇山 > 懸山 > 硬山', badge: '位階制度' },
    ],
    keyTakeaways: [
      '斗栱在唐宋時期主要功能為「力學結構承重」，至明清時期逐漸縮小退化為「裝飾性符號」。',
      '中國傳統木構建築「牆倒屋不塌」的秘密在於榫卯柔性節點與斗栱能耗散地震能量。',
      '北京故宮紫禁城體現了極致的南北中軸對稱與前朝（三大殿）後寢（乾清坤寧）嚴格階級次序。',
    ],
  },
  'history/world-history': {
    topicSlug: 'world-history',
    title: '西方建築史流變：古典柱式、哥德拱券與現代主義',
    subtitle: '希臘三大柱式、羅馬拱券穹頂、中世紀哥德尖拱飛扶壁與包浩斯機能主義',
    conceptType: 'comparative-matrix',
    icon: '🏛️',
    diagramTitle: '西方建築經典結構技術演進譜系（梁柱 → 圓拱穹頂 → 尖拱飛扶壁 → 鋼筋混凝土框架）',
    diagramDescription: '展示希臘多立克/愛奧尼/科林斯柱式、羅馬萬神殿混凝土穹頂、哥德巴黎聖母院飛扶壁、及柯比意現代建築五點。',
    formulaBanner: '柯比意現代建築五點: 底層挑空 (Pilotis) / 自由平面 / 自由立面 / 水平帶窗 / 屋頂花園',
    visualHighlights: [
      { label: '希臘三大柱式', desc: '多立克 (Doric, 雄健無柱礎) / 愛奧尼 (Ionic, 雙渦卷優雅) / 科林斯 (Corinthian, 芼莨葉華麗)', badge: '古典秩序' },
      { label: '哥德結構革命', desc: '尖拱 (Pointed Arch) 減小側推力 + 飛扶壁 (Flying Buttress) 外導載重，使牆面能大面積開彩色玻璃窗', badge: '結構輕盈' },
      { label: '包浩斯與國際樣式', desc: '「形隨機能 (Form follows function)」，揚棄歷史裝飾，強調鋼骨玻璃與空間流動性', badge: '現代主義' },
    ],
    keyTakeaways: [
      '羅馬人發明火山灰混凝土與圓拱穹頂，創造出萬神殿 (Pantheon) 43.3 米無柱宏偉大跨度內部空間。',
      '哥德式建築以垂直向上的高聳線條與光線穿透，營造神聖崇高的宗教體驗。',
      '包浩斯 (Bauhaus) 開創了現代設計教育體系，將藝術、工藝與工業化大量生產完美結合。',
    ],
  },
  'history/architectural-history': {
    topicSlug: 'architectural-history',
    title: '近現代建築大師理論、思潮論述與經典名作',
    subtitle: '萊特有機建築、密斯少即是多、柯比意新建築五點、安藤忠雄與當代思潮',
    conceptType: 'comparative-matrix',
    icon: '🏢',
    diagramTitle: '現代主義四大家理論思想與代表作品（落水山莊/薩伏瓦別墅/巴塞隆納館）對照圖',
    diagramDescription: '展示柯比意（居住機器與新建築五點）、密斯（Less is more 鋼與玻璃）、萊特（Fallingwater 有機建築與環境融合）。',
    formulaBanner: '大師名言: Form follows function (Sullivan) ； Less is more (Mies) ； A house is a machine for living in (Corbusier)',
    visualHighlights: [
      { label: '柯比意 (Le Corbusier)', desc: '薩伏瓦別墅 (Villa Savoye)、馬賽公寓 (Unité d\'Habitation)，模矩人 (Modulor)', badge: '理性典範' },
      { label: '密斯 (Mies van der Rohe)', desc: '巴塞隆納德國館、西格拉姆大樓，極簡鋼與玻璃結構美學「少即是多 (Less is more)」', badge: '極簡結構' },
      { label: '萊特 (Frank Lloyd Wright)', desc: '落水山莊 (Fallingwater)、古根漢美術館，提倡建築自土地中自然生長的「有機建築」', badge: '有機自然' },
    ],
    keyTakeaways: [
      '柯比意「新建築五點」完全解放了傳統承重牆對室內平面的束縛，開創了現代自由空間。',
      '後現代主義 (Post-Modernism, Robert Venturi) 提出「Less is a bore (少即是乏味)」，重新引入歷史符號與隱喻。',
      '安藤忠雄 (Tadao Ando) 以極致細膩的清水混凝土、幾何秩序與光影穿透，開創當代批判地域主義詩意空間。',
    ],
  },
  'history/cultural-heritage': {
    topicSlug: 'cultural-heritage',
    title: '文化資產保存法規、古蹟修復倫理與再利用',
    subtitle: '文資法分類（古蹟/歷史建築/聚落建築群）、威尼斯憲章與修舊如舊原則',
    conceptType: 'flowchart-logic',
    icon: '🏛️',
    diagramTitle: '文資保存四階段（調查研究 → 修復設計 → 匠師施工 → 活化再利用）流程規範圖',
    diagramDescription: '展示《威尼斯憲章》修復原則（真實性、可逆性、可識別性、最小干預），及台灣古蹟修復工法。',
    formulaBanner: '文資修復國際四原則: 真實性 (Authenticity) / 可逆性 (Reversibility) / 可識別性 / 最小干預',
    visualHighlights: [
      { label: '真實性 (Authenticity)', desc: '保留不同歷史時期留下的真實構造痕跡，嚴禁毫無依據的憑空捏造復原', badge: '歷史真實' },
      { label: '可逆性 (Reversibility)', desc: '新加入的加固補強構件（如鋼構補強），在未來必須能安全拆除而不傷及原有古蹟本體', badge: '未來可拆' },
      { label: '活化再利用 (Adaptive Reuse)', desc: '注入當代文創、展示或公共功能，使歷史建築在現代生活中持續具備生命力', badge: '永續傳承' },
    ],
    keyTakeaways: [
      '《文資法》古蹟分類：國定古蹟（文化部審定）、直轄市定古蹟、縣市定古蹟。',
      '修復古蹟時新舊材料交接必須具備「可識別性」，讓參訪者能清楚辨別何處為原物、何處為現代修補。',
      '歷史建築經文資審議通過後，依法得享有容積移轉與地價稅、房屋稅減免等法定獎勵措施。',
    ],
  },
  'history/social-change': {
    topicSlug: 'social-change',
    title: '社會變遷、都市化進程與高齡少子化居住挑戰',
    subtitle: '工業化都市擴張、高齡社會無障礙通用設計、社會住宅與地方創生',
    conceptType: 'comparative-matrix',
    icon: '👥',
    diagramTitle: '台灣人口金字塔轉型（高齡少子化）與全齡通用設計 (Universal Design) 七原則圖解',
    diagramDescription: '展示都市化率超過 80%，超高齡社會無障礙斜坡、門檻齊平、昇降設備與青銀共居社會住宅政策。',
    formulaBanner: '通用設計 7 原則: 公平使用 / 彈性使用 / 簡易直覺 / 容錯安全 / 低體力消耗 / 空間尺度合宜',
    visualHighlights: [
      { label: '超高齡社會 (Super-Aged)', desc: '65 歲以上人口佔比超過 20%，推動無障礙友善環境、老舊公寓加裝電梯成為都市更新核心', badge: '高齡轉型' },
      { label: '社會住宅 (Social Housing)', desc: '只租不售，結合托嬰中心、日照中心與青年創業基地，落實居住正義', badge: '居住正義' },
      { label: '通用設計 (Universal Design)', desc: '不分年齡、性別、身心障礙與否，所有人都能輕鬆安全使用的空間設計', badge: '全齡友善' },
    ],
    keyTakeaways: [
      '台灣於 2025 年正式邁入「超高齡社會」（65 歲以上人口達 20% 以上）。',
      '無障礙通路坡道坡度依法規最大不得超過 1:12，每上升 75 公分必須設置長 150 公分以上之休息平台。',
      '危老條例（都市危險及老舊建築物加速重建條例）提供容積獎勵與稅賦減免，加速老舊耐震不足建物改建。',
    ],
  },

  // ==========================================
  // GEOGRAPHY & CIVICS (12 Topics)
  // ==========================================
  'geography/environment-terrain': {
    topicSlug: 'environment-terrain',
    title: '地形地貌、板塊構造與斷層地質災害防治',
    subtitle: '板塊擠壓（歐亞 vs 菲律賓海）、活動斷層帶、順向坡滑動與土石流潛勢',
    conceptType: 'survey-geometry',
    icon: '⛰️',
    diagramTitle: '台灣造山帶板塊碰撞剖面圖與地層順向坡 (Dip Slope) 雨水潤滑崩塌機制圖解',
    diagramDescription: '展示岩層傾角與坡面傾角一致時，地下水在層理面產生水壓潤滑引發順向坡滑動（如國道三號七堵走山事件）。',
    formulaBanner: '順向坡滑動條件: 岩層走向與坡面平行 ； 岩層傾角 (θ_bed) < 坡面傾角 (θ_slope) 且出露於坡腳',
    visualHighlights: [
      { label: '板塊隱沒碰撞', desc: '菲律賓海板塊以每年約 8 公分向西北隱沒碰撞歐亞大陸板塊，造成台灣地震頻繁地形陡峭', badge: '構造活躍' },
      { label: '順向坡 (Dip Slope)', desc: '極危險地質，坡腳嚴禁任意開挖砍除，並需設置深層截水溝與地錨加固', badge: '地質敏感' },
      { label: '土石流三要素', desc: '充足鬆散土石、劇烈地形坡度 (15°~30°)、持續暴雨降雨量（土石流警戒雨量）', badge: '水土保持' },
    ],
    keyTakeaways: [
      '建築基地若位於「活動斷層兩側一定範圍內」或「地質敏感區」，依法必須進行專案地質調查與加強耐震設計。',
      '順向坡邊坡開挖時，破壞了坡腳支撐阻力，雨水沿著岩層弱面滲入潤滑極易引發災難性整體滑動。',
      '等高線圖判讀：等高線向高處凸出為「山谷（集水線）」；等高線向低處凸出為「山脊（分水嶺）」。',
    ],
  },
  'geography/climate-environment': {
    topicSlug: 'climate-environment',
    title: '氣候水文、季風洋流與台灣微氣候風土建築',
    subtitle: '副熱帶季風、梅雨颱風水文、都市熱島效應 (UHI) 與通風採光微氣候',
    conceptType: 'environmental-physics',
    icon: '🌦️',
    diagramTitle: '台灣冬夏季風流場路徑與都市熱島效應 (Urban Heat Island) 氣溫熱島圖譜',
    diagramDescription: '展示夏季西南季風與冬季東北季風，都市下墊面柏油水泥蓄熱產生高溫中心，及利用風道與綠化水體降溫。',
    formulaBanner: '降溫策略: 綠覆率 ≥ 50% ； 透水地坪保水降溫 ； 迎風面建築退縮引導通風風道',
    visualHighlights: [
      { label: '季風風向特徵', desc: '夏季吹溫暖潮濕「西南季風」，冬季吹寒冷乾燥「東北季風」（北部迎風面多雨）', badge: '季節風向' },
      { label: '都市熱島效應', desc: '大量柏油混凝土人工鋪面、空調排熱與高樓阻擋通風，使市中心氣溫比郊區高出 3~5°C', badge: '城市發燒' },
      { label: '風土遮陽策略', desc: '台灣夏季太陽高度角高 (約 88°)，南向外遮陽以「水平遮陽板」最有效，東西向以「垂直遮陽」最佳', badge: '遮陽設計' },
    ],
    keyTakeaways: [
      '建築遮陽黃金原則：南向窗戶採「水平遮陽板」擋住正午高角度陽光；東西向窗戶採「垂直遮陽板」阻擋斜射低角度西曬。',
      '都市風道 (Wind Corridor)：沿主要道路與河川軸線留設連續開闊綠帶，可將涼爽海風引進城市中心緩解熱島效應。',
      '基隆因冬季東北季風受地形抬升迎風面冷凝，年降雨日數極多而有「雨港」之稱。',
    ],
  },
  'geography/population-urban': {
    topicSlug: 'population-urban',
    title: '都市計畫體系、土地使用分區與人口空間分佈',
    subtitle: '都市計畫三大類型（市鎮/鄉街/特定區）、分區管制（住/商/工/保）與容積率',
    conceptType: 'flowchart-logic',
    icon: '🏙️',
    diagramTitle: '土地使用分區管制（建蔽率決定空地、容積率決定總量）建築量體空間模型圖',
    diagramDescription: '展示基地面積 1000m²、建蔽率 60%、容積率 300% 之建築量體組合方案（5 層滿蓋 vs 10 層退縮留設大廣場）。',
    formulaBanner: '建築面積 = 基地面積 × 建蔽率 ； 總樓地板面積 = 基地面積 × 容積率',
    visualHighlights: [
      { label: '建蔽率 (Building Coverage)', desc: '建築物在基地上的水平投影面積佔基地面積的百分比，保障採光通風與法定空地', badge: '平面覆蓋' },
      { label: '容積率 (Floor Area Ratio)', desc: '地上各層樓地板面積總和佔基地面積的百分比，管制都市總人口與活動總密度', badge: '立體總量' },
      { label: '使用分區管制', desc: '住宅區 (住一~住四)、商業區 (商一~商四)、工業區、農業區、保護區', badge: '分區管制' },
    ],
    keyTakeaways: [
      '同一個容積率下，降低建蔽率可以將建築物向上蓋得更高、更苗條，留出更多地面開放空間與綠地。',
      '都市計畫法規體系：都市計畫法（母法） → 都市計畫法施行細則 → 各主要計畫與細部計畫土管規定。',
      '公共設施保留地（如學校、公園、道路）是保障都市居民基本生活品質之法定用地。',
    ],
  },
  'geography/regional-development': {
    topicSlug: 'regional-development',
    title: '區域發展、國土計畫法三層架構與交通路網',
    subtitle: '國土功能分區（國土保育/海洋資源/農業發展/城鄉發展）與 TOD 軌道導向發展',
    conceptType: 'flowchart-logic',
    icon: '🗺️',
    diagramTitle: '《國土計畫法》四大國土功能分區劃設架構與高鐵/捷運 TOD 節點輻射發展圖解',
    diagramDescription: '展示以捷運站為核心 (500m 步行圈)，高密度混合開發 TOD (Transit-Oriented Development) 減少汽車依賴。',
    formulaBanner: 'TOD 軌道導向: 步行 500 公尺生活圈 (5~8 分鐘) ； 混合住宅、商務、休閒於一體',
    visualHighlights: [
      { label: '國土四大功能分區', desc: '國土保育地區、海洋資源地區、農業發展地區、城鄉發展地區（取代舊有區域計畫法）', badge: '國土保育' },
      { label: 'TOD 軌道導向開發', desc: '圍繞大眾運輸車站進行高強度混合使用開發，鼓勵大眾運輸減少私有運具排碳', badge: '大眾運輸' },
      { label: '城鄉發展平衡', desc: '科學園區（竹科/中科/南科）帶動周邊新市鎮開發與高鐵特區生活圈串聯', badge: '產業軸帶' },
    ],
    keyTakeaways: [
      '《國土計畫法》全面取代過去非都市土地管制，確立「先保育後開發」之永續國土空間治理原則。',
      'TOD 的三大核心原則 (3D)：Density (高密度)、Diversity (土地多元使用)、Design (人本友善步行空間)。',
      '台灣西部高鐵生活圈將台北至高雄縮短為 90 分鐘一日生活圈，徹底改變了全島區域空間競合型態。',
    ],
  },
  'geography/environmental-issues': {
    topicSlug: 'environmental-issues',
    title: '環境議題、海平面上升與韌性海綿城市',
    subtitle: '極端氣候強降雨、都市熱島、地層下陷與透水鋪面/雨水花園海綿設施',
    conceptType: 'environmental-physics',
    icon: '🌊',
    diagramTitle: '傳統灰色排水系統 vs 海綿城市綠色基礎設施（透水鋪面/下凹綠地/雨水貯留）水循環對照圖',
    diagramDescription: '展示「慢排入滲、就地蓄留」，以透水瀝青、景觀滯洪池減緩洪峰流量，降低都市內澇淹水風險。',
    formulaBanner: '出流管制規定: 基地開發必須自設滯洪設施 ； 洪峰流量 Q = 1/360 · C · I · A',
    visualHighlights: [
      { label: '透水鋪面 (Porous Pavement)', desc: '讓雨水直接滲入地下土壤補充地下水，同時降低地表逕流與路面積水', badge: '雨水入滲' },
      { label: '雨水花園 (Rain Garden)', desc: '下凹式景觀植栽槽，利用土壤微生物與植物根系淨化雨水逕流污染', badge: '生態過濾' },
      { label: '地下滯洪蓄水池', desc: '暴雨時暫存大量屋頂與地表逕流，雨後再緩慢排入下水道或回收澆灌花木', badge: '削峰填谷' },
    ],
    keyTakeaways: [
      '海綿城市 (Sponge City) 的核心理念：改變「快速把水排掉」的傳統灰色思維，轉為「就地吸水、蓄水、滲水、淨水」。',
      '地層下陷主要原因為長期超抽地下水導致黏土層受壓壓密不可逆脫水，常發生於沿海養殖區。',
      '綠建築「基地保水指標」旨在評估建築基地涵養水分與蒸發降溫之生態能力。',
    ],
  },
  'geography/gis': {
    topicSlug: 'gis',
    title: '地理資訊系統 (GIS)、衛星遙測與空間疊圖分析',
    subtitle: '向量資料 (點/線/面)、網格資料 (Raster)、空間環域 (Buffer) 與坡度坡向分析',
    conceptType: 'flowchart-logic',
    icon: '🛰️',
    diagramTitle: 'GIS 多圖層空間疊加分析（地形坡度 + 道路網 + 敏感區 = 最佳建築選址）圖解',
    diagramDescription: '展示點（測站/建築）、線（道路/管線）、面（地籍/分區），及利用環域分析 (Buffer) 檢討消防服務半徑。',
    formulaBanner: 'GIS 空間分析: 疊圖分析 (Overlay) / 環域分析 (Buffer) / 視線分析 (Viewshed) / 坡度分析 (Slope)',
    visualHighlights: [
      { label: '向量資料 (Vector)', desc: '以精確坐標記錄點 (Point)、線 (Polyline)、面 (Polygon)，適合地籍界線與管線網路', badge: '精確幾何' },
      { label: '網格資料 (Raster)', desc: '以像元網格矩陣記錄數值（如 DEM 數位高程模型、衛星航照影像、溫度場）', badge: '連續場域' },
      { label: '空間環域分析 (Buffer)', desc: '以特定要素為中心向外擴展一定距離的緩衝區（如捷運站 500m 服務圈）', badge: '影響半徑' },
    ],
    keyTakeaways: [
      '建築基地選址分析：利用 GIS 疊合等高線坡度圖、土石流潛勢圖、斷層帶與道路網，快速篩選出安全可建地。',
      '數位高程模型 (DEM/DTM)：可精確計算基地整地工程之挖方量與填方量 (Cut and Fill)。',
      '空間資料坐標系統轉換：台灣常用 TWD97 / 二度分帶坐標 (TM2) 與 WGS84 GPS 經緯度系統。',
    ],
  },
  'civics/democracy-rule-of-law': {
    topicSlug: 'democracy-rule-of-law',
    title: '民主法治原則、依法行政與公法私法體系',
    subtitle: '憲法位階、法律保留原則、比例原則（適當/必要/狹義）與行政救濟',
    conceptType: 'comparative-matrix',
    icon: '⚖️',
    diagramTitle: '法律位階金字塔（憲法 > 法律 > 法規命令 > 行政規則）與行政處分救濟路徑圖',
    diagramDescription: '展示憲法最高性，建築法（法律）授權內政部訂定建築技術規則（法規命令），及訴願與行政訴訟救濟。',
    formulaBanner: '比例原則三子原則: 適當性 (有助於目的) ； 必要性 (侵害最小手段) ； 狹義比例 (衡量得失不失衡)',
    visualHighlights: [
      { label: '法律保留原則', desc: '限制人民自由權利事項（如拆除違建、撤銷建照），必須有法律明確授權', badge: '保障人權' },
      { label: '比例原則 (Proportionality)', desc: '政府採取之行政手段與欲達成之目的之間必須符合比例，不可「用大砲打小鳥」', badge: '手段適當' },
      { label: '行政救濟程序', desc: '不服行政機關處分（如建照不予核發） → 提起「訴願」 → 不服訴願決定 → 提起「行政訴訟」', badge: '救濟權利' },
    ],
    keyTakeaways: [
      '法律位階原則：下位法不得牴觸上位法（命令牴觸法律無效，法律牴觸憲法無效）。',
      '比例原則三要件：1. 適當性（手段能達目的）；2. 必要性（採最小侵害手段）；3. 衡量性（手段與利益相當）。',
      '依法行政為現代法治國核心：包含「法律優位」（不得違法）與「法律保留」（積極依法）。',
    ],
  },
  'civics/constitution-human-rights': {
    topicSlug: 'constitution-human-rights',
    title: '憲法基本權利、財產權保障與都市更新徵收',
    subtitle: '平等權、自由權、財產權（釋字 709 號都更合憲性）、居住權與公共利益',
    conceptType: 'flowchart-logic',
    icon: '🏛️',
    diagramTitle: '財產權保障 vs 公共利益徵收正當法律程序（聽證/合理補償/司法審查）平衡圖',
    diagramDescription: '展示憲法第 15 條財產權保障，都市更新中公聽會、聽證會正當程序，及土地徵收需符合公益性與必要性。',
    formulaBanner: '釋字 709 號都更審查: 必須踐行「正當法律程序」 ； 舉辦公開聽證會 ； 確保資訊對稱',
    visualHighlights: [
      { label: '財產權保障 (Art. 15)', desc: '保障人民財產之自由使用、收益與處分，國家徵收土地必須給予「合理市價補償」', badge: '私產保障' },
      { label: '正當法律程序 (Due Process)', desc: '重大開發與都更計畫必須舉辦公聽會、公開展覽、通知所有利害關係人表達意見', badge: '程序正義' },
      { label: '居住權 (Right to Housing)', desc: '國際人權公約保障適足居住權，反對無安置配套措施之強制迫遷', badge: '基本人權' },
    ],
    keyTakeaways: [
      '大法官釋字第 709 號解釋：都市更新涉及人民財產權與居住自由，主管機關核定前必須舉辦公開聽證會。',
      '土地徵收四要件：1. 具備重大公共利益；2. 具備絕對必要性；3. 無其他替代方案（侵害最小）；4. 給予完全補償。',
      '憲法第 23 條為基本權利限制之總閘門：唯有在防止妨礙他人自由、避免緊急危難、維持社會秩序或增進公共利益所必要者，得以法律限制之。',
    ],
  },
  'civics/labor-rights-safety': {
    topicSlug: 'labor-rights-safety',
    title: '勞動基準法、營造職業安全衛生與工地防墜',
    subtitle: '職安法、營造安全衛生設施標準、高處作業 (≥ 2m) 防墜三寶與勞動契約',
    conceptType: 'flowchart-logic',
    icon: '⛑️',
    diagramTitle: '營造工地高處墜落危害防護層級（消除危害 → 安全網/護欄 → 個人安全帶防墜）圖解',
    diagramDescription: '展示墜落高度 ≥ 2m 必須設置 90cm 高護欄、安全母索與背負式雙大鉤安全帶（高掛低用），及工地進場五項安全防護。',
    formulaBanner: '防墜第一鐵律: 高度 ≥ 2 公尺作業 ； 必須設置合格護欄、安全網或配戴全身背負式安全帶',
    visualHighlights: [
      { label: '防墜設施三道防線', desc: '1. 合格防護欄杆（高度 90cm 以上附中欄桿及腳趾板） ； 2. 安全平網 ； 3. 個人雙大鉤安全帶', badge: '防墜三寶' },
      { label: '高掛低用原則', desc: '安全帶掛鉤必須固定在人體腰部「上方之堅固錨定點 (安全母索)」，切忌低掛高用以防墜落距離過長', badge: '掛鉤規範' },
      { label: '勞工即時退避權', desc: '作業場所發生立即危險之虞時，雇主或工作場所負責人應即令停止作業，勞工得自行退避', badge: '生命至上' },
    ],
    keyTakeaways: [
      '營造業重大職業災害有超過 60% 來自「墜落危害」，開口部（電梯井、樓梯口、樓板邊緣）必須 100% 封閉或加設護欄。',
      '進入營造工地必須全員配戴符合 CNS 標準之合格安全帽並扣緊頤帶、穿著反光背心與防穿刺安全鞋。',
      '勞動基準法規定正常工時每日不得超過 8 小時，每週不得超過 40 小時，加班需發給法定加班費。',
    ],
  },
  'civics/engineering-ethics-public-interest': {
    topicSlug: 'engineering-ethics-public-interest',
    title: '工程倫理、建築師專業責任與吹哨者保護',
    subtitle: '公眾安全第一、利益衝突迴避、工程品質防弊與工程師社會責任 (CSR)',
    conceptType: 'comparative-matrix',
    icon: '🛡️',
    diagramTitle: '工程倫理決策金字塔（公眾生命安全 > 雇主利益 > 同儕關係 > 個人利益）',
    diagramDescription: '展示當雇主商業利益與公眾結構安全發生衝突時，工程師/建築師依法必須堅持「公眾安全至上」與通報義務。',
    formulaBanner: '工程倫理第一守則: 將公眾之安全、健康與福祉置於首要地位 (Public Safety First)',
    visualHighlights: [
      { label: '公眾安全優先', desc: '當工程設計涉及偷工減料或安全隱患時，工程師有法定義務拒絕簽證並向上通報', badge: '最高原則' },
      { label: '利益衝突迴避', desc: '不得同時向業主與材料承包商索取回扣或不當利益，維持專業獨立性與客觀性', badge: '誠實廉潔' },
      { label: '吹哨者保護 (Whistleblower)', desc: '保障勇於揭發公共工程重大貪腐弊案或偷工減料安全隱患之內部專業人員', badge: '揭弊保障' },
    ],
    keyTakeaways: [
      '建築師法規定：建築師受委託辦理業務，應遵守誠信原則，不得有損害公眾安全或謀取非法利益之行為。',
      '工程簽證制度是一項「法律上對公眾安全的重大責任擔保」，切勿借牌或未經實質審核盲目蓋章。',
      '在可預見的結構安全與生命危險面前，工程倫理絕對高於商業保密協定。',
    ],
  },
  'civics/sustainable-development': {
    topicSlug: 'sustainable-development',
    title: '永續發展目標 (SDGs)、淨零排放與碳定價機制',
    subtitle: '聯合國 17 項 SDGs、台灣 2050 淨零路徑、碳費碳稅與建築能效標示 (BERS)',
    conceptType: 'environmental-physics',
    icon: '🌱',
    diagramTitle: '台灣 2050 淨零轉型四大策略（能源/產業/生活/社會）與建築能效等級 (1+ 級) 標示',
    diagramDescription: '展示新建建築能效評估系統 (BERS) 1~7 級與 1+ 級近零碳建築 (Nearly Zero Energy Building, nZEB)。',
    formulaBanner: '建築能效標示: 1~7 級 ； 最優等 1+ 級 (節能 50% 以上 + 綠電) 邁向 2050 淨零碳排',
    visualHighlights: [
      { label: 'SDG 11 永續城鄉', desc: '建構具包容、安全、韌性及永續特質的城市與人類居住環境', badge: '永續城市' },
      { label: '建築能效標示 (BERS)', desc: '評估建築外殼、空調、照明三大耗能系統，核發 1 至 7 級標示，最高等級為 1+ 級', badge: '能效標章' },
      { label: '碳費與碳交易', desc: '落實使用者付費原則，高排碳企業需繳納碳費，激勵採用低碳建材與綠色施工技術', badge: '經濟誘因' },
    ],
    keyTakeaways: [
      '台灣 2050 淨零轉型目標：2050 年 100% 新建公有建築物及超過 85% 現有建築物達到近零碳建築 (nZEB)。',
      '建築全生命週期碳排包括「蘊含碳 (Embodied Carbon, 建材生產製造施工)」與「營運碳 (Operational Carbon, 日常用水用電)」。',
      '循環經濟三原則：源頭減量 (Reduce)、物料重複使用 (Reuse)、資源回收再生 (Recycle)。',
    ],
  },
  'civics/social-justice-welfare': {
    topicSlug: 'social-justice-welfare',
    title: '社會正義、社會福利制度與居住正義實踐',
    subtitle: '羅爾斯正義論 (無知之幕)、社會保險 vs 社會救助、包租代管與租金補貼',
    conceptType: 'flowchart-logic',
    icon: '🤝',
    diagramTitle: '羅爾斯正義論（無知之幕 Veil of Ignorance）與社會安全網三重防線機制圖解',
    diagramDescription: '展示社會保險（勞保/健保）、社會救助（低收入生活扶助）及居住正義（社會住宅、包租代管、租金補貼政策）。',
    formulaBanner: '羅爾斯正義二原則: 1. 平等自由原則 ； 2. 差異原則 (讓社會中最弱勢成員獲得最大利益)',
    visualHighlights: [
      { label: '無知之幕 (Veil of Ignorance)', desc: '在不知道自己出身、財富、天賦地位的前提下制定社會規則，必會優先保障最弱勢者', badge: '哲學正義' },
      { label: '社會保險 (Social Insurance)', desc: '如全民健保、勞工保險，採強制納保、風險分攤與所得重分配機制', badge: '風險分擔' },
      { label: '居住正義政策三箭', desc: '1. 興辦社會住宅 ； 2. 推動包租代管 ； 3. 擴大發放青年與弱勢租金補貼', badge: '居住權利' },
    ],
    keyTakeaways: [
      '社會保險採「使用者付費自繳保費」；社會救助則由「政府公務預算全額支應」，救助弱勢邊緣戶。',
      '居住正義的核心不在於人人買得起豪宅，而在於「人人皆能以合理負擔獲得安全尊嚴之適足居住環境」。',
      '通用設計與社會住宅融合：社會住宅提撥一定比例戶數作為無障礙愛心房，落實全齡共融照顧。',
    ],
  },

  // ==========================================
  // EXTENSIONS (7 Topics)
  // ==========================================
  'extensions/parametric-design-and-ai-assisted-competition': {
    topicSlug: 'parametric-design-and-ai-assisted-competition',
    title: '參數化幾何運算、Grasshopper 演算法與 AI 輔助設計',
    subtitle: 'Rhino + Grasshopper 節點資料流、遺傳演算法拓撲最佳化與 AI 生成式立面',
    conceptType: 'flowchart-logic',
    icon: '💻',
    diagramTitle: 'Grasshopper 節點資料流向圖（點線面幾何運算 → 太陽日照最佳化 → 3D 結構構件生成）',
    diagramDescription: '展示以演算法控制雙曲面屋頂、曲率分析、結構力流拓撲最佳化 (Topology Optimization) 與 AI 空間佈局。',
    formulaBanner: '參數化流程: 輸入參數 (Sliders) → 演算法節點 (Components) → 幾何形體 (Geometry) → 性能反饋 (Ladybug)',
    visualHighlights: [
      { label: '節點資料樹 (Data Trees)', desc: 'Grasshopper 資料結構核心（Path, Branch, Item），管理多維度幾何陣列與關聯運算', badge: '資料結構' },
      { label: '性能驅動設計 (Performance)', desc: '結合 Ladybug 日照輻射分析與 Karamba 結構力學模擬，自動迭代出最省料抗震形態', badge: '性能最佳化' },
      { label: 'AI 生成輔助', desc: '利用 Diffusion 模型進行空間概念快速意象生成，再由參數化模型精確落地為可施工圖面', badge: 'AI 協作' },
    ],
    keyTakeaways: [
      '參數化設計的核心不是畫出複雜形體，而是建立「各幾何元素間的邏輯關聯規則」，調整任一參數全模型即時聯動。',
      '拓撲最佳化 (Topology Optimization) 能在給定受力邊界條件下，剔除無受力多餘材料，生成極輕量有機骨架。',
      '台中歌劇院曲牆、淡江大橋主塔等世界級地標建築均高度依賴參數化運算完成施工定位。',
    ],
  },
  'extensions/portfolio-and-design-discourse': {
    topicSlug: 'portfolio-and-design-discourse',
    title: '建築作品集排版設計、視覺敘事與空間論述',
    subtitle: 'Portfolio 故事線架構、圖面層級 (1:100~1:10)、文字論述與審查委員視角',
    conceptType: 'flowchart-logic',
    icon: '🎨',
    diagramTitle: '專業建築作品集頁面網格版面 (Grid System) 與設計專案故事線 (Storytelling) 展開圖',
    diagramDescription: '展示概念發想 (Site & Concept) → 空間組織 (Plans/Sections) → 構造細部 (Details) → 實體模型照片之嚴謹排版節奏。',
    formulaBanner: '作品集黃金節奏: 1. 基地痛點與概念 (Why) → 2. 空間配置與流線 (What) → 3. 構造與空間氛圍 (How)',
    visualHighlights: [
      { label: '視覺層級 (Visual Hierarchy)', desc: '每頁設定一個「視覺焦點 (Hero Image)」，其餘平立剖圖與分析圖依網格規整排列', badge: '焦點明確' },
      { label: '完整圖面語言', desc: '包含指北針、比例尺、剖切線代號、空間名稱與人體尺度人偶，展現紮實製圖素養', badge: '專業符號' },
      { label: '實體模型攝影', desc: '以柔和單一光源拍攝 1:50~1:100 實體工作模型與空間採光氛圍模型，體現手作空間感', badge: '空間光影' },
    ],
    keyTakeaways: [
      '審查委員翻閱每本作品集平均只有 1~2 分鐘，首頁概念圖與排版整體質感決定第一印象。',
      '作品集切忌只放最終渲染炫光圖，展示推敲過程中的「手繪草圖、模型草模與概念演進」更能體現設計思考深度。',
      '文字論述宜精簡有力，用專業空間詞彙（如場所精神、流線交會、光影序列）取代空洞情緒字眼。',
    ],
  },
  'extensions/spatial-design': {
    topicSlug: 'spatial-design',
    title: '空間機能計畫、人體工學尺度與動線序列組織',
    subtitle: '人體尺度人因工程、泡泡圖 (Bubble Diagram)、空間矩陣與服務/被服務空間',
    conceptType: 'drafting-projection',
    icon: '📐',
    diagramTitle: '人體工學動作淨空尺度（走道 90cm/無障礙迴轉 150cm）與空間機能泡泡圖拓撲關係',
    diagramDescription: '展示人體尺度 (Modulor)、公私領域分區、服務空間 (Servant) 與被服務空間 (Served)、動線無交錯衝突原則。',
    formulaBanner: '人體尺度標準: 走道淨寬 ≥ 90 cm ； 樓梯級高 R ≤ 18cm, 級深 T ≥ 26cm ； 輪椅迴轉直徑 ≥ 150 cm',
    visualHighlights: [
      { label: '泡泡圖 (Bubble Diagram)', desc: '在設計初期以圓圈大小代表空間面積，連線粗細代表關聯強度，推敲最佳配置', badge: '概念分區' },
      { label: '動線分離原則', desc: '主要公眾動線、後勤服務動線、無障礙動線與緊急避難動線清晰分流不交錯', badge: '動線流暢' },
      { label: '路康空間哲學 (Louis Kahn)', desc: '劃分「被服務空間 (Served Space, 廳堂/展廳)」與「服務空間 (Servant Space, 樓梯/管道間)」', badge: '空間本質' },
    ],
    keyTakeaways: [
      '樓梯舒適公式：2R + T ≈ 60~63 公分（R 為級高，T 為級深），符合人體抬腿跨步力學節奏。',
      '無障礙輪椅迴轉空間標準：直徑 150 公分以上之圓形淨空，地坪高差不得超過 0.5 公分。',
      '空間設計首重「尺度感 (Scale)」，從私密空間 (2.4m 高) 到公共大廳 (6~10m 挑高) 營造豐富空間情緒序列。',
    ],
  },
  'extensions/construction-methods': {
    topicSlug: 'construction-methods',
    title: '現代營造工法：連續壁、逆打工法與鋼構吊裝',
    subtitle: '地下室擋土開挖 (連續壁/地錨)、逆打工法 (Top-Down)、鋼骨吊裝校正與灌漿',
    conceptType: 'structural-stress',
    icon: '🏗️',
    diagramTitle: '都會區地下深開挖「逆打工法 (Top-Down Construction)」地上地下同步施工剖面圖',
    diagramDescription: '展示打入鋼骨基柱後，先行施作一樓樓板作為支撐，地上結構向上蓋、地下結構向下開挖，大幅縮短工期。',
    formulaBanner: '工法比較: 順打工法 (由下而上，安全標準) vs 逆打工法 (由一樓同時向上下推進，省工期防變形)',
    visualHighlights: [
      { label: '連續壁 (Diaphragm Wall)', desc: '以抓斗開挖深槽、注入皂土泥漿護壁、吊放鋼筋籠並澆置水中混凝土，具超強擋土止水能力', badge: '深開挖擋土' },
      { label: '逆打工法 (Top-Down)', desc: '利用一樓 RC 樓板作為強大水平支撐，有效抑制周邊鄰房地層下陷，地上地下同時施工', badge: '縮短工期' },
      { label: '鋼骨吊裝校正', desc: '以經緯儀雙向監控鋼柱垂直度 (垂直偏差 ≤ 1/1000)，安裝高張力螺栓並分初鎖與本鎖緊固', badge: '鋼結構精度' },
    ],
    keyTakeaways: [
      '都會區深開挖最嚴重的公害為「周邊地層下陷與鄰房龜裂」，連續壁剛度大、止水性好，為最可靠之擋土設施。',
      '逆打工法最大優勢在於能大幅縮短總工期，並以永久樓板代替臨時鋼支撐，結構變形控制極佳。',
      '預鑄節塊工法 (Precast Segmental Method)：在工廠標準化製作預鑄梁柱節塊，運至現場吊裝拼接，大幅提升施工品質與速度。',
    ],
  },
  'extensions/cad-bim': {
    topicSlug: 'cad-bim',
    title: '建築資訊模型 (BIM)、Revit 協同設計與碰撞檢測',
    subtitle: 'BIM 3D~7D 維度、LOD 100~500 細緻度、Navisworks 碰撞檢測與工程算量',
    conceptType: 'flowchart-logic',
    icon: '🏢',
    diagramTitle: 'BIM 建築、結構、機電 (MEP) 三維模型整合與 Navisworks 空間衝突碰撞檢測圖解',
    diagramDescription: '展示梁穿梁、風管撞結構梁、消防管撞門框之即時紅藍干涉檢測，消除工地現場打鑿重做風險。',
    formulaBanner: 'BIM 維度: 3D (空間幾何) / 4D (時間排程) / 5D (造價預算) / 6D (綠能永續) / 7D (設施維運 FM)',
    visualHighlights: [
      { label: 'LOD 細緻度標準', desc: 'LOD 100 (概念體量) → LOD 200 (概略構件) → LOD 300 (施工精確圖) → LOD 400 (加工製造組裝)', badge: 'LOD 規範' },
      { label: '硬碰撞 vs 軟碰撞', desc: '硬碰撞（實體幾何干涉如管穿梁）；軟碰撞（間隙不足未留維修操作空間或保溫層厚度）', badge: '衝突分析' },
      { label: 'BIM 自動化算量 (QTO)', desc: '模型構件參數直接聯動混凝土體積、模板面積與鋼筋噸數，消除傳統手工算量誤差', badge: '精準預算' },
    ],
    keyTakeaways: [
      'BIM (Building Information Modeling) 不只是 3D 繪圖軟體，而是包含所有幾何與物理屬性參數的「數位孿生資料庫」。',
      '碰撞檢測 (Clash Detection) 能在施工前於電腦模型中找出 99% 的管線衝突，避免工地現場敲打打鑿浪費成本。',
      'IFC (Industry Foundation Classes) 為國際通用之開放 BIM 檔案交換標準，實現跨軟體無縫協同作業。',
    ],
  },
  'extensions/portfolio-models': {
    topicSlug: 'portfolio-models',
    title: '實體建築模型製作材料、比例尺度與雷雕 3D 列印',
    subtitle: '風扣板/木晶板/ABS/椴木板、1:100~1:20 模型工法與數位雷射切割技術',
    conceptType: 'drafting-projection',
    icon: '✂️',
    diagramTitle: '實體模型材料力學特性（椴木/灰卡/壓克力/風扣）與 45° 斜角搭接無縫接合剖面圖',
    diagramDescription: '展示厚度 1mm~5mm 板材雷雕切縫補償 (Kerf Compensation)、模型膠水選用（UHU/壓克力二氯甲烷）與等高線地形層疊。',
    formulaBanner: '模型比例轉換: 1:100 模型中 1 公分 = 現實 1 公尺 ； 1:200 模型中 1 公分 = 現實 2 公尺',
    visualHighlights: [
      { label: '45° 斜切接角 (Miter Joint)', desc: '板材邊緣以 45° 專用切刀斜切，組裝時不露板材截面夾心，模型轉角俐落精準', badge: '精緻工藝' },
      { label: '等高線地形模型', desc: '依基地等高線間距選擇對應厚度卡紙（如 1m 間距在 1:100 用 10mm 板、在 1:500 用 2mm 板）', badge: '地形層疊' },
      { label: '雷射切割切縫補償', desc: '雷射光束本身具約 0.15mm 直徑 (Kerf)，精密卡榫模型繪圖時需向外偏移補償', badge: '數位製造' },
    ],
    keyTakeaways: [
      '概念模型 (Study Model) 偏好易加工材料（灰卡、黃銅絲、黏土），重在快速推敲空間體量與採光。',
      '正評大模型 (Final Presentation Model) 重在構造真實性與材料質感表達（椴木板、磨砂壓克力、微縮人偶）。',
      '模型黏著劑禁忌：保麗龍/風扣板絕對不可使用強力膠或瞬間膠（含溶劑會將保麗龍芯融化蝕空），應使用專用保麗龍膠或 UHU 膠。',
    ],
  },
  'extensions/certification': {
    topicSlug: 'certification',
    title: '建築與營建專業技術士證照檢定地圖',
    subtitle: '建築製圖應用 (手繪/電繪)、測量 (地籍/工程)、營造工程管理與勞工安衛證照',
    conceptType: 'flowchart-logic',
    icon: '📜',
    diagramTitle: '技職學生從在學技術士 (乙/丙級) 到國家專技高考 (建築師/技師) 完整證照晉升階梯',
    diagramDescription: '展示丙級 (基礎門檻) → 乙級 (技優甄審加分 15%) → 甲級/專技高考 (執業簽證大師) 之法定權責矩陣。',
    formulaBanner: '升學就業利器: 乙級技術士證 (統測甄選入學加分 15%) ； 專技高考及格 (取得國家建築師執照)',
    visualHighlights: [
      { label: '建築製圖應用 (乙/丙級)', desc: '丙級（手繪/電腦繪圖二選一）；乙級（手繪施工圖 + CAD 2D/3D 上機實作，甄試加分 15%）', badge: '高中職主力' },
      { label: '工程測量 (乙/丙級)', desc: '水準測量、經緯儀閉合導線、全測站定點放樣與計算，土木營造現場必備能力', badge: '現場必備' },
      { label: '營造工程管理 (乙級)', desc: '取得乙級證照並受訓及格，可依法擔任營造廠「專任工程人員/工地主任 (Site Manager)」', badge: '工地主任' },
    ],
    keyTakeaways: [
      '高職階段取得「建築製圖應用乙級」或「工程測量乙級」，於四技二專甄選入學享有總分加分 15% 之重大升學優勢。',
      '營造工程管理乙級是營造現場最有實質含金量的證照之一，畢業符合年資即可換發內政部工地主任執業證。',
      '終極專業頂峰：專技高考建築師、結構工程技師、土木工程技師，享有國家法定專屬設計監造與結構安全簽證權。',
    ],
  },
  // ==========================================
  // CHEMISTRY EXPANDED (1 Topic)
  // ==========================================
  'chemistry/matter-composition': {
    topicSlug: 'matter-composition',
    title: '物質的組成與分類、原子結構與建材週期律',
    subtitle: '純物質/混合物、電子組態、八隅體法則與耐候金屬化學週期',
    conceptType: 'comparative-matrix',
    icon: '⚛️',
    diagramTitle: '物質分類樹狀架構（元素/化合物 vs 均相/非均相混合物）與元素週期表原子結構矩陣',
    diagramDescription: '展示純物質與混合物物理化學區隔，對照過渡金屬（如鐵、鉻、鎳）電子組態與耐候不銹鋼防蝕化學反應。',
    formulaBanner: '化學鍵原理: 離子鍵 (電負度差 ΔEN > 2.0) ； 共價鍵 (共用電子對) ； 金屬鍵 (自由電子海)',
    visualHighlights: [
      { label: '純物質 vs 混合物', desc: '純物質（元素、化合物）具固定熔沸點；混合物（如水泥砂漿、合金）無固定熔沸點', badge: '物質分類基礎' },
      { label: '原子結構與價電子', desc: '質子數決定原子序，最外層價電子數決定族群與化學活性，滿足八隅體趨於穩定', badge: '週期律本質' },
      { label: '建材防蝕金屬配對', desc: '不銹鋼藉由鉻 (Cr ≥ 10.5%) 在表面生成緻密 Cr₂O₃ 鈍化保護膜，阻止內部鐵原子氧化鏽蝕', badge: '建築防腐化學' },
    ],
    keyTakeaways: [
      '合金（如不銹鋼、黃銅）本質上是固態均相溶液（固溶體），為混合物而非化合物，物理分離法不可分但無固定熔點。',
      '元素週期表同族元素具有相同之最外層價電子數，故表現出高度相似之化學反應活性與化合價。',
      '陰極防蝕法（犧牲陽極法）：利用活潑金屬（如鋅 Zn）附著於鋼鐵表面（如熱浸鍍鋅鋼板），優先氧化以保護鐵不受腐蝕。',
    ],
  },
  // ==========================================
  // CHINESE EXPANDED (5 Topics)
  // ==========================================
  'chinese/modern-literature': {
    topicSlug: 'modern-literature',
    title: '現代文學流派演進、作家風格與空間書寫',
    subtitle: '現代詩三大流派、台灣鄉土文學論戰、眷村與都市建築地景意象',
    conceptType: 'comparative-matrix',
    icon: '📖',
    diagramTitle: '台灣現代文學發展光譜（日治鄉土→戰後現代主義→鄉土文學論戰→當代多元都市空間）',
    diagramDescription: '展示紀弦現代派（橫的移植）、藍星詩社（縱的繼承）、創世紀（超現實）之文學主張，及黃春明、楊逵之城鄉空間關懷。',
    formulaBanner: '現代詩三大詩社: 現代派 (橫的移植、知性) ； 藍星詩社 (縱的繼承、抒情) ； 創世紀 (超現實主義、前衛)',
    visualHighlights: [
      { label: '現代派 (紀弦)', desc: '主張「橫的移植」引進西方現代主義，以知性排斥盲目抒情，確立現代詩新紀元', badge: '現代派' },
      { label: '藍星詩社 (余光中/覃子豪)', desc: '強調「縱的繼承」，融合古典中國詩詞意象與現代節奏，重視音樂美感與文化鄉愁', badge: '藍星詩社' },
      { label: '鄉土文學與空間', desc: '聚焦農村土地、老街老屋與底層勞動者生活，反映工業化都市擴張帶來的空間異化與認同', badge: '空間社會學' },
    ],
    keyTakeaways: [
      '余光中詩風融合古典與現代，代表作《鄉愁》以郵票、船票、墳墓、海峽四重空間象徵情感遞進。',
      '日治時期台灣新文學之父賴和，小說《一桿「稱仔」》深刻揭露殖民統治度量衡制度對弱勢農民之剝削與壓迫。',
      '現代散文中「空間書寫」常作為記憶情感之容器，如林文月寫眷村老厝、齊邦媛寫巨流河兩岸流離，建築空間承載世代流轉。',
    ],
  },
  'chinese/linguistics': {
    topicSlug: 'linguistics',
    title: '語言文字學、句法結構與建築成語考辨',
    subtitle: '六書構字法理、詞類活用、主謂賓句型與常見語病邏輯診斷',
    conceptType: 'flowchart-logic',
    icon: '📝',
    diagramTitle: '漢語句法核心架構（主語-謂語-賓語）與常見六大語病（成分殘缺/搭配不當/歧義矛盾）診斷樹',
    diagramDescription: '展示名詞活用為動詞、賓語前置倒裝句結構，以及公文契約與論說文中邏輯語病之三階快速快篩法則。',
    formulaBanner: '句型基本結構: [定語] 主語 + [狀語] 謂語 + [定語] 賓語 <補語> ； 語病快篩: 抓幹抽枝查搭配',
    visualHighlights: [
      { label: '詞類活用 (Functional Shift)', desc: '名詞作動詞（如「左右皆『肘』之」之肘擊、「『衣』錦還鄉」之穿著），古漢語常見靈活轉品', badge: '活用法則' },
      { label: '賓語前置倒裝 (Inversion)', desc: '否定句或疑問句代詞作賓語前置（如「莫己若」即「莫若己」、「何陋之有」即「有何陋」）', badge: '倒裝句型' },
      { label: '常見語病診斷 (Error Analysis)', desc: '搭配不當（如「提高水準與觀點」動賓不合）、前後不一（「能否成功取決於努力」兩面失衡）', badge: '邏輯語病' },
    ],
    keyTakeaways: [
      '古漢語賓語前置三大鐵則：疑問代詞作賓語前置（「沛公安在」）；否定句代詞作賓語前置（「古之人不余欺也」）；以「之/是」提賓（「唯利是圖」）。',
      '成語考辨忌望文生義：「明日黃花」指過時事物而非未來；「差強人意」指大致令人滿意而非非常差勁；「鼎力相助」為敬辭請人幫忙，不可言自己鼎力相助。',
      '語病修改原則：不改變原意，以「增、刪、調、換」四法處理，先抓句子主幹（主謂賓），再檢視修飾成分（定狀補）是否冗贅或矛盾。',
    ],
  },
  'chinese/reading-comprehension': {
    topicSlug: 'reading-comprehension',
    title: '統測閱讀素養與跨領域雙文本分析',
    subtitle: '訊息擷取、統整解釋、反思評價三層次與非連續性圖表文本互證',
    conceptType: 'flowchart-logic',
    icon: '🔍',
    diagramTitle: 'PISA 國際閱讀素養三層次評量模型（定位檢索→脈絡整合→反思批判）與工程跨文本分析路徑',
    diagramDescription: '展示統測國文素養題型如何結合建築空間評析、歷史文獻與統計圖表，引導學生透過交叉比對鎖定文本核心論點。',
    formulaBanner: '素養解題三步驟: 1. 審題眼鎖定關鍵詞 → 2. 文本定位脈絡線索 → 3. 比對干擾選項邏輯漏洞',
    visualHighlights: [
      { label: '層次一：擷取訊息 (Access)', desc: '直接在文本中定位事實資訊、數據、人名或時間，重在精準定位無偏漏', badge: '事實擷取' },
      { label: '層次二：統整解釋 (Integrate)', desc: '歸納段落主旨、推敲作者言外之意或隱喻象徵，串聯多段落訊息形成因果鏈', badge: '邏輯整合' },
      { label: '層次三：省思評鑑 (Reflect)', desc: '跳脫文本站在客觀視角批判作者論證效力、文體風格，或將觀點遷移應用於現實情境', badge: '批判思考' },
    ],
    keyTakeaways: [
      '素養閱讀做題口訣：先看題幹後讀文章，劃記題幹關鍵定位詞，帶著問題回到文本精確「掃描 (Scanning)」對應段落。',
      '非連續性文本（圖表、地圖、契約規章）解題關鍵在於「圖文互證」，注意圖表標題、座標軸單位、圖例與極端數據拐點。',
      '選項干擾陷阱特徵：過度推論（文本未提及卻宣稱必然）、偷換概念（更換主語或條件）、以偏概全（用單一特例推導普遍結論）。',
    ],
  },
  'chinese/writing-expression': {
    topicSlug: 'writing-expression',
    title: '統測寫作引導、空間論述與思維昇華',
    subtitle: '審題立意、起承轉合結構佈局、空間美學論述與修辭鍊字法',
    conceptType: 'flowchart-logic',
    icon: '✒️',
    diagramTitle: '統測高分作文思維建構模型（審題立意→空間佈局→經驗鏈結→思辨昇華）黃金四段論',
    diagramDescription: '展示如何將建築空間視角（如老屋修復、光影虛實、動線流動）融入作文寫作，從個人微觀感性昇華至社會人文關懷。',
    formulaBanner: '寫作四部曲: 起 (開門見山定基調) ； 承 (具體鋪陳敘空間) ； 轉 (哲思反轉剖矛盾) ； 合 (首尾呼應照宏旨)',
    visualHighlights: [
      { label: '審題與立意 (Theme & Vision)', desc: '抓準題目核心限制詞與隱含動態發展，拒絕千篇一律的八股模板，確立獨特人文視角', badge: '文章靈魂' },
      { label: '空間感性鋪敘 (Spatial Imagery)', desc: '調動視覺、觸覺、聽覺等多重感官描寫空間質地（如紅磚粗獷、鋼構冷冽、天窗灑落之光芒）', badge: '畫面營造' },
      { label: '哲理思辨轉折 (Philosophical Shift)', desc: '從具體物象昇華至人生處世哲學或文化永續議題，展示高階批判思考與同理胸襟', badge: '境界昇華' },
    ],
    keyTakeaways: [
      '審題三問：題目是什麼？為什麼會出這個題目？我有哪些獨特生命/專業經驗可以與其共振？',
      '高分突破點在於「細節描寫」：少用抽象形容詞（如「很美麗」、「很難過」），多用動態名詞與精準動詞呈現畫面。',
      '文章結尾切忌流於空洞口號呼籲，應首尾呼應並留有餘味，讓文字如建築落成般結構嚴密而意境悠遠。',
    ],
  },
  'chinese/cultural-knowledge': {
    topicSlug: 'cultural-knowledge',
    title: '國學常識、文化規制與古代建築禮制',
    subtitle: '經史子集四庫分類、干支紀年、傳統對聯平仄與合院堂構空間秩序',
    conceptType: 'comparative-matrix',
    icon: '🏛️',
    diagramTitle: '國學四庫全書分類脈絡與傳統合院建築禮制（正身護龍、左尊右卑、中軸對稱）倫理空間圖解',
    diagramDescription: '展示傳統漢人合院建築（一條龍、三合院、四合院）如何具象化儒家長幼有序之禮教秩序，對照四庫全書類目劃分。',
    formulaBanner: '對聯格律: 上聯末字「仄聲」(三四聲) ； 下聯末字「平聲」(一二聲) ； 空間倫理: 左尊右卑、長幼居室有序',
    visualHighlights: [
      { label: '四庫全書分類 (Four Branches)', desc: '經（儒家十三經）、史（正史編年）、子（諸子百家科技農醫）、集（文學作品楚辭詩詞）', badge: '國學架構' },
      { label: '對聯平仄粘對 (Couplet Rules)', desc: '字數相等、詞性相對、平仄相反，傳統面向大門時上聯貼於右側（人面向門之右手邊），下聯貼於左側', badge: '門聯貼法' },
      { label: '合院建築禮制空間', desc: '大正身中央為公媽廳（神明廳），大房住左大杉（左尊）、二房住右小杉，護龍依房序遞排', badge: '空間秩序' },
    ],
    keyTakeaways: [
      '四庫分類陷阱辨析：《論語》《孟子》《爾雅》歸入「經部」；《史記》《資治通鑑》歸入「史部」；《荀子》《莊子》《天工開物》歸入「子部」；《陶淵明集》《李太白全集》歸入「集部」。',
      '干支紀年推算法：天干 10 數、地支 12 數，以 60 年為一甲子循環；天干對應年份尾數（如甲 4、乙 5、丙 6、丁 7、戊 8、己 9、庚 0、辛 1、壬 2、癸 3）。',
      '傳統建築木構大木作名詞：「樑架」承載屋面重力，「斗栱」承接挑簷並具備抗震緩衝彈性功能，「雀替」強化梁柱交接直角抗變形。',
    ],
  },
  // ==========================================
  // CIVICS COMPLETE (6 Topics)
  // ==========================================
  'civics/citizenship-community': {
    topicSlug: 'citizenship-community',
    title: '公民身分、公共參與與社區總體營造',
    subtitle: '公民權利演進、民主審議、社區營造與都市更新公眾參與',
    conceptType: 'flowchart-logic',
    icon: '👥',
    diagramTitle: '公民參與階梯理論 (Ladder of Citizen Participation) 與社區營造公私協力三螺旋模型',
    diagramDescription: '展示非參與（操弄）→ 象徵性參與（告知/諮詢）→ 實質公民權力（夥伴/公民掌控）之階梯進程，連結空間規劃公民審議。',
    formulaBanner: '公民權演進: 18世紀民權 (人身自由) → 19世紀參政權 (投票罷免) → 20世紀社會權 (生存勞動福祉)',
    visualHighlights: [
      { label: '公民參與階梯 (Arnstein)', desc: '自操弄告知（低階）至參與式預算與夥伴關係（高階），讓社區住民實質主導生活空間改造', badge: '參與階梯' },
      { label: '社區總體營造 (Community)', desc: '「造人、造景、造產」，結合在地文史、空間紋理與地方創生，凝聚社區共同體意識', badge: '地方創生' },
      { label: '都市更新公聽與審議', desc: '權利變換、容積獎勵與聽證程序，依法保障原住戶居住權，平衡公共利益與私人產權', badge: '空間正義' },
    ],
    keyTakeaways: [
      '公民參與並非單純的公聽會出席打卡，真正的實質參與必須具備充分知情權、討論時間與對決策結果之約束力。',
      '社區總體營造的核心在於由下而上 (Bottom-up) 的草根自主發起，而非官僚自上而下 (Top-down) 的硬體工程補助。',
      '審議民主 (Deliberative Democracy) 強調公民在獲得完整資訊與中立專家諮詢後，透過理性論辯尋求公共利益最大共識。',
    ],
  },
  'civics/law-life': {
    topicSlug: 'law-life',
    title: '法律位階、憲法權利保障與建築法制',
    subtitle: '憲法-法律-命令位階體系、比例原則與都市計畫建築執照法治',
    conceptType: 'comparative-matrix',
    icon: '⚖️',
    diagramTitle: '凱爾森法規範位階金字塔與行政行為比例原則（適當性/必要性/狹義比例性）違憲審查模型',
    diagramDescription: '展示憲法最高性、法律保留原則，對照建築法、建築技術規則位階，以及政府限制人民財產權時的憲法正當法律程序。',
    formulaBanner: '行政法比例原則: 1. 適當性 (目的正當手段有效) → 2. 必要性 (最小侵害) → 3. 衡量性 (利益大於損害)',
    visualHighlights: [
      { label: '法律位階原則 (Hierarchy)', desc: '憲法具有最高效力；法律不得牴觸憲法；法規命令不得牴觸憲法與法律（無效判定）', badge: '憲法優位' },
      { label: '法律保留原則 (Legality)', desc: '涉及限制人民自由權利（如建蔽率容積率限制、違建強制拆除）必須有立法院法律明文授權', badge: '人權保障' },
      { label: '行政救濟程序 (Remedy)', desc: '對建築主管機關處分不服：向原處分機關或上級機關提「訴願」→ 提起行政法院「行政訴訟」', badge: '救濟途徑' },
    ],
    keyTakeaways: [
      '比例原則是公法學帝王條款：手段必須有助於目的達成（適當性）、在所有有效手段中選擇損害最小者（必要性）、所造成的損害與追求之公益不可顯失均衡（衡量性）。',
      '都市計畫土地使用分區管制（如住一、商三）限制土地所有權人的建築開發強度，必須符合憲法第 23 條之公益必要性與法律保留原則。',
      '違章建築強制拆除：地方工務局開具之違建認定通知書屬於「行政處分」，人民若不服應先依法提起訴願，不得於現場以暴力阻撓公務執行。',
    ],
  },
  'civics/economy-sustainability': {
    topicSlug: 'economy-sustainability',
    title: '市場機制、外部效果與循環建築經濟',
    subtitle: '市場供需均衡、外部成本內部化（碳費/容積獎勵）與綠色金融 ESG',
    conceptType: 'environmental-physics',
    icon: '📈',
    diagramTitle: '市場供需曲線、負外部性（施工污染/碳排）市場失靈與皮古稅 (Pigouvian Tax) 矯正圖解',
    diagramDescription: '展示市場價格機制如何決定資源配置，以及私人成本未計入環境破壞時引發之社會福祉無謂損失 (Deadweight Loss)。',
    formulaBanner: '外部成本內部化: 社會邊際成本 SMC = 私人邊際成本 PMC + 外部邊際成本 EMC ； 碳費徵收補足差額',
    visualHighlights: [
      { label: '市場失靈 (Market Failure)', desc: '工廠排碳、營建工地揚塵噪音造成周邊外部成本，使市場均衡產量大於社會最適產量', badge: '負外部性' },
      { label: '皮古稅與碳費 (Carbon Fee)', desc: '對高排碳建材（水泥、鋼鐵）課徵碳費，迫使企業將環境成本計入售價，導向綠色研發', badge: '外部性內部化' },
      { label: '公共財與搭便車 (Free Rider)', desc: '公共財具非排他性與非敵對性（如都市綠地公園），市場無法自發提供，需政府公共投資', badge: '公共財特質' },
    ],
    keyTakeaways: [
      '外部性內部化手段包括：租稅補貼法（皮古稅、綠建築容積獎勵）、財產權界定法（寇斯定理 Coase Theorem、碳排放權交易）。',
      '機會成本 (Opportunity Cost)：在資源有限情況下做出選擇時，所放棄的其他選擇中價值最高者。',
      '循環經濟 (Circular Economy) 在建築領域之實踐：推行建築履歷、可拆卸性設計 (DfD) 與建材銀行，將拆除廢棄物轉化為再生骨材資源。',
    ],
  },
  'civics/society-culture': {
    topicSlug: 'society-culture',
    title: '社會階層化、文化多樣性與都市空間正義',
    subtitle: '文化資本、空間隔離、通用設計 (Universal Design) 與文化平權',
    conceptType: 'comparative-matrix',
    icon: '🤝',
    diagramTitle: '布赫迪厄四大資本理論（經濟/社會/文化/象徵資本）與都市空間階級隔離映射模型',
    diagramDescription: '展示昂貴房價與都市仕紳化 (Gentrification) 如何造成弱勢群體被迫邊緣化遷徙，並倡議社會住宅與通用無障礙空間正義。',
    formulaBanner: '空間正義原則: 空間分配平等 (人人享有尊嚴居住權) ； 通用設計 7 原則 (不因年齡能力受阻)',
    visualHighlights: [
      { label: '都市仕紳化 (Gentrification)', desc: '老舊城區更新後物價地價飆漲，原始低收入居民無力負擔被迫遷出，導致文化紋理斷裂', badge: '仕紳化挑戰' },
      { label: '通用設計 (Universal Design)', desc: '「公平使用、彈性操作、簡易直覺、容錯容差」，無障礙斜坡與電梯讓所有世代平權共享', badge: '友善平權' },
      { label: '社會住宅政策 (Social Housing)', desc: '政府提供只租不售住宅並混居配置，落實居住正義，打破階級標籤與居住空間隔離', badge: '居住人權' },
    ],
    keyTakeaways: [
      '文化多樣性是現代文明核心資產，全球在地化 (Glocalization) 鼓勵在吸納國際前衛建築理念時，深刻植根本土文化特色。',
      '都市空間正義 (Spatial Justice) 追求的是每個人無論身心條件與貧富，均享有公平使用都市公共設施與高品質生活環境之權利。',
      '通用設計並非僅為身心障礙者設計，而是讓嬰兒推車、銀髮族、孕婦、一般大眾在任何空間中皆能無障礙、有尊嚴地自主生活。',
    ],
  },
  'civics/labor-ethics': {
    topicSlug: 'labor-ethics',
    title: '勞動權益、工程專業倫理與工地安衛防衛',
    subtitle: '勞基法勞動三權、職安法雇主責任、工程師倫理守則與吹哨者保護',
    conceptType: 'flowchart-logic',
    icon: '⛑️',
    diagramTitle: '職業安全衛生風險控制五層級金字塔（消除→替代→工程控制→管理控制→個人防護 PPE）',
    diagramDescription: '展示營建施工墜落、坍塌、感電重大職災防衛，對照工程師倫理「將公眾安全、健康與福祉置於首位」之決策路徑。',
    formulaBanner: '勞動三權: 團結權 (組工會) / 協商權 (團體協約) / 爭議權 (合法罷工) ； 工程倫理第一條: 公眾安全至上',
    visualHighlights: [
      { label: '職安控制五層級 (Hierarchy)', desc: '優先採用消除與工程防護（如安全護欄、安全防護網），個人防護具 (PPE 安全帽/帶) 為最後底線', badge: '防護金字塔' },
      { label: '工程專業倫理守則', desc: '當業主要求偷工減料或隱匿結構重大瑕疵時，工程師有法定通報責任，公眾生命高於業主合約', badge: '倫理底線' },
      { label: '吹哨者保護 (Whistleblower)', desc: '揭露工地重大工安弊端與違法偷工減料行為時，法律提供身分保密與免受不當解僱懲處保護', badge: '良心保護' },
    ],
    keyTakeaways: [
      '職業安全衛生法嚴格規定：在高度 2 公尺以上之高處作業處所，雇主必須設置安全防墜設備（護欄、安全網或安全母索），否則構成重大違規。',
      '勞基法保障基本權益：正常工時每日不超過 8 小時、每週不超過 40 小時，例假與休息日出勤必須依法加成發給加班費。',
      '工程專業倫理與利益衝突：工程師絕不可收受材料供應商之回扣或不當款待，簽證前必須親自查驗設計圖說與計算書之正確性。',
    ],
  },
  'civics/environment-policy': {
    topicSlug: 'environment-policy',
    title: '環境治理、氣候變遷因應法與 2050 淨零轉型',
    subtitle: '氣候法碳定價、環境影響評估法 (EIA)、建築能效標示 (BERS) 與永續政策',
    conceptType: 'environmental-physics',
    icon: '🌍',
    diagramTitle: '台灣 2050 淨零排放四大轉型策略（能源/產業/生活/社會）與綠建築九大指標評估體系 (EEWH)',
    diagramDescription: '展示台灣氣候變遷因應法碳費機制、環境影響評估三階段審查，對照公有與民間新建建築分階段強制導入建築能效規範。',
    formulaBanner: '淨零碳排定義: 溫室氣體人為排放量 - 碳匯移除量 = 0 ； 建築能效標示: 1~7 級與近零碳建築 1+ 級',
    visualHighlights: [
      { label: '環境影響評估 (EIA)', desc: '在大型建築或開發案動工前，科學預測並公開評估對生態、水文、空氣品質之影響，採預防原則', badge: '預防原則' },
      { label: '建築能效標示 (BERS)', desc: '評定外殼節能、空調效率與照明功耗，最高等級為「近零碳建築 (Nearly Zero-Carbon Building 1+)」', badge: '能效標章' },
      { label: '氣候變遷因應法', desc: '明定 2050 淨零排放法定國家目標，設立氣候基金，開徵碳費並推動跨部會溫室氣體減量方案', badge: '法定目標' },
    ],
    keyTakeaways: [
      '台灣綠建築評估系統 EEWH 四大範疇九大指標：生態（生物多樣性、綠化量、基地保水）、節能（日常節能）、減廢（CO2減量、廢棄物減量）、健康（室內環境、水資源、污水垃圾）。',
      '環境影響評估法之核心精神為「預防原則 (Precautionary Principle)」，旨在未造成無可挽回之生態浩劫前採取源頭避讓與緩解措施。',
      '自 2024 年起，內政部推動公有新建建築物率先取得建築能效 1 級或近零碳建築 (1+)，帶動民間不動產市場全面朝向低碳循環轉型。',
    ],
  },
};

