export interface InfographicAnnotation {
  label: string;
  desc: string;
  x?: number;
  y?: number;
  badge?: string;
}

export interface TopicInfographicItem {
  topicSlug: string;
  title: string;
  subtitle: string;
  conceptType: 
    | 'equilibrium-vector' 
    | 'structural-stress' 
    | 'material-reaction' 
    | 'survey-geometry' 
    | 'drafting-projection' 
    | 'flowchart-logic' 
    | 'comparative-matrix' 
    | 'environmental-physics';
  icon: string;
  diagramTitle: string;
  diagramDescription: string;
  formulaBanner?: string;
  visualHighlights: InfographicAnnotation[];
  keyTakeaways: string[];
}

// 13 Subjects x 120 Topics Complete Infographics Registry
export const topicInfographicsMap: Record<string, TopicInfographicItem> = {
  // ==========================================
  // 1. MECHANICS (13 Topics)
  // ==========================================
  'mechanics/structural-failures': {
    topicSlug: 'structural-failures',
    title: '結構破壞機制與安全裕度防衛',
    subtitle: '極限承載力 (Pu) 與容許應力法 (ASD / LRFD) 破壞路徑圖解',
    conceptType: 'structural-stress',
    icon: '💥',
    diagramTitle: '結構應力超載與脆性/延性破壞分岔模型',
    diagramDescription: '展示結構受荷時，從彈性變形 → 塑性降伏 → 頸縮破壞的力學能量吸收路徑，對比脆性突潰與延性預警。',
    formulaBanner: '安全係數 FS = 極限應力 σ_ult / 容許應力 σ_allow ≥ 1.5 ~ 3.0',
    visualHighlights: [
      { label: '彈性階段 (Elastic)', desc: '卸載後完全恢復，符合虎克定律 σ = E·ε', badge: '安全工作區' },
      { label: '塑性降伏 (Yielding)', desc: '材料開始永久變形，大量吸收地震能量', badge: '能量緩衝區' },
      { label: '頸縮破壞 (Rupture)', desc: '應力集中處截面驟減，達到破壞極限 Pu', badge: '致命破壞點' },
    ],
    keyTakeaways: [
      '延性破壞（如低碳鋼）破壞前有巨大變形預警；脆性破壞（如無筋混凝土）瞬間崩塌無預警。',
      '安全係數 FS 必須大於 1.0，工程上通常依載重不確定性取 1.5 至 3.0。',
      '強柱弱梁 (Strong Column Weak Beam) 設計能迫使塑性鉸產生在梁端，避免建築物瞬間倒塌。',
    ],
  },
  'mechanics/parallel-force-systems': {
    topicSlug: 'parallel-force-systems',
    title: '平面平行力系之合成與等效力偶',
    subtitle: '合力大小 R = ΣF 與合力作用線位置 Varignon 定理',
    conceptType: 'equilibrium-vector',
    icon: '⚖️',
    diagramTitle: '平行分力分佈與單一等效合力力臂幾何圖',
    diagramDescription: '將一組同向或反向之平行力，透過代數和求出合力 R，並利用合力矩等於各分力矩之和（瓦里農定理）精確定位作用線。',
    formulaBanner: '合力 R = ΣF_y ； 合力位置 x̄ = Σ(F_i · x_i) / R (瓦里農定理)',
    visualHighlights: [
      { label: '同向平行力', desc: '合力大小等於各力之和，作用線必在各力之間', badge: '重心內側' },
      { label: '反向平行力', desc: '合力大小等於較大力減較小力，作用線在較大力外側', badge: '偏心外側' },
      { label: '純力偶 (Couple)', desc: '大小相等、方向相反但不在同一直線上，合力為 0 但力偶矩 M = F·d ≠ 0', badge: '純旋轉效應' },
    ],
    keyTakeaways: [
      '瓦里農定理 (Varignon\'s Theorem)：合力對任意點之矩，恆等於各分力對同點之矩代數和。',
      '力偶可以在平面內自由平移而不改變其對物體造成的旋轉效應。',
      '若平行力系 ΣF = 0 且 ΣM = 0，則力系達成完全靜力平衡。',
    ],
  },
  'mechanics/nonconcurrent-force-systems': {
    topicSlug: 'nonconcurrent-force-systems',
    title: '共面非共點非平行力系平衡',
    subtitle: '三平衡方程式 ΣFx=0, ΣFy=0, ΣM=0 解三大未知支承反力',
    conceptType: 'equilibrium-vector',
    icon: '📐',
    diagramTitle: '任意二維幾何構件受外力與支承反力受力自由體圖 (FBD)',
    diagramDescription: '解除支承約束（滾支承 1 反力、鉸支承 2 反力、固端 3 反力），繪製完整外力與反力向量多邊形閉合圖。',
    formulaBanner: '靜力平衡三大公理: ΣF_x = 0 , ΣF_y = 0 , ΣM_O = 0',
    visualHighlights: [
      { label: '滾支承 (Roller)', desc: '限制垂直位移，提供 1 個垂直反力 (Ry)', badge: '1 未知數' },
      { label: '鉸支承 (Hinged Pin)', desc: '限制水平與垂直位移，提供 2 個反力 (Rx, Ry)', badge: '2 未知數' },
      { label: '固定端 (Fixed Support)', desc: '限制水平、垂直與轉動，提供 3 個反力 (Rx, Ry, M)', badge: '3 未知數' },
    ],
    keyTakeaways: [
      '解非共點力系時，取「未知力交會最多之點」作為力矩中心 (ΣM=0)，可直接消去最多未知數。',
      '二力構件 (Two-Force Member)：兩端受力之桿件，其反力方向必沿著兩端點之連線方向。',
      '靜定結構具備恰好 3 個獨立未知反力，可由 3 個平衡方程式完全求解。',
    ],
  },
  'mechanics/shear-properties': {
    topicSlug: 'shear-properties',
    title: '剪切應力、剪切應變與材料剪切模數',
    subtitle: '橫向剪切力 V、剪應力 τ = V/A 與虎克剪切定律 τ = G·γ',
    conceptType: 'structural-stress',
    icon: '✂️',
    diagramTitle: '矩形微元素純剪切變形與角度偏折 γ 幾何圖譜',
    diagramDescription: '正交微元素在剪應力 τ 作用下，直角扭曲變形為斜菱形，角度變化量即為剪切應變 γ (rad)。',
    formulaBanner: '剪應力 τ = V / A ； 剪應變 γ = Δs / L ； 剪切模數 G = E / [2(1 + ν)]',
    visualHighlights: [
      { label: '單剪 (Single Shear)', desc: '如單搭接螺栓，剪切截面只有 1 個，τ = P / A', badge: '螺栓抗剪 1x' },
      { label: '雙剪 (Double Shear)', desc: '如雙夾板螺栓，剪切截面有 2 個，τ = P / (2A)', badge: '螺栓抗剪 2x' },
      { label: '剪應力互等定理', desc: '正交兩面上的剪應力大小相等且方向必定同時指向或背離兩面之交線', badge: 'τ_xy = τ_yx' },
    ],
    keyTakeaways: [
      '剪切變形改變物體之「形狀（角度）」，而不改變微元素之體積；正應力則改變「長度（體積）」。',
      '雙剪接頭之受剪面積為單剪之 2 倍，故在相同載重下剪應力減半，接合更為安全。',
      '彈性模數 E、剪切模數 G 與波松比 ν 三者存在連動關係：G = E / [2(1+ν)]。',
    ],
  },
  'mechanics/units-vectors': {
    topicSlug: 'units-vectors',
    title: '力學單位制與向量正交分解',
    subtitle: 'SI 國際單位制因次換算與向量合成、方向餘弦',
    conceptType: 'equilibrium-vector',
    icon: '🧭',
    diagramTitle: '二維與三維直角坐標系力向量直角三角形正交投影',
    diagramDescription: '將斜向力 F 投影分解為 Fx = F·cosθ 與 Fy = F·sinθ，並利用方向餘弦滿足 cos²α + cos²β + cos²γ = 1。',
    formulaBanner: '1 MPa = 1 N/mm² = 10⁶ Pa ； 方向餘弦 cos²α + cos²β + cos²γ = 1',
    visualHighlights: [
      { label: '水平分量 Fx', desc: '鄰邊投影：Fx = F · cosθ', badge: 'X 軸分力' },
      { label: '垂直分量 Fy', desc: '對邊投影：Fy = F · sinθ', badge: 'Y 軸分力' },
      { label: '因次齊次性', desc: '等號兩側物理量綱必須一致 (如 [N] = [kg]·[m/s²])', badge: '單位檢核' },
    ],
    keyTakeaways: [
      '力學核心單位換算牢記：1 MPa = 1 N/mm² = 10⁶ N/m² = 10 bar。',
      '向量相加滿足平行四邊形法則與三角形法則，可依 X、Y 各自代數相加後再求合成向量。',
      '力的三要素為：大小 (Magnitude)、方向 (Direction) 與作用點 (Point of Application)。',
    ],
  },
  'mechanics/force-equilibrium': {
    topicSlug: 'force-equilibrium',
    title: '共點力系平衡與拉密定理 (Lami\'s Theorem)',
    subtitle: '三力平衡封閉三角形與拉密正弦比例定理',
    conceptType: 'equilibrium-vector',
    icon: '🎯',
    diagramTitle: '三力共點平衡向量閉合三角形與對角正弦幾何關係',
    diagramDescription: '當三共點力作用於一點達到靜力平衡時，力向量首尾相連必成一封閉三角形，且各力與其對角正弦值成正比。',
    formulaBanner: '拉密定理: P / sinα = Q / sinβ = R / sinγ (三力共點平衡)',
    visualHighlights: [
      { label: '三力共點原理', desc: '剛體受三個不平行外力平衡時，三力作用線必交於同一點', badge: '幾何交會' },
      { label: '向量閉合三角形', desc: '首尾相接形成閉合環路：ΣF = 0', badge: '合力為零' },
      { label: '正交分解法', desc: 'ΣFx = 0, ΣFy = 0 聯立求解兩未知力', badge: '代數解析' },
    ],
    keyTakeaways: [
      '拉密定理僅適用於「三力共點且達成平衡」之特殊狀況，若力數 ≥ 4 則改用正交分解法。',
      '當三力共點且兩兩夾角為 120° 時，三力大小必然完全相等 (P = Q = R)。',
      '三力共點若其中兩力夾角為 90°，可直接利用直角三角形三角函數秒殺求解。',
    ],
  },
  'mechanics/centroid': {
    topicSlug: 'centroid',
    title: '重心、形心與平行軸定理 (Parallel Axis Theorem)',
    subtitle: '截面形心坐標 (x̄, ȳ)、慣性矩 I 與斷面模數 S = I/c',
    conceptType: 'structural-stress',
    icon: '📍',
    diagramTitle: '組合斷面（T型/工字型）面積一次矩形心定位與二次矩平行軸平移',
    diagramDescription: '將複合截面分割為基本幾何形狀（矩形、三角形、圓），以加權平均求形心，再利用 I = Ī + A·d² 累加全截面慣性矩。',
    formulaBanner: '形心 ȳ = Σ(A_i · y_i) / ΣA_i ； 平行軸定理: I_x = Ī_x + A·d²',
    visualHighlights: [
      { label: '矩形形心慣性矩', desc: '底 b 高 h 矩形對自身形心軸 Ī = b·h³ / 12', badge: '基礎公式' },
      { label: '三角形形心慣性矩', desc: '底 b 高 h 三角形對自身形心軸 Ī = b·h³ / 36', badge: '底邊為 bh³/12' },
      { label: '平行軸距離 d', desc: '幾何分割塊自身形心軸與全體形心軸之垂直距離', badge: '平移距離' },
    ],
    keyTakeaways: [
      '矩形截面抗彎能力與高度之「三次方 (h³)」成正比，故梁之放置方向必須立放（高大於寬）。',
      '斷面模數 S = I / c（c 為形心至最外緣之距離），梁之最大抗彎正應力 σ_max = M / S。',
      '平行軸定理中，形心軸之慣性矩 Ī 永遠是所有平行軸中之「極小值」，故 I_任意軸 = Ī + A·d² 恆大於 Ī。',
    ],
  },
  'mechanics/friction': {
    topicSlug: 'friction',
    title: '滑動摩擦力與傾倒臨界分析',
    subtitle: '最大靜摩擦力 f_max = μ_s·N、摩擦角 φ_s 與傾倒/滑動雙重檢討',
    conceptType: 'equilibrium-vector',
    icon: '🧱',
    diagramTitle: '斜面上物體受力分解、摩擦錐 (Friction Cone) 與正向力作用點偏移',
    diagramDescription: '物體在斜面上受重力、正向力 N 與摩擦力 f 作用，當斜面傾角 θ = 摩擦角 φ_s 時達到臨界滑動狀態；正向力作用線移出底面邊界時達到臨界傾倒。',
    formulaBanner: '最大靜摩擦力 f_max = μ_s · N ； 臨界滑動角 tanθ = μ_s ； 摩擦角 φ = arctan(μ_s)',
    visualHighlights: [
      { label: '靜摩擦狀態 (f ≤ f_max)', desc: '摩擦力大小等於推力，物體維持靜止', badge: '未達臨界' },
      { label: '動摩擦狀態 (f_k = μ_k·N)', desc: '物體開始滑動，動摩擦係數 μ_k < 靜摩擦係數 μ_s', badge: '滑動進行中' },
      { label: '傾倒條件 (Tipping)', desc: '正向力 N 偏離中心超過底寬之半 (x > b/2)，物體將先傾倒而非滑動', badge: '幾何邊界' },
    ],
    keyTakeaways: [
      '斜面上物體之臨界滑動傾角 θ 與物體質量 W 無關，只由靜摩擦係數決定 (tanθ = μ_s)。',
      '判斷先滑動還是先傾倒：分別計算臨界推力 P_slide 與 P_tip，較小者為實際發生的破壞模式。',
      '滾動摩擦阻力遠小於滑動摩擦阻力，此為輪軸與滾珠軸承之基本原理。',
    ],
  },
  'mechanics/truss': {
    topicSlug: 'truss',
    title: '平面桁架分析與零力桿判斷三大法則',
    subtitle: '節點法 (Method of Joints)、截面法 (Method of Sections) 與零力桿秒殺',
    conceptType: 'structural-stress',
    icon: '🏗️',
    diagramTitle: '沃倫 (Warren) / 普拉特 (Pratt) 桁架拉力/壓力桿力流與零力桿特徵圖',
    diagramDescription: '展示桁架節點平衡 ΣFx=0, ΣFy=0，透過截面法「一刀切斷不多於 3 桿」取力矩中心求內力，並以零力桿三大法則秒殺無受力桿件。',
    formulaBanner: '靜定桁架條件: m = 2j - r (桿數 m, 節點數 j, 支承反力數 r)',
    visualHighlights: [
      { label: '零力桿法則一 (L型)', desc: '兩桿相交於無載重節點且不共線，兩桿皆為零力桿', badge: '2 桿共 0' },
      { label: '零力桿法則二 (T型)', desc: '三桿相交於無載重節點，其中兩桿共線，第三桿必為零力桿', badge: '1 桿為 0' },
      { label: '零力桿法則三 (X型)', desc: '四桿兩兩共線相交於無載重節點，對頂兩桿桿力相等', badge: '力相等' },
    ],
    keyTakeaways: [
      '截面法最大優勢：欲求中間某單一桿件內力，直接切斷該桿並對其他兩桿交點取力矩 (ΣM=0) 即可一步求解。',
      '桁架所有節點均假設為理想光滑鉸接，故所有桿件只承受軸向拉力 (Tension) 或軸向壓力 (Compression)，無彎矩。',
      '零力桿雖然在特定載重下受力為 0，但在實際工程中具有支撐長壓桿、防止側向挫屈 (Buckling) 之關鍵功能。',
    ],
  },
  'mechanics/beam': {
    topicSlug: 'beam',
    title: '靜定梁受力、剪力圖 (SFD) 與彎矩圖 (BMD)',
    subtitle: '載重 w、剪力 V、彎矩 M 微分關係 dV/dx = -w, dM/dx = V',
    conceptType: 'structural-stress',
    icon: '🌉',
    diagramTitle: '簡支梁在集中載重/均佈載重作用下之 SFD 與 BMD 曲線連動對照圖',
    diagramDescription: '展示載重圖 (Load) → 剪力圖 (SFD 斜率等於載重) → 彎矩圖 (BMD 斜率等於剪力，剪力為 0 處彎矩產生相對極值 M_max)。',
    formulaBanner: '微分關係: dV/dx = -w(x) ； dM/dx = V(x) ； 彎矩面積定理: ΔM = ∫ V dx',
    visualHighlights: [
      { label: '均佈載重區 (w)', desc: 'SFD 為斜直線（一次方），BMD 為拋物線（二次方）', badge: '連續變化' },
      { label: '集中載重處 (P)', desc: 'SFD 產生大小為 P 之垂直突變階梯，BMD 產生折角尖點', badge: '突變階梯' },
      { label: '最大彎矩位置 (M_max)', desc: '當 SFD 穿過零點 (V = 0) 時，該截面之彎矩值必為局部極值', badge: '危險截面' },
    ],
    keyTakeaways: [
      '簡支梁在均佈載重 w 全跨作用下，最大彎矩出現在跨中，大小精確為 M_max = w·L² / 8。',
      '簡支梁在跨中集中載重 P 作用下，最大彎矩在跨中，大小為 M_max = P·L / 4。',
      '懸臂梁在自由端受集中載重 P 時，最大彎矩出現在固定端，大小為 M_max = -P·L（產生負彎矩）。',
    ],
  },
  'mechanics/stress-strain': {
    topicSlug: 'stress-strain',
    title: '正應力、正應變、虎克定律與熱應力變形',
    subtitle: '軸向變形量 δ = PL/AE、熱膨脹變形 δ_T = α·L·ΔT 與應力應變圖',
    conceptType: 'structural-stress',
    icon: '📏',
    diagramTitle: '低碳鋼標準拉伸應力-應變曲線（比例限/彈性限/降伏點/極限強度/破壞）',
    diagramDescription: '標註彈性區斜率（楊氏模數 E = σ/ε）、上/下降伏點、塑性流動平台與兩端受約束桿件升溫產生之熱壓應力。',
    formulaBanner: '軸向變形: δ = P·L / (A·E) ； 虎克定律: σ = E·ε ； 熱應力: σ_T = E · α · ΔT',
    visualHighlights: [
      { label: '彈性模數 (E)', desc: '應力-應變曲線彈性段斜率，代表材料抵抗彈性變形之剛度 (Rigidity)', badge: '剛度指標' },
      { label: '降伏強度 (σ_y)', desc: '材料開始產生顯著塑性變形之臨界應力（如 SD280 鋼筋 σ_y = 280 MPa）', badge: '設計基準' },
      { label: '熱應力約束', desc: '兩端固定之桿件受熱升溫 ΔT 時，因自由膨脹受阻而產生壓應力 σ = E·α·ΔT', badge: '溫度破壞' },
    ],
    keyTakeaways: [
      '軸向變形量與載重 P 及桿長 L 成正比，與截面積 A 及彈性模數 E 成反比 (δ = PL/AE)。',
      '鋼材之彈性模數 E 約為 200 GPa (2.04×10⁶ kgf/cm²)，不論高強度鋼或低碳鋼其 E 值幾乎相同。',
      '自由膨脹不受約束之桿件，升溫時只產生熱變形 (δ_T = α·L·ΔT) 而「不產生任何熱應力」。',
    ],
  },
  'mechanics/spatial-force-systems': {
    topicSlug: 'spatial-force-systems',
    title: '空間力系平衡與三維力矩向量積',
    subtitle: '空間六平衡方程式 ΣFx=0, ΣFy=0, ΣFz=0, ΣMx=0, ΣMy=0, ΣMz=0',
    conceptType: 'equilibrium-vector',
    icon: '🌐',
    diagramTitle: '三維空間直角座標系 (X, Y, Z) 力向量與位置向量叉積力矩 M = r × F',
    diagramDescription: '利用單位向量與行列式展開，計算三維空間中力對某點或對某空間軸之投影力矩與空間平衡狀態。',
    formulaBanner: '空間平衡六條件: ΣF_x=0, ΣF_y=0, ΣF_z=0 ； ΣM_x=0, ΣM_y=0, ΣM_z=0',
    visualHighlights: [
      { label: '三維位置向量 r', desc: '從力矩中心 O 指向力作用線上任意點 A 之向量 r = xi + yj + zk', badge: '力臂向量' },
      { label: '向量外積 (Cross Product)', desc: 'M_O = r × F，方向由右手定則判定，垂直於 r 與 F 所決定的平面', badge: '力矩向量' },
      { label: '對軸之矩', desc: '力對某軸之矩，等於該力對該軸上任意點之矩向量在該軸方向上之投影分量', badge: '軸投影矩' },
    ],
    keyTakeaways: [
      '三維空間剛體具備 6 個自由度（3 個平移 + 3 個旋轉），故需 6 個獨立方程式達成完全平衡。',
      '空間中若力之作用線與某軸平行或相交，則該力對該軸之「力矩必為零」。',
      '求解空間力系時，先求出各力之單位方向向量 λ = (Δx·i + Δy·j + Δz·k) / L，再乘上力大小 F。',
    ],
  },
  'mechanics/plane-stress': {
    topicSlug: 'plane-stress',
    title: '平面應力轉換與莫耳圓 (Mohr\'s Circle) 圖解',
    subtitle: '主應力 σ₁, σ₂、主平面角度 θ_p 與最大剪應力 τ_max = R',
    conceptType: 'structural-stress',
    icon: '⭕',
    diagramTitle: '應力微元素旋轉 θ 角之應力狀態在 σ-τ 座標系對應之莫耳圓圖解',
    diagramDescription: '莫爾圓圓心坐標為 C = ((σx+σy)/2, 0)，圓半徑 R 即為最大剪應力 τ_max，圓與 σ 軸交點即為主應力 σ₁ 與 σ₂。',
    formulaBanner: '莫耳圓心 C = (σ_x + σ_y)/2 ； 半徑 R = √[((σ_x - σ_y)/2)² + τ_xy²] ； 主應力 σ_{1,2} = C ± R',
    visualHighlights: [
      { label: '主平面 (Principal Planes)', desc: '剪應力為零 (τ = 0) 之截面，其正應力達到極大值 σ₁ 與極小值 σ₂', badge: '純拉/壓' },
      { label: '最大剪應力平面', desc: '與主平面夾角為 45°，其最大剪應力大小等於莫爾圓半徑 τ_max = R', badge: '45° 剪切' },
      { label: '實體角與圓上角', desc: '實體微元素旋轉 θ 角，莫爾圓上對應點旋轉 2θ 角且方向相同', badge: '2θ 映射' },
    ],
    keyTakeaways: [
      '在主平面上，剪應力恆等於零 (τ = 0)；兩主應力平面互相垂直 (夾角 90°)。',
      '最大剪應力大小等於兩主應力差之半：τ_max = (σ₁ - σ₂) / 2 = 莫爾圓半徑 R。',
      '純剪切狀態下 (σx = 0, σy = 0)，莫耳圓圓心在原點 (0,0)，主應力為 σ₁ = +τ, σ₂ = -τ。',
    ],
  },

  // ==========================================
  // 2. MATERIALS (13 Topics)
  // ==========================================
  'materials/green-building-materials': {
    topicSlug: 'green-building-materials',
    title: '綠建材評估與建築循環經濟生命週期',
    subtitle: '四大綠建材標章（生態、健康、高性能、再生）與 LCA 碳足跡',
    conceptType: 'material-reaction',
    icon: '🌱',
    diagramTitle: '台灣四大綠建材標章評估指標與建築全生命週期 (LCA) 減碳路徑',
    diagramDescription: '展示生態綠建材、健康綠建材 (低 TVOC/甲醛)、高性能綠建材 (隔音/防熱) 與再生綠建材之循環回用機制。',
    formulaBanner: '綠建材使用率 = (綠建材總表面積 / 室內裝修總表面積) ≥ 60% (室內) / 45% (室外)',
    visualHighlights: [
      { label: '健康綠建材', desc: '嚴格限制總揮發性有機物 (TVOC) 與游離甲醛逸散速率 (E1/E0 級)', badge: '室內空氣' },
      { label: '生態綠建材', desc: '採用天然未加工無匱乏危機原料（竹材、羊毛隔熱）', badge: '自然資源' },
      { label: '再生綠建材', desc: '回收廢棄物摻配率達一定比例（高爐石、再生骨材）', badge: '循環經濟' },
    ],
    keyTakeaways: [
      '健康綠建材為台灣建築物室內裝修最常用標章，旨在避免「病態建築症候群 (SBS)」。',
      '綠建築法規規定建築物室內裝修綠建材使用率至少需達 60% 以上。',
      '高性能防音綠建材需通過衝擊音隔音性能檢測，符合建築技術規則樓板隔音 ΔLw ≥ 17 dB 標準。',
    ],
  },
  'materials/basic-properties': {
    topicSlug: 'basic-properties',
    title: '工程材料基本物理與力學性質',
    subtitle: '密度、比重、孔隙率 (n)、吸水率與彈/塑/韌/脆性圖解',
    conceptType: 'material-reaction',
    icon: '🧪',
    diagramTitle: '三相微觀孔隙模型（固體骨架、開口孔隙、封閉孔隙）與吸水力學關係',
    diagramDescription: '展示材料真實體積 vs 外觀體積，孔隙率 n = V_pore / V_total 與吸水率、抗凍融耐久性之物理關聯。',
    formulaBanner: '孔隙率 n = (1 - ρ_bulk / ρ_true) × 100% ； 含水率 w = (W_wet - W_dry) / W_dry × 100%',
    visualHighlights: [
      { label: '真密度 (True Density)', desc: '純固體骨架質量除以絕對密實體積（扣除所有孔隙）', badge: '材料本質' },
      { label: '體積密度 (Bulk Density)', desc: '含內部所有開口與封閉孔隙之自然狀態外觀體積密度', badge: '外觀體積' },
      { label: '吸水飽和係數', desc: '開口孔隙越多，吸水率越高，材料抗凍融性與強度急劇下降', badge: '耐久性關鍵' },
    ],
    keyTakeaways: [
      '材料的孔隙率越低（越密實），其抗壓強度越高、導熱係數越高、吸水率越低、耐凍性越好。',
      '韌性 (Toughness) 是材料在破壞前吸收塑性變形能量的能力；脆性材料（如玻璃、陶瓷）破壞前幾乎無變形。',
      '硬度 (Hardness) 代表抵抗表面被其他較硬物體壓入或刮傷的能力（莫氏硬度 1~10 級）。',
    ],
  },
  'materials/cement-composition': {
    topicSlug: 'cement-composition',
    title: '卜特蘭水泥四大水化化合物化學組成',
    subtitle: 'C3S（早強）、C2S（後期）、C3A（水化熱最高）、C4AF（耐水化）',
    conceptType: 'material-reaction',
    icon: '⚗️',
    diagramTitle: '卜特蘭水泥水化產物水化熱釋放速率與強度發展歷程對比曲線',
    diagramDescription: '展示 C3S (矽酸三鈣)、C2S (矽酸二鈣)、C3A (鋁酸三鈣)、C4AF (鐵鋁酸四鈣) 在 28 天至 1 年之強度貢獻圖。',
    formulaBanner: '水泥四大礦物: C₃S (3CaO·SiO₂) , C₂S (2CaO·SiO₂) , C₃A (3CaO·Al₂O₃) , C₄AF (4CaO·Al₂O₃·Fe₂O₃)',
    visualHighlights: [
      { label: 'C3S (矽酸三鈣, 50~70%)', desc: '水化反應快，主導水泥前 28 天之「早期強度」', badge: '早強功臣' },
      { label: 'C2S (矽酸二鈣, 15~30%)', desc: '水化緩慢發熱低，提供 28 天以後之「長期強度發展」', badge: '後勁十足' },
      { label: 'C3A (鋁酸三鈣, 5~10%)', desc: '水化極快發熱量最高，耐硫酸鹽侵蝕能力最差，需加石膏調節凝結', badge: '水化熱魔王' },
      { label: 'C4AF (鐵鋁酸四鈣, 5~15%)', desc: '水化速度快但強度貢獻極低，賦予水泥深灰色外觀', badge: '水化顏色' },
    ],
    keyTakeaways: [
      '早強水泥（Type III）提高 C3S 與 C3A 比例並磨得更細；低熱水泥（Type IV 如大壩）則大幅提高 C2S 比例。',
      '水泥熟料中若不添加石膏 (CaSO4·2H2O)，C3A 會在幾分鐘內急速水化造成「急凝 (Flash Set)」無法施工。',
      '水化反應生成的 C-S-H 膠體 (水化矽酸鈣) 是水泥硬化體強度的主要來源。',
    ],
  },
  'materials/cement-types': {
    topicSlug: 'cement-types',
    title: 'CNS 61 卜特蘭水泥五大類型規範比較',
    subtitle: 'Type I 普通、Type II 中熱中硫、Type III 早強、Type IV 低熱、Type V 抗硫酸鹽',
    conceptType: 'comparative-matrix',
    icon: '🏭',
    diagramTitle: 'CNS 61 五大水泥類型成分比例、水化熱與典型工程應用矩陣圖',
    diagramDescription: '對照 Type I~V 水泥在水化熱曲線、凝結速度、抗化學侵蝕能力與工程場景（如大壩、高樓、碼頭海港）。',
    formulaBanner: 'CNS 61 規範: Type I (普通) / Type II (中度抗硫) / Type III (早強) / Type IV (低熱) / Type V (抗硫)',
    visualHighlights: [
      { label: 'Type I (普通型)', desc: '一般建築工程、梁柱板牆通用，用量佔 90% 以上', badge: '常規必備' },
      { label: 'Type III (早強型)', desc: '緊急搶修工程、低溫寒冬施工、預鑄預力混凝土早拆模', badge: '3天達7天強度' },
      { label: 'Type IV (低熱型)', desc: '巨積混凝土（如水庫大壩），避免水化熱聚集導致嚴重溫差裂縫', badge: '大壩水庫' },
      { label: 'Type V (抗硫酸鹽)', desc: '海港碼頭、污水處理廠、高硫酸鹽土壤地下結構', badge: '海港耐蝕' },
    ],
    keyTakeaways: [
      '巨積混凝土最怕內部高溫膨脹造成表面拉裂，必須選用 Type IV 低熱水泥或添加飛灰/爐石粉降溫。',
      'Type II 為中度抗硫酸鹽與中度水化熱，常應用於大型橋墩基礎與地下涵洞。',
      '高爐水泥 (Type IS) 與飛灰水泥 (Type IP) 屬於水硬性混合水泥，能有效提升長期抗滲耐久性。',
    ],
  },
  'materials/cement-vicat': {
    topicSlug: 'cement-vicat',
    title: '維卡儀 (Vicat) 水泥凝結時間試驗',
    subtitle: '標準稠度用水量、初凝時間 (≥ 45 min) 與終凝時間 (≤ 375 min)',
    conceptType: 'material-reaction',
    icon: '⏱️',
    diagramTitle: 'CNS 786 維卡儀標準試針下陷深度與水泥漿凝結時間讀數尺圖解',
    diagramDescription: '展示標準稠度試針 (10mm) 下陷至 10±1mm 測定用水量，及初凝試針 (1mm) 下陷距底板 4mm 判讀初凝點。',
    formulaBanner: 'CNS 61 凝結時間規定: 初凝時間 ≥ 45 分鐘 ； 終凝時間 ≤ 375 分鐘 (6.25 小時)',
    visualHighlights: [
      { label: '標準稠度用水量 (P)', desc: '直徑 10mm 柱體試針在 30 秒內下陷至距底板 10±1mm 處之水量比', badge: '前置基準' },
      { label: '初凝時間 (Initial Set)', desc: '直徑 1mm 針下陷至距底板 4mm 時的時間，混凝土需在此前完成澆置修飾', badge: '施工極限' },
      { label: '終凝時間 (Final Set)', desc: '有環狀附件之試針僅針尖留痕而圓環完全不留痕時的時間，材料完全硬化', badge: '硬化起點' },
    ],
    keyTakeaways: [
      '初凝時間不得小於 45 分鐘，確保工地有足夠時間完成混凝土攪拌、運送、澆置與搗實。',
      '終凝時間不得大於 375 分鐘 (6.25 小時)，避免硬化過慢延誤後續工序與拆模進度。',
      '溫度越高凝結時間越短，故夏季高溫施工常需添加緩凝劑 (Retarder)。',
    ],
  },
  'materials/cement-strength': {
    topicSlug: 'cement-strength',
    title: 'CNS 1012 水泥砂漿抗壓強度試驗',
    subtitle: '50mm (2英吋) 立方體試體、標準砂配比與 3/7/28 天強度發展',
    conceptType: 'structural-stress',
    icon: '🧱',
    diagramTitle: '水泥砂漿 50mm 立方體抗壓破壞模式與水灰比強度發展曲線',
    diagramDescription: '展示標準比例（水泥:標準砂 = 1:2.75，水灰比 0.485），在壓力機上等速加壓破壞之角錐破壞面。',
    formulaBanner: '抗壓強度 f\'m = 最大破壞載重 P / 受壓截面積 A (50mm × 50mm = 2500 mm²)',
    visualHighlights: [
      { label: '標準立方體試體', desc: '50 mm × 50 mm × 50 mm 鋼模分兩層裝填，每層搗實 32 次', badge: '標準試模' },
      { label: '標準砂 (Ottawa Sand)', desc: '符合 CNS 規範之均勻石英砂，排除骨材品質變異對水泥強度的干擾', badge: '標準砂粒' },
      { label: '養護環境', desc: '脫模後浸泡於 23.0±2.0°C 之飽和石灰水中養護至試驗齡期', badge: '標準養護' },
    ],
    keyTakeaways: [
      'CNS 61 要求 Type I 普通水泥砂漿 28 天抗壓強度必須達 28.0 MPa (280 kgf/cm²) 以上。',
      '試體受壓加壓速率應控制在每秒 900 至 1800 N，避免衝擊載重造成強度讀數失真。',
      '養護水必須加入飽和石灰 (Ca(OH)2)，防止試體中之氫氧化鈣被清水溶出而削弱強度。',
    ],
  },
  'materials/cement-storage': {
    topicSlug: 'cement-storage',
    title: '水泥儲存品質防護與假凝 (False Set) 排除',
    subtitle: '防潮防風化儲存標準、假凝 vs 急凝成因與處置對策',
    conceptType: 'material-reaction',
    icon: '📦',
    diagramTitle: '袋裝水泥倉庫防潮架高堆疊規範與假凝/急凝結晶再分散機理圖',
    diagramDescription: '展示離地 20cm 離牆 30cm 堆疊、堆高不超過 10 袋，以及假凝（石膏脫水成半水石膏微晶）經二次攪拌即可恢復工作性。',
    formulaBanner: '假凝 (False Set): 無大量放熱，再攪拌即可復原 ； 急凝 (Flash Set): 大量放熱，不可復原',
    visualHighlights: [
      { label: '倉庫堆疊規範', desc: '架高棧板 ≥ 20cm，離牆 ≥ 30cm，堆疊高度 ≤ 10 袋（長期 ≤ 7 袋）', badge: '防潮防結塊' },
      { label: '假凝 (False Set)', desc: '研磨過熱石膏脫水，加水快速硬化但「無大量發熱」，強力重新攪拌即可復原', badge: '二次攪拌' },
      { label: '急凝 (Flash Set)', desc: '石膏量不足 C3A 暴走水化，「釋放巨大熱量」且不可復原，混凝土報廢', badge: '不可逆破壞' },
    ],
    keyTakeaways: [
      '袋裝水泥先進先出 (FIFO) 原則：儲存超過 3 個月之水泥，使用前必須重新取樣抽驗強度。',
      '遇水泥假凝現象時，切忌額外盲目加水（會破壞水灰比），只需延長機械攪拌時間即可化解。',
      '散裝水泥儲槽 (Silo) 頂部應設透氣除塵濾袋，並定期清理槽底死角積料避免受潮結塊。',
    ],
  },
  'materials/concrete': {
    topicSlug: 'concrete',
    title: '混凝土配比設計、水灰比定律與坍度試驗',
    subtitle: '亞伯蘭水灰比定律 (Abrams\' Law)、坍度試驗與 28 天抗壓試驗',
    conceptType: 'structural-stress',
    icon: '🏗️',
    diagramTitle: '水灰比 (W/C) 與強度/工作性天平關係及 30cm 坍度錐分三層搗實圖解',
    diagramDescription: '展示 W/C 越小強度越高但工作性變差，及 CNS 1176 坍度錐 (高30cm) 分 3 層各搗 25 次之四種坍度形態。',
    formulaBanner: 'Abrams 水灰比定律: f\'c = A / B^(W/C) ； 坍度 = 30 cm - 坍落後最高點高度',
    visualHighlights: [
      { label: '正常坍度 (True Slump)', desc: '均勻對稱沉降，代表配比良好、凝聚力佳之正常工作性', badge: '合格流動' },
      { label: '剪切坍度 (Shear Slump)', desc: '一側坍落脫落，代表配比細料不足或太黏，應重新取樣重測', badge: '重測複驗' },
      { label: '崩塌坍度 (Collapse)', desc: '完全攤平散開，代表水灰比過高、嚴重析離 (Segregation)', badge: '不合格配比' },
    ],
    keyTakeaways: [
      '亞伯蘭定律：在完全搗實的前提下，混凝土強度唯一由「水灰比 (W/C 或 W/B)」決定。',
      '常規鋼筋混凝土梁柱坍度一般約 15±3.8 cm；自密實混凝土 (SCC) 則採用坍流度 (Slump Flow ≥ 60 cm)。',
      '工地絕對禁止「為求好澆置而任意私自加水」，加水會直接拉大水灰比導致試體 28 天抗壓強度不合格。',
    ],
  },
  'materials/stone-ceramics-glass': {
    topicSlug: 'stone-ceramics-glass',
    title: '天然石材、陶瓷面磚與 Low-E 節能玻璃',
    subtitle: '花崗岩/大理石特性、面磚吸水率分級 (I~III類) 與中空 Low-E 玻璃光熱原理',
    conceptType: 'material-reaction',
    icon: '💎',
    diagramTitle: 'Low-E 低輻射中空玻璃奈米銀膜反射遠紅外線與光線穿透光譜圖',
    diagramDescription: '展示 Low-E 玻璃阻擋 90% 室外太陽輻射熱（遠紅外線），同時保留 70% 可見光穿透之光熱分離機制。',
    formulaBanner: '中空 Low-E 玻璃: U值 ≤ 1.8 W/(m²·K) ； 遮陽係數 SC = 0.3 ~ 0.5',
    visualHighlights: [
      { label: '花崗岩 (Granite)', desc: '深成火成岩，二氧化矽含量高，耐酸耐磨，極適合建築室外牆面與地坪', badge: '外牆首選' },
      { label: '大理石 (Marble)', desc: '變質岩（主成分碳酸鈣 CaCO3），遇酸易腐蝕失光，一般僅限室內使用', badge: '室內裝修' },
      { label: '面磚吸水率分級', desc: 'I類磁質 (≤1%) > II類炻質 (≤5%) > III類陶質 (≤18% 僅限室內)', badge: '防膨拱關鍵' },
    ],
    keyTakeaways: [
      '大理石遇酸雨會溶解生成硫酸鈣而風化白化，外牆及地面鋪設應優先選用硬度高耐酸之花崗岩。',
      '外牆磁磚必須採用吸水率 ≤ 1% 之「磁質 (Porcelain) 瓷磚」，以防冬日水氣結冰膨脹導致磁磚脫落砸傷行人。',
      '膠合強化玻璃 (Laminated Glass) 破裂時碎片黏附在 PVB 中間膜上不掉落，為超高層建築帷幕牆法定安全玻璃。',
    ],
  },

  // ==========================================
  // 4. DRAFTING (16 Topics)
  // ==========================================
  'drafting/bim-concepts': {
    topicSlug: 'bim-concepts',
    title: '建築資訊模型 (BIM) 核心概念與數位協同',
    subtitle: 'BIM 3D~7D 維度、LOD 100~500 細緻度與多專業碰撞檢測 (Clash Detection)',
    conceptType: 'flowchart-logic',
    icon: '🏢',
    diagramTitle: 'BIM 建築 (Arch)、結構 (Struct)、機電 (MEP) 數位孿生整合與 Navisworks 空間干涉檢測圖解',
    diagramDescription: '展示梁穿梁、風管撞結構梁、消防管撞門框之即時干涉檢測，消除工地現場打鑿重做風險。',
    formulaBanner: 'BIM 維度: 3D (空間幾何) / 4D (時間排程) / 5D (造價預算) / 6D (綠能永續) / 7D (設施維運 FM)',
    visualHighlights: [
      { label: 'LOD 細緻度標準', desc: 'LOD 100 (概念體量) → LOD 200 (概略構件) → LOD 300 (施工精確圖) → LOD 400 (加工製造組裝)', badge: 'LOD 規範' },
      { label: '硬碰撞 vs 軟碰撞', desc: '硬碰撞（實體幾何干涉如管穿梁）；軟碰撞（間隙不足未留維修操作空間或保溫層厚度）', badge: '衝突分析' },
      { label: 'BIM 自動化算量 (QTO)', desc: '模型構件參數直接聯動混凝土體積、模板面積與鋼筋噸數，消除傳統手工算量誤差', badge: '精準預算' },
    ],
    keyTakeaways: [
      'BIM 不只是 3D 繪圖軟體，而是包含所有幾何與物理屬性參數的「數位孿生資料庫」。',
      '碰撞檢測能在施工前於電腦模型中找出 99% 的管線衝突，避免工地現場敲打打鑿浪費成本。',
      'IFC (Industry Foundation Classes) 為國際通用之開放 BIM 檔案交換標準，實現跨軟體無縫協同作業。',
    ],
  },
  'drafting/building-codes-far': {
    topicSlug: 'building-codes-far',
    title: '建築技術規則：建蔽率、容積率與防火避難檢討',
    subtitle: '建築面積、總樓地板面積、法定空地、走廊樓梯淨寬與防火區劃',
    conceptType: 'drafting-projection',
    icon: '📜',
    diagramTitle: '建築基地建蔽率、容積率立體量體推移與防火區劃 (1500m²) 空間模型',
    diagramDescription: '展示建蔽率決定平面覆蓋與法定空地，容積率決定總樓地板面積，及防火門窗、梯廳排煙室安全檢討。',
    formulaBanner: '建蔽率 = (建築面積 / 基地面積) × 100% ； 容積率 = (總樓地板面積 / 基地面積) × 100%',
    visualHighlights: [
      { label: '建蔽率 (Coverage)', desc: '建築物投影面積除以基地面積，留設法定空地供採光、通風與消防避難', badge: '空地保障' },
      { label: '容積率 (FAR)', desc: '地上各層樓地板面積總和除以基地面積，管制土地使用強度與都市活動密度', badge: '總量管制' },
      { label: '防火區劃 (Fire Compartment)', desc: '高層建築每 1500 m² 應以具 1 小時以上防火時效之牆壁、樓板及防火門窗完全分隔', badge: '防火時效' },
    ],
    keyTakeaways: [
      '基地面積 1000m²、建蔽率 60%、容積率 300%：最大建築面積為 600m²，最大總樓地板面積為 3000m²。',
      '樓梯淨寬法規：一般住宅樓梯淨寬不得小於 90 公分；集合住宅或公共建築不得小於 120 公分。',
      '免計入容積率項目：陽台（每層樓地板面積 10% 以內）、屋頂突出物、機電設備空間及法定防空避難室。',
    ],
  },
  'drafting/drafting-fundamentals': {
    topicSlug: 'drafting-fundamentals',
    title: '建築圖學基礎：投影原理、幾何圖學與圖紙規格',
    subtitle: '中心投影 vs 平行投影（正投影/斜投影/軸測圖）與 CNS A 系列圖紙',
    conceptType: 'drafting-projection',
    icon: '📐',
    diagramTitle: '投影法分類架構樹（中心透視 vs 平行正投影/等角圖）與 A0~A4 裁切對摺模矩圖',
    diagramDescription: '展示正投影（視線垂直投影面無畸變）、等角圖 (30°/30°)、斜角圖 (45° 減半)，及 A 系列圖紙 1:√2 比例。',
    formulaBanner: '圖紙尺寸: A0 (841×1189mm) ； A1 (594×841mm) ； A2 (420×594mm) ； A3 (297×420mm) ； A4 (210×297mm)',
    visualHighlights: [
      { label: '正投影 (Orthographic)', desc: '投射線互相平行且垂直於投影面，能真實反映物體各部位形狀與精確尺度，為工程圖基石', badge: '工程製圖' },
      { label: '軸測等角圖 (Isometric)', desc: '三軸夾角皆為 120°，三個方向縮尺比均為 1:1，直觀呈現 3D 立體外觀', badge: '立體表達' },
      { label: 'A 系列圖紙模矩', desc: '長寬比恆為 1:√2，每對折一次面積恰好減半，比例維持不變', badge: 'ISO / CNS' },
    ],
    keyTakeaways: [
      '工程製圖之所以採用「正投影」，是因為平行投射線不會產生透視變形，可直接在圖紙上量取真實尺寸。',
      '等角圖 (Isometric) 的三軸夾角均為 120°，兩水平軸線與水平線夾角為 30°。',
      'A0 圖紙面積剛好為 1 平方公尺 (1 m²)，標準尺寸為 841 mm × 1189 mm。',
    ],
  },
  'drafting/civil-architectural-drawings': {
    topicSlug: 'civil-architectural-drawings',
    title: '土木與建築施工圖識圖、圖號管理與圖例符號',
    subtitle: '全套建築施工圖（A/S/E/P/M）、平立剖關聯與 CNS 建築材料圖例',
    conceptType: 'drafting-projection',
    icon: '📑',
    diagramTitle: '全套建築施工圖紙圖號體系與混凝土/磚石/保溫/木材 CNS 標準圖例符號對照',
    diagramDescription: '展示鋼筋混凝土 (RC 剖面點斜線)、紅磚 (45° 斜單線)、木材 (年輪木紋)、土壤 (三短一長) 等 CNS 6100 標準符號。',
    formulaBanner: '施工圖號: A-101 (建築平面) / A-201 (立面) / A-301 (剖面) / S-101 (結構配筋) / D-101 (大樣)',
    visualHighlights: [
      { label: '鋼筋混凝土圖例', desc: 'CNS 規範以細實線 45° 斜線內部均勻散佈微細點狀符號表示', badge: 'RC 圖例' },
      { label: '保溫隔熱材料', desc: '連續波浪形線或交叉網格填充表示（如玻璃棉、岩棉）', badge: '保溫圖例' },
      { label: '平立剖關聯索引', desc: '平面圖上以剖切符號（圓圈代號+視向箭頭）標明對應剖面圖圖號', badge: '圖面索引' },
    ],
    keyTakeaways: [
      '識讀建築圖第一步：先看標題欄（工程名稱、圖名、比例尺、圖號、繪圖日期與建築師簽章）。',
      '剖面索引符號：圓圈上半部標註「剖面圖號」，下半部標註「該剖面圖所在之圖紙編號」。',
      '平面圖中若有結構柱梁與牆體重疊，結構體線條粗細與優先級高於非承重磚隔間牆。',
    ],
  },
  'drafting/lines-and-lettering': {
    topicSlug: 'lines-and-lettering',
    title: '工程線條種類、粗細層級與等線體工程字法',
    subtitle: '粗實線、中虛線、細鏈線、割面線優先順序與 CNS 中文等線體',
    conceptType: 'drafting-projection',
    icon: '✍️',
    diagramTitle: 'CNS 8 種線條形式、粗細比例與多線重疊時之繪製優先順序層級圖',
    diagramDescription: '展示線條優先順序：可見輪廓線（粗實線） > 隱藏線（中虛線） > 剖切面線（割面線） > 中心線（細鏈線） > 尺寸線。',
    formulaBanner: '線條優先級: 可見輪廓線 (粗實) > 隱藏線 (中虛) > 割面線 > 中心線 (細鏈) > 尺寸與引線',
    visualHighlights: [
      { label: '粗實線 (Continuous Thick)', desc: '可見輪廓線、建築物外觀與剖切面實體外邊線（粗度 0.5~0.7 mm）', badge: '最優先' },
      { label: '中虛線 (Dashed Medium)', desc: '隱藏輪廓線、被遮擋之不可見邊界（線段 3mm、間距 1mm）', badge: '第 2 優先' },
      { label: '細鏈線 (Chain Thin)', desc: '對稱中心線、旋轉軸線（長劃 15~20mm、間隔 1mm、點 1mm）', badge: '中心對稱' },
      { label: '割面線 (Cutting Plane)', desc: '端部與轉折處加粗之鏈線，兩端附帶視向箭頭與英文字母代號', badge: '剖切指示' },
    ],
    keyTakeaways: [
      '當不同線條在同一直線上重疊時，優先繪製順序：粗實線 > 中虛線 > 割面線 > 細鏈線 > 尺寸線。',
      'CNS 工程中文字體標準為「等線體（字體筆畫粗細一致）」，字高與字寬比例約為 3:2 或 1:1，書寫工整不得連筆。',
      '中心線（細鏈線）兩端必須超出物體輪廓線約 2 至 3 mm，且圓之中心線相交處必須是「長劃與長劃相交」，不可交於點或空隙。',
    ],
  },
  'drafting/scale': {
    topicSlug: 'scale',
    title: '出圖比例尺、三稜比例尺使用與比例換算',
    subtitle: '常用建築比例 (1/100, 1/200, 1/500, 1/10)、縮尺與放大尺度換算',
    conceptType: 'drafting-projection',
    icon: '📏',
    diagramTitle: '三稜比例尺 6 大常用比例 (1/100~1/600) 與圖面距離 vs 實地真實長度換算圖解',
    diagramDescription: '展示圖上 1cm 代表實地 1m (1:100)、實地 2m (1:200)、實地 5m (1:500)，及三稜尺正確量測視角。',
    formulaBanner: '比例公式: 比例尺 = 圖上距離 / 實地真實距離 (如 1:100 即 10mm 代表 1000mm)',
    visualHighlights: [
      { label: '1/100 比例', desc: '建築平立剖面圖最常用比例，圖上 1 公分 = 現實 1 公尺 (100 cm)', badge: '平立剖常用' },
      { label: '1/500 比例', desc: '基地配置圖與地籍套繪圖常用比例，圖上 1 公分 = 現實 5 公尺 (500 cm)', badge: '配置圖' },
      { label: '1/10 比例', desc: '施工大樣圖 (Detail) 常用比例，圖上 1 公分 = 現實 10 公分 (100 mm)', badge: '大樣圖' },
    ],
    keyTakeaways: [
      '比例尺是「量取長度的工具」，絕對禁止拿三稜比例尺來引導筆尖畫線，以免磨損邊緣刻度。',
      '面積縮放關係：圖上長度縮放比為 1:k，則圖上面積縮放比為「1 : k²」（面積為平方比）。',
      '不論圖紙按何種比例縮放列印，圖面上標註的尺寸數字「永遠標註實地真實尺寸」。',
    ],
  },
  'drafting/orthographic-projection': {
    topicSlug: 'orthographic-projection',
    title: '正投影多視圖法：第三角法 vs 第一角法比較',
    subtitle: 'CNS 規範第三角法（人-投-物）與第一角法（人-物-投）空間展開箱',
    conceptType: 'drafting-projection',
    icon: '📦',
    diagramTitle: '第三角法 3D 玻璃投影箱向六個方向展開為二維工程圖紙排布圖',
    diagramDescription: '展示第三角法：俯視圖在正視圖上方、右側視圖在正視圖右方；對比第一角法（歐洲常用）：俯視圖在下方、右側視圖在左方。',
    formulaBanner: 'CNS 規範: 台灣採用第三角法 (Third Angle) ； 投影關係: 觀察者 (人) → 投影面 (投) → 物體 (物)',
    visualHighlights: [
      { label: '第三角法 (Third Angle)', desc: '投影面位於人與物體之間（人-投-物），視圖位置與觀察方向一致（俯視在上、右視在右）', badge: 'CNS / 美日台' },
      { label: '第一角法 (First Angle)', desc: '物體位於人與投影面之間（人-物-投），投影至物體後方（俯視在下、右視在左）', badge: 'ISO / 歐洲' },
      { label: '投影符號標記', desc: 'CNS 規定圖框標題欄中應標註錐體第三角投影符號（左大圓右梯形錐）', badge: '標準標誌' },
    ],
    keyTakeaways: [
      '台灣 CNS 國家標準明確規定：所有機械與建築工程製圖一律以「第三角法」為原則。',
      '第三角法視圖排布直覺符合人體工學：由上看投影在上方、由右看投影在右方。',
      '空間四個象限中，第二象限與第四象限展開時視圖會重疊干擾，故工程上只使用第一角法與第三角法。',
    ],
  },
  'drafting/sectional-views': {
    topicSlug: 'sectional-views',
    title: '剖面視圖分類、45° 剖面線與縱向不剖構件',
    subtitle: '全剖面、半剖面、局部剖面、階梯剖面與肋/螺栓/輪輻不剖規則',
    conceptType: 'drafting-projection',
    icon: '✂️',
    diagramTitle: '割面線轉折路徑、45° 細實線剖面線繪製與對稱物體半剖面 (1/4 剖切) 圖解',
    diagramDescription: '展示割面線粗端與箭頭（指向視線方向），對稱物體半剖面（一半外觀一半內部），及螺栓/鋼筋/肋板縱向剖切不畫剖面線。',
    formulaBanner: 'CNS 剖面線規範: 45° 細實線 ； 間距 1.5 ~ 3.0 mm ； 縱向不剖: 鋼筋/螺栓/肋板/軸/銷',
    visualHighlights: [
      { label: '全剖面 (Full Section)', desc: '假想割面完全切過物體中央，完整揭示內部中空孔洞與構造', badge: '完全剖開' },
      { label: '半剖面 (Half Section)', desc: '僅剖切對稱物體之 1/4，以中心線分界，一半呈現外觀形狀、另一半呈現內部構造', badge: '外觀+內部' },
      { label: '縱向不剖構件 (No Hatching)', desc: '肋板 (Rib)、輪輻、實心軸 (Shaft)、螺栓 (Bolt)、鉚釘、鋼筋等縱向剖切時「不畫剖面線」', badge: '縱向不剖' },
    ],
    keyTakeaways: [
      '相鄰兩構件之剖面線應改變方向（一邊 45°，另一邊 135°）或改變間距，以清晰區分不同零件。',
      '半剖面視圖中，以「細鏈線中心線」作為剖面與外觀之分界線，不可繪製粗實線分割。',
      '階梯剖面 (Offset Section) 在割面轉折處不畫實線，轉折位置在視圖中視為連續平面。',
    ],
  },
  'drafting/architectural-plan': {
    topicSlug: 'architectural-plan',
    title: '建築平面圖繪製：牆體柱位、門窗開口與尺寸符號',
    subtitle: '水平剖切 (1.2m)、結構柱網軸線、門窗代號 (D1/W1) 與三道尺寸線',
    conceptType: 'drafting-projection',
    icon: '🏠',
    diagramTitle: '標準一層建築平面圖（柱網軸線/牆體粗線/門開啟弧線/外圍三道尺寸線）版面分解',
    diagramDescription: '展示水平剖切 1.2m 俯視、牆體粗實線 (0.5mm)、門旋轉開啟 90° 弧線細線、窗框四線與房間標註。',
    formulaBanner: '平面圖繪製規範: 水平剖切高 1.2m ； 牆柱輪廓採粗實線 ； 門窗代號圓圈 D (門) / W (窗)',
    visualHighlights: [
      { label: '門開啟線 (Door Swing)', desc: '以細實線繪製 90° 圓弧，明確標示門扇開啟方向與所佔用之旋轉淨空半徑', badge: '開口細線' },
      { label: '窗戶符號 (Window)', desc: '以四條細平行線表示窗框與窗玻璃，窗下台度 (Sill) 在平面圖上可見', badge: '窗戶四線' },
      { label: '地坪高程 (Level, FL)', desc: '以符號 ▽ FL+15cm 標註室內地坪相對於基地基準點 (GL±0) 之垂直高差', badge: '地坪高程' },
    ],
    keyTakeaways: [
      '建築平面圖剖切高度位於「窗台上方 1.2 公尺處」，故高於 1.2m 之氣窗或梁位需以「中虛線」繪製。',
      '平面圖外圍三道尺寸線：第一道（門窗開口）、第二道（柱心軸線跨距）、第三道（建築物總長總寬）。',
      '柱網軸號編排慣例：水平方向由左至右為數字 (1, 2, 3...)，垂直方向由下至上為英文字母 (A, B, C...)。',
    ],
  },
  'drafting/architectural-elevation': {
    topicSlug: 'architectural-elevation',
    title: '建築立面圖繪製：四向外觀、材質分界與垂直地平線',
    subtitle: '正立面/背立面/側立面、材質圖例（面磚/石材/格柵）、屋脊高度與地平線 (GL)',
    conceptType: 'drafting-projection',
    icon: '🏢',
    diagramTitle: '四向建築立面圖（地平線粗線 GL / 樓層線 FL / 外牆材質貼面 / 女兒牆頂高）投影圖',
    diagramDescription: '展示地面基線 (GL) 以最粗實線繪製，近立面粗實線、遠立面細實線營造景深，及標註層高與總高。',
    formulaBanner: '立面圖要素: 地平線 (GL 最粗線) ； 樓層高度標註 (1FL, 2FL, RFL) ； 外觀材質圖例',
    visualHighlights: [
      { label: '地平線 (Ground Line, GL)', desc: '建築與大地接觸之地面線，為全圖最粗之實線（寬度約 0.7~1.0 mm），穩固圖面視覺重心', badge: '最粗實線' },
      { label: '景深線條層級 (Depth)', desc: '距離觀察者較近之立面量體以中粗線繪製，較遠之後退量體以細線繪製，表現前後景深', badge: '前後層次' },
      { label: '垂直標高標註', desc: '圖面兩側標註各樓層樓地板高程 (1FL, 2FL, 3FL, RFL) 及女兒牆頂高與建築最高點', badge: '垂直尺度' },
    ],
    keyTakeaways: [
      '立面圖命名方式：可以面向方位命名（如東向立面圖、南向立面圖），亦可按主從命名（正立面、背立面、左側立面、右側立面）。',
      '立面圖中所有門窗開口尺寸必須與平面圖嚴格「長對正」與「高平齊」，不得有任何錯位。',
      '屋頂排水坡度與女兒牆頂壓頂金屬板需在立面圖中清晰繪出洩水方向。',
    ],
  },
  'drafting/dimensioning-and-symbols': {
    topicSlug: 'dimensioning-and-symbols',
    title: 'CNS 尺寸標註規範、尺度界線與引出線層級',
    subtitle: '粗中細線條比例 (4:2:1)、尺寸界線、尺寸線與建築尺度單位 (mm/cm)',
    conceptType: 'drafting-projection',
    icon: '📏',
    diagramTitle: 'CNS 3 建築圖尺寸標註三道尺寸線層級（開口細部/軸心跨距/總長總寬）',
    diagramDescription: '展示建築平面圖外圍三道尺寸線：第一道（門窗開口與壁體）、第二道（柱中心軸線跨距）、第三道（建築物總長總寬）。',
    formulaBanner: '線條粗細比例: 粗線 (0.5mm) : 中線 (0.25mm) : 細線 (0.13mm) = 4 : 2 : 1',
    visualHighlights: [
      { label: '第一道尺寸線 (最內)', desc: '標註門窗開口寬度、窗間牆厚度與柱邊細部尺寸', badge: '開口細節' },
      { label: '第二道尺寸線 (中層)', desc: '標註主要柱心軸線與結構隔間跨距尺寸 (Grid to Grid)', badge: '結構軸心' },
      { label: '第三道尺寸線 (最外)', desc: '標註建築物外牆最外緣之總長度與總寬度 (Overall)', badge: '總體輪廓' },
    ],
    keyTakeaways: [
      '建築施工圖尺寸單位「預設一律為公釐 (mm) 或公分 (cm)」，圖面上直接標註數字，不必重複寫出單位符號。',
      '尺寸線不可與其他圖線重疊或相交；尺寸界線應自輪廓線外伸約 2~3 mm，並向外延伸超出尺寸線約 2 mm。',
      '標註直徑符號為 ⌀，半徑符號為 R，球體直徑為 S⌀，球體半徑為 SR，正方形為 □。',
    ],
  },
  'drafting/cad-basics': {
    topicSlug: 'cad-basics',
    title: '電腦輔助繪圖 (CAD) 圖層架構與圖塊屬性',
    subtitle: '圖層顏色/線型/線寬規範、動態圖塊 (Dynamic Blocks) 與世界坐標系 (WCS)',
    conceptType: 'flowchart-logic',
    icon: '💻',
    diagramTitle: 'AutoCAD 標準建築圖層顏色線寬映射矩陣與模型空間/配置空間出圖流',
    diagramDescription: '展示 WALL (粗實白)、DOOR/WIN (中細青)、DIM (細線紅)、TEXT (黃)、HATCH (八號灰) 之圖層管制與 Layout 出圖視埠。',
    formulaBanner: '出圖視埠比例: 1 個圖紙單位 (Paper Space) = n 個模型單位 (Model Space, 1:100 即 1=100)',
    visualHighlights: [
      { label: '圖層分類原則', desc: '按建築構件屬性分層（WALL, COLUMN, BEAM, DOOR, WIN, DIM, TEXT, AXIS, HATCH）', badge: '圖層管理' },
      { label: 'ByLayer 屬性繼承', desc: '所有圖元之顏色 (Color)、線型 (Linetype) 與線寬 (Lineweight) 嚴格設定為 ByLayer', badge: '標準出圖' },
      { label: '模型 vs 配置空間', desc: '模型空間 (Model) 永遠以 1:1 真實尺寸繪製；配置空間 (Layout) 插入圖框並設定視埠比例出圖', badge: '1:1 建模' },
    ],
    keyTakeaways: [
      'CAD 繪圖嚴格禁止將圖元顏色私自指定為獨立顏色，必須統一設為 ByLayer，以確保出圖筆寬表 (CTB) 能正確辨識線寬。',
      '動態圖塊 (Dynamic Block) 可設定拉伸、旋轉、對齊與可見性狀態，大幅減少重繪門窗開口的時間。',
      '世界坐標系 (WCS) 是固定不變的絕對坐標；使用者坐標系 (UCS) 可隨基地傾斜角度自由旋轉對齊。',
    ],
  },
  'drafting/drafting-instruments': {
    topicSlug: 'drafting-instruments',
    title: '製圖儀器之正確操作、保養與精確畫線技法',
    subtitle: '丁字尺 (T-square)、三角板 (30°-60°/45°)、比例尺與圓規鉛芯研磨',
    conceptType: 'drafting-projection',
    icon: '✏️',
    diagramTitle: '丁字尺靠緊圖板左側導邊與兩塊三角板組合繪製 15° 倍數角度幾何技法',
    diagramDescription: '展示丁字尺只用來畫水平線（由左向右畫）、三角板配合丁字尺畫垂直線（由下向上畫）及組合出 15°, 75°, 105° 等角度。',
    formulaBanner: '三角板組合角度: 15° 的整數倍 (15°, 30°, 45°, 60°, 75°, 90°, 105°, 120°, 135°, 150°, 165°)',
    visualHighlights: [
      { label: '丁字尺頭部 (Head)', desc: '必須緊貼圖板左側工作導邊，左手壓住尺身，鉛筆向右傾斜 60° 由左向右繪製水平線', badge: '水平基準' },
      { label: '兩三角板組合', desc: '以 45° 三角板與 30°-60° 三角板疊合，可直接繪出所有 15° 倍數之斜線', badge: '15° 步進' },
      { label: '三稜三面比例尺', desc: '包含 1/100, 1/200, 1/300, 1/400, 1/500, 1/600 六種常用比例，只能用來量取尺度「嚴禁當尺畫線」', badge: '量取專用' },
    ],
    keyTakeaways: [
      '三稜比例尺（三稜鏡尺）刻度精細脆弱，絕對嚴禁用於引導鉛筆或針筆畫線，否則會磨損刻度邊緣導致失真。',
      '繪製直線時鉛筆應朝前進方向傾斜約 60°，並在移動過程中微幅旋轉筆身，確保筆芯均勻磨耗、線寬一致。',
      '圓規鉛芯應研磨成「斜鴨嘴狀（斜切面朝外）」，且鉛芯長度應微短於圓規金屬鋼針約 0.5 mm。',
    ],
  },
  'drafting/geometric-constructions': {
    topicSlug: 'geometric-constructions',
    title: '幾何畫法：等分線段、正多邊形與切線圓弧連接',
    subtitle: '平行線截割法、正五/六邊形圓內接畫法與外切/內切相切弧求圓心',
    conceptType: 'drafting-projection',
    icon: '✨',
    diagramTitle: '圓規尺規作圖等分任意線段與兩垂直直線/圓弧相切圓弧 R 圓心求法',
    diagramDescription: '展示任意線段 n 等分平行線截割法，及圓弧相切求法（外切圓心距離 R1+R，內切圓心距離 R1-R）。',
    formulaBanner: '外切圓弧圓心距: D = R₁ + R ； 內切圓弧圓心距: D = R₁ - R ； 正六邊形邊長 = 外接圓半徑 R',
    visualHighlights: [
      { label: '任意線段等分法', desc: '自端點引一任意斜射線，以圓規截取 n 個等長線段，末端相連後作平行線投影', badge: '比例截割' },
      { label: '外切相切弧 (External)', desc: '求切弧圓心時，以已知兩圓圓心為基準，半徑分別取 (R1 + R) 與 (R2 + R) 畫弧交點', badge: '半徑相加' },
      { label: '正六邊形作圖', desc: '正六邊形邊長剛好等於外接圓半徑 R，以半徑在圓周連續截取 6 等分即可完成', badge: '邊長等於半徑' },
    ],
    keyTakeaways: [
      '相切圓弧作圖核心訣竅：先精確求出「切弧圓心」，再確定「切點位置 (Point of Tangency)」，最後再落筆畫切弧。',
      '兩圓相外切時，切點必在兩圓心之連心線上；相內切時，切點必在兩圓心連心線之延長線上。',
      '正五邊形可利用圓內接黃金分割比例尺規作圖完成，每個內角精確為 108°。',
    ],
  },
  'drafting/auxiliary-views': {
    topicSlug: 'auxiliary-views',
    title: '單斜面正輔助視圖與實形 (True Shape) 投影求法',
    subtitle: '輔助投影面 (Auxiliary Plane)、基準線 (Reference Line) 與斜面真形',
    conceptType: 'drafting-projection',
    icon: '📐',
    diagramTitle: '平行於物體斜面設立輔助投影線，投射展開單斜面真實幾何形狀 (True Shape)',
    diagramDescription: '展示斜面在常規三視圖中產生「縮小變形 (Foreshortened)」，透過平行斜面架設輔助基準線 RL 投射出真實長度與面積。',
    formulaBanner: '輔助視圖原理: 輔助投影面必須「平行於斜面」 ； 投射引線必須「垂直於斜面邊緣線」',
    visualHighlights: [
      { label: '斜面邊緣視圖 (Edge View)', desc: '在某個正視圖中斜面呈現為一條傾斜直線（邊緣視圖）', badge: '線狀視圖' },
      { label: '基準線 (Reference Line)', desc: '平行於該斜面邊緣線劃設基準線 RL，投射引線與 RL 垂直', badge: '平行基準' },
      { label: '深度寬度轉移', desc: '自第三視圖中量取各頂點至基準線之垂直距離，轉移至輔助視圖對應引線上', badge: '距離不變' },
    ],
    keyTakeaways: [
      '斜面在常規正投影三視圖中必呈現「縮影變形 (Foreshortened)」，唯有輔助視圖能呈現其真實形狀與大小 (True Shape)。',
      '正輔助視圖 (Primary Auxiliary View)：輔助投影面垂直於六個主要投影面之其中一個，並平行於斜面。',
      '局部輔助視圖：為了繪圖簡潔清晰，輔助視圖通常只繪製該斜面之真實形狀，其餘無變形部分省略不畫。',
    ],
  },
  'drafting/perspective-projection': {
    topicSlug: 'perspective-projection',
    title: '建築透視圖投影原理與滅點 (VP) 求法',
    subtitle: '一點透視 (平行)、兩點透視 (成角)、三點透視、視平線 (HL) 與基線 (GL)',
    conceptType: 'drafting-projection',
    icon: '🏛️',
    diagramTitle: '兩點透視 (Two-Point Perspective) 視點 (SP)、畫面 (PP)、視平線 (HL) 與左右滅點 (VPL/VPR) 作圖',
    diagramDescription: '展示視平線 HL 決定視角高低（鳥瞰、平視、仰視），立面所有水平線向左右兩滅點 (VP) 匯聚，垂直線保持鉛直。',
    formulaBanner: '透視元素: SP (視點) / PP (畫面) / HL (視平線, 眼睛高度) / GL (地面基線) / VP (消失滅點)',
    visualHighlights: [
      { label: '一點透視 (One-Point)', desc: '物體主要立面平行於畫面 (PP)，只有 1 個中央滅點 (VP)，常用於室內走廊與單一街景', badge: '平行透視' },
      { label: '兩點透視 (Two-Point)', desc: '物體垂直邊接觸畫面，兩側立面斜向後退，產生左滅點 (VPL) 與右滅點 (VPR)，建築外觀最常用', badge: '成角透視' },
      { label: '視平線高低效果', desc: 'HL 高於物體為「鳥瞰圖 (Bird\'s Eye)」；HL 位於正常人眼高 (1.5m) 為「平視圖」；HL 貼近地面為「仰視圖」', badge: '視角高度' },
    ],
    keyTakeaways: [
      '透視圖中最基本空間原則：所有互相平行的水平線條，向遠方延伸後必匯聚交於「視平線 HL 上的同一個滅點 (VP)」。',
      '兩點透視中，唯有「貼在畫面 PP 上之垂直線」具備真實高度尺寸 (True Height)，其餘各部位高度必須由該真高線引退求得。',
      '視點 SP 距離物體過近時會產生嚴重的魚眼鏡頭廣角畸變，視錐角 (Cone of Vision) 應控制在 30° 至 60° 範圍內。',
    ],
  },
  // ==========================================
  // MATERIALS EXPANDED (4 Topics)
  // ==========================================
  'materials/wood': {
    topicSlug: 'wood',
    title: '木材構造特徵、力學異向性與乾縮濕脹',
    subtitle: '順紋抗壓 vs 橫紋抗剪、纖維飽和點 (FSP 25%~30%) 與年輪構造',
    conceptType: 'material-reaction',
    icon: '🪵',
    diagramTitle: '木材微觀年輪構造（心材/邊材/早材/晚材）與三向力學異向性光譜圖',
    diagramDescription: '展示木材順紋方向強度為橫紋數倍之非等向性，以及含水率自生材降至纖維飽和點 (FSP) 與氣乾狀態時的體積乾縮規律。',
    formulaBanner: '含水率 MC (%) = [(W_wet - W_dry) / W_dry] × 100% ； 纖維飽和點 FSP ≈ 25%~30%',
    visualHighlights: [
      { label: '順紋抗壓 (Parallel to Grain)', desc: '木纖維順向承載軸向壓力，強度最高（約 30~50 MPa），主要作為結構木柱', badge: '強度頂峰' },
      { label: '橫紋抗拉 (Perpendicular)', desc: '纖維間橫向膠結微弱，極易沿年輪層間劈裂破壞，工程上嚴禁受拉', badge: '最脆弱方向' },
      { label: '乾縮濕脹 (Shrinkage)', desc: '含水率在 FSP (約28%) 以下時，結合水脫出引發乾縮；乾縮量：弦向 > 徑向 > 順紋方向', badge: '變形規律' },
    ],
    keyTakeaways: [
      '含水率唯有在纖維飽和點 (FSP) 以下變動時，木材的物理尺寸才會發生乾縮與濕脹，且強度隨含水率降低而顯著提升。',
      '木材三向乾縮率大小關係：弦向 (約 6~10%) > 徑向 (約 3~5%) > 順紋方向 (約 0.1~0.3%，幾乎可忽略)。',
      '心材 (Heartwood) 位於樹幹內部，已無輸導養分功能，樹脂沉澱色深，防腐防蟲性顯著優於外圍淡色的邊材 (Sapwood)。',
    ],
  },
  'materials/polymers-asphalt': {
    topicSlug: 'polymers-asphalt',
    title: '高分子聚合物與瀝青材料工程性質',
    subtitle: '瀝青針入度、軟化點、延展性三大指標與防水熱固/熱塑塑膠',
    conceptType: 'material-reaction',
    icon: '🧪',
    diagramTitle: '瀝青三大基本品質檢驗試驗（針入度、環球軟化點、延展性）與溫度敏感性曲線',
    diagramDescription: '展示瀝青自固態、半固態至高溫黏流態之相變特徵，對照 CNS 規範針入度分級 (如 AC-10, AC-20) 與鋪面抗車轍表現。',
    formulaBanner: '瀝青三大檢驗: 針入度 (0.1mm, 100g, 5s, 25℃) ； 環球軟化點 (°C) ； 延展性 (5cm/min, 25℃, cm)',
    visualHighlights: [
      { label: '針入度試驗 (Penetration)', desc: '在 25℃ 下以 100g 標準針刺入 5 秒，深度每 0.1mm 為 1 度；度數越大代表瀝青越軟', badge: '稠度分級' },
      { label: '環球軟化點 (Softening Point)', desc: '以鋼珠在加熱甘油/水中下陷到達底板之溫度，軟化點愈高代表夏季抗車轍變形能力愈佳', badge: '高溫穩定性' },
      { label: '延展性試驗 (Ductility)', desc: '標準「啞鈴型」試體在 25℃ 恆溫水槽以 5cm/min 拉伸至斷裂之長度，代表低溫抗裂柔韌度', badge: '塑性指標' },
    ],
    keyTakeaways: [
      '針入度值越小，代表瀝青越硬稠，適用於炎熱多載重地區；針入度值越大，代表瀝青較軟，適用於寒冷氣候以防脆裂。',
      '熱塑性塑膠（如 PVC、PE、PP）具備加熱軟化、冷卻硬化的可逆特性；熱固性塑膠（如環氧樹脂 Epoxy、酚醛樹脂）固化後不可逆。',
      '改質瀝青 (Modified Asphalt) 透過添加 SBS 或橡膠粉，能大幅拓寬彈性溫度工作區間，減緩路面老化的疲勞裂縫。',
    ],
  },
  'materials/metals': {
    topicSlug: 'metals',
    title: '建築金屬材料與鋼筋力學性能檢驗',
    subtitle: '應力-應變曲線（降伏強度 fy、極限抗拉 fu）、CNS 560 鋼筋號數與冷彎試驗',
    conceptType: 'structural-stress',
    icon: '⛓️',
    diagramTitle: '結構碳鋼與竹節鋼筋拉伸試驗應力-應變（σ-ε）四階段特徵曲線與降伏平原',
    diagramDescription: '展示結構鋼拉伸受力時歷經「彈性直線段 (E=2.04×10⁵ MPa) → 降伏平原 → 應變硬化段 → 頸縮斷裂」之材料響應。',
    formulaBanner: '虎克定律: σ = E · ε ； 降伏強度 fy (SD280 / SD420) ； 斷後伸長率 EL = [(L - L₀) / L₀] × 100%',
    visualHighlights: [
      { label: '明顯降伏平原 (Yield Plateau)', desc: '應力不增加而應變急遽放大，為低碳鋼提供充分塑性延展預警的核心機制', badge: '延性防護' },
      { label: '極限抗拉強度 (Tensile Strength)', desc: '材料所能承受之最大工程應力峰值 fu，超過此點試體截面開始產生局部頸縮 (Necking)', badge: '強度極限' },
      { label: '鋼筋冷彎試驗 (Cold Bend)', desc: '依 CNS 560 規定彎曲 180° 或 90° 後，彎曲外側表面不得產生肉眼可見之龜裂紋', badge: '延性韌性品管' },
    ],
    keyTakeaways: [
      'CNS 560 規定耐震結構用竹節鋼筋（如 SD420W）必須具備「實測抗拉強度與實測降伏強度比值 fu/fy ≥ 1.25」，且實測 fy 不得超標 80 MPa。',
      '鋼材之碳含量越高，硬度與抗拉強度越高，但延展性、衝擊韌性與可焊性則急遽劣化。',
      '鋼筋號數稱謂：CNS 鋼筋以直徑毫米命名（如 D10 直徑 9.53mm、D13 直徑 12.7mm、D25 直徑 25.4mm）。',
    ],
  },
  'materials/green-materials': {
    topicSlug: 'green-materials',
    title: '綠建材四大範疇與室內揮發物 (TVOC) 防衛',
    subtitle: '生態、健康、高性能、再生綠建材四大類別與甲醛逸散率規範',
    conceptType: 'comparative-matrix',
    icon: '🌿',
    diagramTitle: '台灣綠建材標章四大類別（生態/健康/高性能/再生）評估指標與氣候效益矩陣',
    diagramDescription: '展示綠建材全生命週期（採集→製造→使用→回收）評價維度，聚焦健康綠建材氣候箱法檢測與室內空氣品質 (IAQ) 標準。',
    formulaBanner: '健康綠建材逸散極限: 總揮發性有機物 TVOC ≤ 0.19 mg/m²·h ； 甲醛 HCHO ≤ 0.05 mg/m²·h',
    visualHighlights: [
      { label: '健康綠建材 (Healthy)', desc: '低逸散、低污染，嚴格限制甲醛與 TVOC 釋放，保障人體居住呼吸道健康', badge: '佔標章申請 80%' },
      { label: '生態綠建材 (Ecological)', desc: '以天然植物纖維、未經深加工原料為主，符合無匱乏危機且低耗能加工原則', badge: '自然天然' },
      { label: '高性能綠建材 (High Performance)', desc: '具備優異之隔音（樓板衝擊音改善）、隔熱節能（遮陽率/熱傳導）或透水性能', badge: '物理機能' },
      { label: '再生綠建材 (Recycled)', desc: '利用建築廢棄混凝土、廢陶瓷、飛灰高爐石再製，達成循環經濟減廢目標', badge: '循環循環' },
    ],
    keyTakeaways: [
      '建築技術規則防空污規定：建築物室內裝修材料、樓地板及牆面塗料，綠建材使用率應達總面積 60% 以上；室外應達 20% 以上。',
      '健康綠建材試驗係將試體置於密閉小型環境試驗箱（氣候箱法 CNS 16053），連續取樣檢驗 72 小時後的釋出濃度。',
      '高性能防音綠建材能有效使集合住宅分戶樓板衝擊音降低 17 分貝 (dB) 以上，大幅消除上下樓層生活噪音干擾。',
    ],
  },
  // ==========================================
  // SURVEYING COMPLETE (8 Topics)
  // ==========================================
  'surveying/surveying-fundamentals': {
    topicSlug: 'surveying-fundamentals',
    title: '測量學總論、基準橢球體與地球曲率',
    subtitle: '大地測量 vs 平面測量、大地水準面 (Geoid)、正高與橢球高',
    conceptType: 'survey-geometry',
    icon: '🌐',
    diagramTitle: '基準橢球體 (WGS84/TWD97)、大地水準面與正高 (Orthometric Height) 空間幾何模型',
    diagramDescription: '展示平均海水面延伸形成之大地水準面（等位面），對比數學橢球體表面，推導正高 H 與橢球高 h 之間的轉換關係。',
    formulaBanner: '高程幾何: 大地高 h = 正高 H + 水準面差距 N ； 地球曲率差: C = 0.0785 · K² (m, K以km計)',
    visualHighlights: [
      { label: '平面測量適用範圍', desc: '半徑 10 km (或面積 100 km²) 以內之小區域，可將地表鉛垂線視為互相平行，忽略地球曲率', badge: '工程實務基準' },
      { label: '正高系統 (Orthometric)', desc: '沿重力鉛垂線至大地水準面之真實幾何距離，水往低處流的物理依據（台灣水準原點於基隆）', badge: '法定工程標高' },
      { label: '高程測量曲率限制', desc: '距離僅 100m 時曲率差即達 0.8mm，故高程水準測量即便在短距離內亦不可任意忽略曲率影響', badge: '高程嚴格性' },
    ],
    keyTakeaways: [
      '距離測量在小區域 (10km以內) 誤差極小，可忽略曲率；但高程測量對曲率極為敏感，前後視距必須等長以徹底消除球差與氣差。',
      '鉛垂線 (Plumb Line) 為重力方向，水準面 (Level Surface) 處處垂直於鉛垂線，兩者皆為曲面而非幾何平面。',
      '台灣現行坐標系統採用 TWD97 (橫麥卡托二度分帶投影 TM2)，中央經線為 121°E，原點橫坐標平移 250,000 公尺以防負值。',
    ],
  },
  'surveying/indirect-distance-elevation': {
    topicSlug: 'indirect-distance-elevation',
    title: '間接距離測量與三角高程測算幾何',
    subtitle: '視距測量 (Stadia Surveying)、光學經緯儀視距絲與高差三角解算',
    conceptType: 'survey-geometry',
    icon: '🔭',
    diagramTitle: '經緯儀視距絲截距求水平距與三角高程垂直向量解算空間幾何圖解',
    diagramDescription: '展示傾斜視線觀測水準尺時，藉由視距加常數與乘常數（K=100），以及垂直角 α 修正推求水平距離與待測點標高。',
    formulaBanner: '水平距離: D = K · s · cos²α (K=100) ； 標高差: Δh = D · tanα + i - t + (C - R)',
    visualHighlights: [
      { label: '視距絲截距 s (Interval)', desc: '經緯儀十字絲之上絲讀數減下絲讀數 s = (Top - Bottom)，反映視距光學張角', badge: '光學測距' },
      { label: '斜視線二次餘弦修正', desc: '當望遠鏡仰俯角為 α 時，尺面不垂直視線且視線斜向，需乘以 cos²α 換算為水平距', badge: '角度平方修正' },
      { label: '儀器高 (i) 與覘標高 (t)', desc: '高差公式 Δh = D·tanα + i - t，儀高加、目標高減，二者幾何向量直接抵銷', badge: '高程傳遞' },
    ],
    keyTakeaways: [
      '視距常數 K 在現代望遠鏡設計中通常精確製造為 100，加常數 C 內焦透鏡通常為 0。',
      '三角高程測量適用於起伏劇烈之山區或高聳結構（如煙囪、橋塔頂部），免除逐站爬坡搬運水準儀之艱難。',
      '兩差改正（地球曲率與大氣折光）在長距離三角高程中不可忽略，綜合計算法則為 (C - R) = +0.0675 · K² (m)。',
    ],
  },
  'surveying/distance-and-angle': {
    topicSlug: 'distance-and-angle',
    title: '距離量測改正精要與水平角測回法',
    subtitle: '鋼卷尺六大系統誤差改正與測回法 (Repetition Method) 正倒鏡消差',
    conceptType: 'survey-geometry',
    icon: '📐',
    diagramTitle: '光學經緯儀盤左 (Face Left) 與盤右 (Face Right) 觀測消減儀器三軸誤差光學對稱模型',
    diagramDescription: '展示測回法藉由旋轉望遠鏡 180° 配合水平度盤縱轉，徹底消除視準軸不垂直橫軸、橫軸不垂直直盤軸等內部製造機械偏差。',
    formulaBanner: '溫度改正: Ct = α · L · (T - T₀) ； 水平角測回值 = [盤左角 + (盤右角 ± 180°)] / 2',
    visualHighlights: [
      { label: '正倒鏡平均消差 (FL/FR)', desc: '取盤左與盤右觀測值之平均值，可消除「視準軸誤差」、「橫軸誤差」及「度盤偏心差」', badge: '三軸誤差消除' },
      { label: '鋼卷尺溫度改正 (Temperature)', desc: '當現場溫度 T 高於檢定溫度 T₀ (20℃) 時尺身膨脹，量得讀數偏小，需加正改正數', badge: '熱脹冷縮' },
      { label: '垂曲改正 (Sag)', desc: '卷尺懸空測量時因自重下垂呈懸鏈線，使讀數偏大，改正數 Cs 恆為負值', badge: '重力垂下' },
    ],
    keyTakeaways: [
      '正倒鏡觀測「無法消除」豎軸傾斜誤差！因為豎軸不鉛直會使整個度盤傾斜，必須依靠精密的雙軸傾斜感應器或水準管嚴格整平。',
      '量距三大基本改正口訣：尺長長、量出短、應加長；溫度高、尺膨脹、量出短、應加上；懸空量、自重垂、恆減去。',
      '多測回水平角觀測時，各測回應將水平度盤變更初始配置角（180°/n），以消除度盤刻劃不均勻之週期誤差。',
    ],
  },
  'surveying/elevation-and-leveling': {
    topicSlug: 'elevation-and-leveling',
    title: '水準儀幾何高程測量與閉合水準網',
    subtitle: '後視 (BS)、前視 (FS)、視準軸高度 (IH) 與轉點 (TP) 高程傳遞',
    conceptType: 'survey-geometry',
    icon: '📏',
    diagramTitle: '連續水準測量視準線高度 (IH) 遞推與轉點 (TP) 尺墊架設高程閉合迴路圖解',
    diagramDescription: '展示水準儀望遠鏡水平視線讀取標尺，依循「高程 + 後視 = 視準高」、「視準高 - 前視 = 待測點高程」之精確遞推鏈。',
    formulaBanner: '視準高法: IH = Elev_A + BS ； Elev_B = IH - FS ； 容許閉合差: E_allow = ± c√K (mm)',
    visualHighlights: [
      { label: '後視讀數 BS (Backsight)', desc: '瞄準已知標高點之水準尺讀數，用以建立望遠鏡視準線之絕對高程 (IH)', badge: '已知點加法' },
      { label: '前視讀數 FS (Foresight)', desc: '瞄準待測點或轉點之水準尺讀數，以視準高減去前視讀數求得該點標高', badge: '待測點減法' },
      { label: '前後視距等長原則 (Equidistant)', desc: '儀器架設於兩尺正中央使 D_BS = D_FS，可 100% 抵消視準軸微小不平行誤差 (i角誤差)', badge: '黃金消差守則' },
    ],
    keyTakeaways: [
      '前後視距相等 (D_BS = D_FS) 是水準測量最重要的現場守則，可同時消除地球曲率差、大氣折光差以及儀器 i 角誤差。',
      '轉點 (Turning Point, TP) 必須放置堅固金屬尺墊，在後視儀器搬遷前標尺嚴禁移動位置或旋轉底座。',
      '往返測水準測量閉合差計算：往測高差加返測高差之代數和即為閉合差，其值必須小於容許誤差限度（如三等水準 ±12√K mm）。',
    ],
  },
  'surveying/instrument-setup': {
    topicSlug: 'instrument-setup',
    title: '全測站經緯儀電子架設與光電測距 (EDM)',
    subtitle: '整平定心 SOP、雙軸傾斜補償器與大氣氣溫氣壓 (PPM) 改正',
    conceptType: 'survey-geometry',
    icon: '📡',
    diagramTitle: '全測站儀架設整平定心四步曲（定心粗平→腳架伸縮→腳螺旋精平→光學對心器校驗）',
    diagramDescription: '展示光電測距 (EDM) 紅外線/雷射相位差測距幾何原理，對比反射稜鏡常數 (Prism Constant) 與大氣屈折係數調節。',
    formulaBanner: '氣象改正數: PPM = 278.44 - [0.2914 × P(hPa)] / [1 + 0.00366 × T(℃)]',
    visualHighlights: [
      { label: '光學/雷射對心 (Centering)', desc: '移動腳架尖端或儀器基座螺栓，使對心標記與地面控制點釘頭嚴格重合於同鉛垂線', badge: '空間對心' },
      { label: '雙軸自動補償 (Dual-axis)', desc: '內部液體雙軸感應器可動態感測微小傾斜，即時自動修正水平與垂直度盤讀數', badge: '智慧補償' },
      { label: '稜鏡常數設定 (Prism Offset)', desc: '圓形反射稜鏡中心反射點與固定桿軸心之幾何偏差（常見如 0mm 或 -30mm），需正確預設', badge: '測距防呆' },
    ],
    keyTakeaways: [
      '架設儀器標準口訣：圓氣泡看三腳架（踩踏調整長度），長氣泡（管水準器）看腳螺旋（雙手雙向轉動）。',
      '大氣氣溫與氣壓會改變光速傳播介質密度，長距離光電測距前必須實測氣象參數並輸入全測站儀進行 PPM (百萬分之一) 修正。',
      '全測站儀免稜鏡測距功能（直接反射）雖便捷，但遇深色粗糙吸光牆面或大傾角入射時，測距訊號易散射而產生較大測距偏差。',
    ],
  },
  'surveying/traverse-surveying': {
    topicSlug: 'traverse-surveying',
    title: '導線測量角度閉合差分配與方位角推算',
    subtitle: '閉合導線幾何條件、內角和定理與轉向角方位角連續推演 SOP',
    conceptType: 'survey-geometry',
    icon: '🧭',
    diagramTitle: '多邊形閉合導線內角幾何約束與方位角前推法則（前進線左加右減 ± 180°）',
    diagramDescription: '展示 n 邊形閉合導線各站觀測角度，藉由理論內角和推算角度閉合差 fβ，平均分配修正後依序推算各導線邊之坐標方位角。',
    formulaBanner: '內角和幾何理論值: Σβ = (n - 2) × 180° ； 方位角前推: φ_{n+1} = φ_n + 180° ± 轉折角',
    visualHighlights: [
      { label: '角度閉合差檢驗 (Closure Error)', desc: '實測角度和與理論值之差 fβ = Σβ_實測 - (n-2)×180°，若在限差內則反號平均分配', badge: '幾何約束' },
      { label: '方位角連續前推 (Azimuth)', desc: '前進方向測折角：左角則加、右角則減，算得角度大於 360° 減 360°，負值則加 360°', badge: '方位角推算' },
      { label: '閉合導線 vs 附合導線', desc: '閉合導線起訖於同點；附合導線起訖於不同之已知控制點，具備更高等級之防錯幾何檢核', badge: '導線型式' },
    ],
    keyTakeaways: [
      '導線角度閉合差之分配原則：若各角觀測條件相同，閉合差應「反符號」平均分配於各內角；若角度無法整除，餘數分配於短邊夾角處。',
      '方位角推算恆定法則：下一邊方位角 = 前一邊方位角 + 180° + 觀測左角（若大於 360° 則減 360°；若大於 720° 則減 720°）。',
      '若計算出來的角度閉合差超過法規容許上限，代表外業觀測有粗差（如讀錯度盤或瞄錯目標），嚴禁強行平差，必須返工重測。',
    ],
  },
  'surveying/coordinate-computation': {
    topicSlug: 'coordinate-computation',
    title: '導線坐標正反算與羅盤儀平差 (Bowditch Rule)',
    subtitle: '緯距 ΔX = D·cosφ、經距 ΔY = D·sinφ 與精度閉合比檢驗',
    conceptType: 'survey-geometry',
    icon: '📍',
    diagramTitle: '導線邊長幾何正投影分解（緯距/經距）與羅盤儀法按邊長比例閉合差分配模型',
    diagramDescription: '展示各導線邊長投影計算坐標增量，檢核總閉合差 W = √(Wx² + Wy²)，並計算導線閉合比數（如 1/8000）判定外業精度等級。',
    formulaBanner: 'ΔX = D · cosφ ； ΔY = D · sinφ ； 緯距改正: C_x = - (W_x / ΣD) × D_i ； 精度 = 1 / (ΣD / W)',
    visualHighlights: [
      { label: '坐標增量計算 (Increments)', desc: '緯距 ΔX = D·cos(方位角)（南北向）；經距 ΔY = D·sin(方位角)（東西向）', badge: '三角投影' },
      { label: '羅盤儀平差法 (Compass Rule)', desc: '假設角度與距離觀測精度相當，各邊增量改正數嚴格正比於該邊邊長佔總周長之比例', badge: '最常用平差法' },
      { label: '閉合精度比數 (Precision Ratio)', desc: '總周長除以全長閉合差 ΣD / W，數值分母越大代表外業施測品質越精準（統測要求常為 1/5000）', badge: '成果合格門檻' },
    ],
    keyTakeaways: [
      '羅盤儀法（包迪許法 Bowditch Rule）：緯距閉合差 Wx 與經距閉合差 Wy 之改正數，均依各邊邊長佔總導線長之比例分攤。',
      '過渡儀法（Transit Rule）：適用於角度測量精度遠高於距離測量之場合，此時改正數係依緯距或經距絕對值之大小比例分攤。',
      '坐標反算：若已知 A(XA, YA) 與 B(XB, YB)，則兩點間距離 D = √[(XB-XA)² + (YB-YA)²]，方位角 φ = arctan[(YB-YA)/(XB-XA)]。',
    ],
  },
  'surveying/area-and-error': {
    topicSlug: 'area-and-error',
    title: '土地面積解算 (坐標法/倍橫距法) 與誤差傳播定律',
    subtitle: '鞋帶公式 (Shoelace)、倍橫距法 (DMD) 與獨立變數偶然誤差傳播',
    conceptType: 'flowchart-logic',
    icon: '📐',
    diagramTitle: '多邊形頂點坐標交叉相乘鞋帶算法 (Shoelace) 與高斯誤差中誤差傳播路徑模型',
    diagramDescription: '展示封閉地籍界址坐標順時針/逆時針交叉矩陣相乘求解土地平面積，以及觀測值誤差如何平方放大傳遞至最終計算結果。',
    formulaBanner: '坐標面積: 2A = |Σ(X_i · Y_{i+1} - X_{i+1} · Y_i)| ； 誤差傳播: σ_F² = Σ [(∂F/∂x_i)² · σ_i²]',
    visualHighlights: [
      { label: '坐標法面積計算 (Shoelace)', desc: '各界址點坐標依序排列，正斜向相乘總和減去反斜向相乘總和，取絕對值除以 2', badge: '快速無瑕解法' },
      { label: '倍橫距法 DMD (Double Meridian)', desc: '前一邊 DMD + 前邊經距 + 本邊經距 = 本邊 DMD，各邊 DMD 乘以緯距後代數求和', badge: '傳統導線查核' },
      { label: '偶然誤差平方和 (Propagation)', desc: '兩獨立觀測量相加減時，其總和之中誤差並非直接相加，而是方均根值 σ = √(σ₁² + σ₂²)', badge: '誤差傳播金律' },
    ],
    keyTakeaways: [
      '坐標法求面積時，頂點坐標必須按「順時針」或「逆時針」閉合順序排列，首點坐標在行列式底部必須重複書寫一次以形成閉合。',
      '若一距離經過 n 次同精度獨立重複量測，則平均值之中誤差為單次中誤差除以根號 n (σ_avg = σ / √n)，量測次數愈多精度愈高。',
      '矩形長寬獨立測量，長為 a±σa、寬為 b±σb，則面積 A = a·b 之中誤差為 σA = √[(b·σa)² + (a·σb)²]。',
    ],
  },
};

